from .base import *

CONCURRENT_REQUESTS = 1
CLOSESPIDER_ITEMCOUNT = 100
CLOSESPIDER_ERRORCOUNT = 1

HTTPCACHE_ENABLED = True
HTTPCACHE_EXPIRATION_SECS = 0
HTTPCACHE_DIR = "httpcache"
HTTPCACHE_IGNORE_HTTP_CODES = [500, 502, 503, 504, 408, 403]
HTTPCACHE_STORAGE = "scrapy.extensions.httpcache.FilesystemCacheStorage"
