from __future__ import annotations

FOOTLOCKER_CATEGORIES = {
    "New & Trending": {
        "New Arrivals": {
            "All New Arrivals": "/category/new-arrivals.html",
            "Men's": "/category/mens/new-arrivals.html",
            "Women's": "/category/womens/new-arrivals.html",
            "Big Kids'": "/category/kids/new-arrivals.html?query=%3Arelevance%3Acollection_id%3Anew-arrivals%3Agender%3AGirls%27%3Agender%3ABoys%27%3AageRange%3AGrade+School",
            "Little Kids'": "/category/kids/new-arrivals.html?query=%3Arelevance%3Acollection_id%3Anew-arrivals%3AageRange%3APreschool",
            "Infant & Toddler": "/category/kids/new-arrivals.html?query=%3Arelevance%3Acollection_id%3Anew-arrivals%3AageRange%3AInfant%3Agender%3AGirls%27%3Agender%3ABoys%27%3AageRange%3AToddler",
            "Just Released": "/release-calendar/launched.html",
        },
        "Trending Men's": {
            "Fall Favorites ": "/category/collection/fall-essentials/mens.html",
            "Performance Running": "/category/sport/performance-running?query=marathon%3Arelevance%3Agender%3AMen%27s",
            "Signature Basketball": "/category/collection/signature-basketball.html?query=signaturebasketball%3Arelevance%3Agender%3AMen%27s",
            "Shoes Under $100": "/category/sale/mens/shoes/under-100.html",
        },
        "Trending Women's": {
            "Fall Favorites": "/category/collection/fall-essentials/womens.html",
            "Mules & Clogs": "/category/shoes/mules.html?query=mules%3Arelevance%3Agender%3AWomen%27s",
            "Low Profile Sneakers": "/category/collection/low-profile.html?query=lowprofile%3Arelevance%3Agender%3AWomen%27s",
            "Shoes Under $100": "/category/sale/womens/shoes/under-100.html",
        },
        "Shop for the Whole Crew": {
            "\ud83c\udfc0 NBA Fan Shop": "https://www.footlocker.com/category/fan-shop/nba.html",
            "Exclusives ": "/category/collection/exclusives.html",
            "Fall Favorites": "/category/collection/fall-essentials.html",
            "Kids' Shoes Under $50": "/category/sale/kids/shoes/under-50.html",
            "\ud83d\udcfa It Always Will Be Foot Locker": "/always-footlocker.html",
            "\ud83d\udcfa Sole Stories": "https://www.footlocker.com/sole-stories",
        },
        "Promo Images": {
            "Nike Air Max": "/category/shoes/nike/air-max",
            "ASICS": "/category/brands/asics.html",
            "Now at Foot Locker: Salomon": "https://www.footlocker.com/category/brands/salomon",
            "Gift Shop ": "/category/collection/gift-guide/top-gifts.html",
        },
    },
    "Men's": {
        "Shoes": {
            "All Men's Shoes": "/category/mens/shoes.html",
            "Basketball": "/category/sport/basketball/mens/shoes",
            "Casual": "/category/sport/casual/mens/shoes.html",
            "Running": "/category/sport/running/mens/shoes.html",
            "Boots": "/category/mens/shoes/boots.html",
            "Sandals & Slides": "/category/mens/shoes/sandals-slides.html",
            "Shoes Under $100": "/category/sale/mens/shoes/under-100.html",
        },
        "Shop By Shoe Size": {
            "6.0": "/category/mens/shoes/sizes/6-0.html",
            "6.5": "/category/mens/shoes/sizes/6-5.html",
            "7.0": "/category/mens/shoes/sizes/7-0.html",
            "7.5": "/category/mens/shoes/sizes/7-5.html",
            "8.0": "/category/mens/shoes/sizes/8-0.html",
            "8.5": "/category/mens/shoes/sizes/8-5.html",
            "9.0": "/category/mens/shoes/sizes/9-0.html",
            "9.5": "/category/mens/shoes/sizes/9-5.html",
            "10.0": "/category/mens/shoes/sizes/10-0.html",
            "10.5": "/category/mens/shoes/sizes/10-5.html",
            "11.0": "/category/mens/shoes/sizes/11-0.html",
            "11.5": "/category/mens/shoes/sizes/11-5.html",
            "12.0": "/category/mens/shoes/sizes/12-0.html",
            "12.5": "/category/mens/shoes/sizes/12-5.html",
            "13.0": "/category/mens/shoes/sizes/13-0.html",
            "14.0": "/category/mens/shoes/sizes/14-0.html",
            "15.0": "/category/mens/shoes/sizes/15-0.html",
            "16.0": "/category/mens/shoes/sizes/16-0.html",
            "17.0": "/category/mens/shoes/sizes/17-0.html",
            "18.0": "/category/mens/shoes/sizes/18-0.html",
        },
        "Clothing & Accessories": {
            "All Men's Clothing": "/category/mens/clothing.html",
            "All Men's Accessories": "/category/mens/accessories.html",
            "Shorts": "/category/mens/clothing/shorts.html",
            "T-shirts": "/category/mens/clothing/t-shirts.html",
            "Activewear": "/category/clothing/activewear?query=%3Arelevance%3Acollection_id%3Aactivewear%3Agender%3AMen%27s",
            "Pants": "/category/mens/clothing/pants.html",
            "Hoodies & Sweatshirts": "/category/mens/clothing/hoodies.html",
            "Jackets": "/category/mens/clothing/jackets.html",
        },
        "Brands": {
            "Jordan": "/category/mens/jordan.html",
            "Nike": "/category/mens/nike.html",
            "New Balance": "/category/mens/new-balance.html",
            "On": "/category/mens/on.html",
            "Asics": "/category/mens/asics.html",
            "adidas": "/category/mens/adidas.html",
            "Hoka": "/category/mens/shoes/hoka.html",
            "Vans": "/category/mens/vans.html",
        },
        "Featured": {
            "All Men's": "/category/mens.html",
            "New Arrivals": "/category/mens/new-arrivals.html",
            "Fall Favorites": "/category/collection/fall-essentials/mens.html",
            "\ud83c\udfc0 NBA Fan Shop": "https://www.footlocker.com/category/fan-shop/nba/mens.html",
            "Exclusives": "/category/collection/exclusives/mens.html",
            "Black Owned Brands": "/category/collection/black-owned-brands/mens.html",
            "Trending Styles ": "/category/collection/trending?query=%3Arelevance%3Acollection_id%3Atrending-styles%3Agender%3AMen%27s",
            "Performance Running": "/category/sport/performance-running?query=marathon%3Arelevance%3Agender%3AMen%27s",
        },
        "Promo Images": {
            "Fleece": "/category/mens/clothing/fleece",
            "Boots": "/category/mens/shoes/boots",
            "LCKR": "https://www.footlocker.com/category/brands/lckr",
            "Top Rated Styles": "/category/mens/top-rated-styles.html",
        },
    },
    "Women's": {
        "Shoes": {
            "All Women's Shoes": "/category/womens/shoes.html",
            "Casual": "/category/sport/casual/womens/shoes.html",
            "Running": "/category/sport/running/womens/shoes.html",
            "Basketball": "/category/sport/basketball/womens/shoes.html",
            "Boots": "/category/womens/shoes/boots.html",
            "Mules & Clogs ": "/category/shoes/mules.html?query=mules%3Arelevance%3Agender%3AWomen%27s",
            "Shoes Under $100": "/category/sale/womens/shoes/under-100.html",
            "Mommy & Me": "/category/collection/full-family.html",
            "Low Profile Sneakers": "/category/collection/low-profile.html?query=lowprofile%3Arelevance%3Agender%3AWomen%27s",
        },
        "Shop By Shoe Size": {
            "5.0": "/category/womens/shoes/sizes/5-0.html",
            "5.5": "/category/womens/shoes/sizes/5-5.html",
            "6.0": "/category/womens/shoes/sizes/6-0.html",
            "6.5": "/category/womens/shoes/sizes/6-5.html",
            "7.0": "/category/womens/shoes/sizes/7-0.html",
            "7.5": "/category/womens/shoes/sizes/7-5.html",
            "8.0": "/category/womens/shoes/sizes/8-0.html",
            "8.5": "/category/womens/shoes/sizes/8-5.html",
            "9.0": "/category/womens/shoes/sizes/9-0.html",
            "9.5": "/category/womens/shoes/sizes/9-5.html",
            "10.0": "/category/womens/shoes/sizes/10-0.html",
            "10.5": "/category/womens/shoes/sizes/10-5.html",
            "11.0": "/category/womens/shoes/sizes/11-0.html",
            "12.0": "/category/womens/shoes/sizes/12-0.html",
        },
        "Clothing & Accessories": {
            "All Women's Clothing": "/category/womens/clothing.html",
            "All Women's Accessories": "/category/womens/accessories.html",
            "Shirts & Tops": "/category/womens/clothing/shirts-tops.html",
            "Activewear": "/category/clothing/activewear?query=%3Arelevance%3Acollection_id%3Aactivewear%3Agender%3AWomen%27s",
            "Dresses & Skirts": "/category/womens/clothing/dresses.html",
            "Shorts": "/category/womens/clothing/shorts.html",
            "Hoodies & Sweatshirts": "/category/womens/clothing/hoodies.html",
            "Pants": "/category/womens/clothing/pants.html",
            "Jackets ": "/category/womens/clothing/jackets.html",
        },
        "Brands": {
            "Nike": "/category/womens/nike.html",
            "New Balance": "/category/womens/new-balance.html",
            "adidas": "/category/womens/adidas.html",
            "Jordan": "/category/womens/jordan.html",
            "On": "/category/womens/on.html",
            "HOKA": "/category/womens/hoka.html",
            "Salomon": "/category/brands/salomon?query=%3Arelevance%3Acollection_id%3Asalomon%3Agender%3AWomen%27s",
            "Asics": "/category/womens/asics.html",
        },
        "Featured": {
            "All Women's": "/category/womens.html",
            "New Arrivals": "/category/womens/new-arrivals.html",
            "Fall Favorites": "/category/collection/fall-essentials/womens.html",
            "Exclusives": "/category/collection/exclusives/womens.html",
            "Trending Styles ": "/category/collection/trending?query=%3Arelevance%3Acollection_id%3Atrending-styles%3Agender%3AWomen%27s",
            "Black Owned Brands": "/category/collection/black-owned-brands.html",
            "\ud83c\udfc0 NBA Fan Shop": "https://www.footlocker.com/category/fan-shop/nba.html",
        },
        "Promo Images": {
            "Fall Favorites": "https://www.footlocker.com/category/collection/fall-essentials/womens.html",
            "Fleece": "https://www.footlocker.com/category/womens/clothing/fleece",
            "UGG": "https://www.footlocker.com/category/womens/ugg.html",
            "Top Rated Styles": "/category/womens/top-rated-styles.html",
        },
    },
    "Kids'": {
        "Big Kids' Shoe Size": {
            "3.5": "/category/grade-school/shoes/sizes/3-5.html",
            "4.0": "/category/grade-school/shoes/sizes/4-0.html",
            "4.5": "/category/grade-school/shoes/sizes/4-5.html",
            "5.0": "/category/grade-school/shoes/sizes/5-0.html",
            "5.5": "/category/grade-school/shoes/sizes/5-5.html",
            "6.0": "/category/grade-school/shoes/sizes/6-0.html",
            "6.5": "/category/grade-school/shoes/sizes/6-5.html",
            "7.0": "/category/grade-school/shoes/sizes/7-0.html",
        },
        "Little Kids' Shoe Size ": {
            "10.5": "/category/preschool/shoes/sizes/10-5.html",
            "11.0": "/category/preschool/shoes/sizes/11-0.html",
            "11.5": "/category/preschool/shoes/sizes/11-5.html",
            "12.0": "/category/preschool/shoes/sizes/12-0.html",
            "12.5": "/category/preschool/shoes/sizes/12-5.html",
            "13.0": "/category/preschool/shoes/sizes/13-0.html",
            "13.5": "/category/preschool/shoes/sizes/13-5.html",
            "1.0": "/category/preschool/shoes/sizes/1-0.html",
            "1.5": "/category/preschool/shoes/sizes/1-5.html",
            "2.0": "/category/preschool/shoes/sizes/2-0.html",
            "2.5": "/category/preschool/shoes/sizes/2-5.html",
            "3.0": "/category/preschool/shoes/sizes/3-0.html",
        },
        "Infant & Toddler Shoe Size": {
            "1.0": "/category/kids/shoes/infant-toddler/sizes/1-0.html",
            "2.0": "/category/kids/shoes/infant-toddler/sizes/2-0.html",
            "3.0": "/category/kids/shoes/infant-toddler/sizes/3-0.html",
            "4.0": "/category/kids/shoes/infant-toddler/sizes/4-0.html",
            "5.0": "/category/kids/shoes/infant-toddler/sizes/5-0.html",
            "6.0": "/category/kids/shoes/infant-toddler/sizes/6-0.html",
            "7.0": "/category/kids/shoes/infant-toddler/sizes/7-0.html",
            "8.0": "/category/kids/shoes/infant-toddler/sizes/8-0.html",
            "9.0": "/category/kids/shoes/infant-toddler/sizes/9-0.html",
            "10.0": "/category/kids/shoes/infant-toddler/sizes/10-0.html",
        },
        "Shoes": {
            "All Big Kids": "/category/kids/shoes/grade-school.html",
            "All Little Kids": "/category/kids/shoes/pre-school.html",
            "All Infant & Toddler": "/category/kids/shoes/infant-toddler.html",
            "Basketball": "/category/sport/basketball/kids/shoes.html",
            "Casual": "/category/sport/casual/kids/shoes.html",
            "Running": "/category/sport/running/kids/shoes.html",
            "Boots": "/category/kids/shoes/boots.html",
            "Slip-Ons": "/category/kids/shoes/slip-on.html",
            "Shoes Under $50": "/category/sale/kids/shoes/under-50.html",
            "Trending Styles": "/category/collection/trending?query=%3Arelevance%3Acollection_id%3Atrending-styles%3Agender%3ABoys%27%3Agender%3AGirls%27",
        },
        "Clothing & Accessories": {
            "All Clothing": "/category/kids/clothing.html",
            "All Accessories": "/category/kids/accessories.html",
            "Boys' Clothing": "/category/boys/clothing.html",
            "Girls' Clothing": "/category/girls/clothing.html",
            "Matching Sets": "/category/clothing/matching-sets/kids.html",
            "T-shirts": "/category/kids/clothing/t-shirts.html",
            "Shorts": "/category/kids/clothing/shorts.html",
            "Hoodies & Sweatshirts": "/category/kids/clothing/hoodies.html",
            "Pants": "/category/kids/clothing/pants.html",
            "Jackets": "/category/kids/clothing/jackets.html",
        },
        "Brands": {
            "Nike": "/category/kids/nike.html",
            "Jordan": "/category/kids/jordan.html",
            "Vans": "/category/kids/vans.html",
            "New Balance": "/category/kids/new-balance.html",
            "adidas": "/category/kids/adidas",
            "On": "/category/kids/on.html",
            "Asics": "/category/kids/asics.html",
            "PUMA": "/category/kids/puma.html",
        },
        "Promo Images": {
            "Fall Favorites": "https://www.footlocker.com/category/collection/fall-essentials.html?query=%3Arelevance%3Acollection_id%3Afall-essentials%3Agender%3ABoys%27%3Agender%3AGirls%27",
            "Fleece": "/category/kids/clothing/fleece",
            "New Arrivals": "https://www.footlocker.com/category/kids/new-arrivals.html",
            "Top Rated Styles": "/category/kids/top-rated-styles.html",
        },
    },
    "Brands": {
        "Shop All Brands": {},
        "Featured Brands": {
            "PSD": "/category/brands/PSD.html",
            "PUMA": "/category/brands/puma.html",
            "Reebok": "/category/brands/reebok.html",
            "Salomon": "/category/brands/salomon.html",
            "Saucony": "/category/brands/saucony.html",
            "Timberland": "/category/brands/timberland.html",
            "UGG": "/category/brands/ugg.html",
            "Under Armour": "/category/brands/under-armour.html",
            "Vans": "/category/brands/vans.html",
        },
        "Promo Images": {
            "Nike": "/category/brands/nike.html",
            "Jordan": "/category/brands/jordan.html",
            "adidas": "/category/brands/adidas.html",
            "New Balance": "/category/brands/new-balance.html",
        },
    },
    "Sale": {
        "Shop All Sale": {
            "All Sale": "/category/sale.html",
            "Promo Code Eligible ": "/category/save-now.html",
            "Air Jordan 1 Sale: Adults' $79.99 & Kids' $69.99 and Under": "https://www.footlocker.com/en/category/sale/jordan/aj1-adults-and-kids",
            "Top Rated on Sale": "https://www.footlocker.com/en/category/sale/top-rated-styles.html",
        },
        " Men's": {
            "All Men's Sale": "/category/sale/mens.html",
            "Shoes": "/category/sale/mens/shoes.html",
            "Clothing": "/category/sale/mens/clothing.html",
            "Accessories": "/category/sale/mens/accessories.html",
        },
        "Women's": {
            "All Women's Sale": "/category/sale/womens.html",
            "Shoes": "/category/sale/womens/shoes.html",
            "Clothing": "/category/sale/womens/clothing.html",
            "Accessories": "/category/sale/womens/accessories.html",
        },
        "Kids'": {
            "All Kids' Sale": "/category/sale/kids.html",
            "Shoes": "/category/sale/kids/shoes.html",
            "Clothing": "/category/sale/kids/clothing.html",
            "Accessories": "/category/sale/kids/accessories.html",
        },
        "Shop Sale By Price ": {
            "Under $100": "/category/sale.html?query=%3Arelevance%3Acollection_id%3Asale%3Aprice%3A-inf-25%3Aprice%3A25-50%3Aprice%3A50-75%3Aprice%3A\"75\"-\"100\"",
            "Under $75 ": "/category/sale.html?query=%3Arelevance%3Acollection_id%3Asale%3Aprice%3A-inf-25%3Aprice%3A25-50%3Aprice%3A\"50\"-\"75\"",
            "Under $50": "/category/sale.html?query=%3Arelevance%3Acollection_id%3Asale%3Aprice%3A-inf-25%3Aprice%3A\"25\"-\"50\"",
            "Under $25": "/category/sale.html?query=%3Arelevance%3Acollection_id%3Asale%3Aprice%3A\"-inf\"-\"25\"",
        },
        "Promo Images": {
            "Shop Nike Sale": "/category/sale/nike.html",
            "Shop Jordan Sale": "/category/sale/jordan.html",
            "Shop adidas Sale": "/category/sale/adidas.html",
            "Shop New Balance Sale": "/category/sale/new-balance.html",
        },
    },
}
