HOMES_CATEGORIES = [
    {"category": "new-york-ny", "url": "https://www.homes.com/new-york-ny/"},
    {"category": "los-angeles-ca", "url": "https://www.homes.com/los-angeles-ca/"},
    {"category": "chicago-il", "url": "https://www.homes.com/chicago-il/"},
    {"category": "houston-tx", "url": "https://www.homes.com/houston-tx/"},
    {"category": "phoenix-az", "url": "https://www.homes.com/phoenix-az/"},
    {"category": "philadelphia-pa", "url": "https://www.homes.com/philadelphia-pa/"},
    {"category": "san-antonio-tx", "url": "https://www.homes.com/san-antonio-tx/"},
    {"category": "san-diego-ca", "url": "https://www.homes.com/san-diego-ca/"},
    {"category": "dallas-tx", "url": "https://www.homes.com/dallas-tx/"},
    {"category": "san-jose-ca", "url": "https://www.homes.com/san-jose-ca/"},
    {"category": "austin-tx", "url": "https://www.homes.com/austin-tx/"},
    {"category": "jacksonville-fl", "url": "https://www.homes.com/jacksonville-fl/"},
    {"category": "fort-worth-tx", "url": "https://www.homes.com/fort-worth-tx/"},
    {"category": "columbus-oh", "url": "https://www.homes.com/columbus-oh/"},
    {"category": "charlotte-nc", "url": "https://www.homes.com/charlotte-nc/"},
    {"category": "indianapolis-in", "url": "https://www.homes.com/indianapolis-in/"},
    {"category": "san-francisco-ca", "url": "https://www.homes.com/san-francisco-ca/"},
    {"category": "seattle-wa", "url": "https://www.homes.com/seattle-wa/"},
    {"category": "denver-co", "url": "https://www.homes.com/denver-co/"},
    {"category": "boston-ma", "url": "https://www.homes.com/boston-ma/"},
]
