from __future__ import annotations

"""L.L.Bean category inventory (issue #172).

Captured 2026-10-02 from the homepage SSR hydration state
(`window.__INITIAL_STATE__.headerReducer.navData`), which carries the full
11-department browse tree. The site `sitemap.xml` is bot-challenged, so the
header nav is the canonical taxonomy source.

The raw capture is committed at `sample/llbean-categories-flat.json`
(department -> node) so the inventory can be diffed when L.L.Bean renames a
department. That capture is flattened one level (the `subDepts` parent path is
not preserved), so the same leaf `name` occurs under several departments --
`resolve_target_url()` matches on `category` exactly, so names are made unique
here by qualifying with the department and, where that still collides, the
category id.
"""

LLBEAN_CATEGORIES: list[dict] = [
    {
        "category": "Gift Shop",
        "department": "Gift Shop",
        "category_id": 509870,
        "url": "https://www.llbean.com/llb/shop/509870",
    },
    {
        "category": "Gifts for Her",
        "department": "Gift Shop",
        "category_id": 507087,
        "url": "https://www.llbean.com/llb/shop/507087",
    },
    {
        "category": "Gifts for Him",
        "department": "Gift Shop",
        "category_id": 507074,
        "url": "https://www.llbean.com/llb/shop/507074",
    },
    {
        "category": "Gifts for Kids",
        "department": "Gift Shop",
        "category_id": 507102,
        "url": "https://www.llbean.com/llb/shop/507102",
    },
    {
        "category": "Gifts for Everyone",
        "department": "Gift Shop",
        "category_id": 1000010136,
        "url": "https://www.llbean.com/llb/shop/1000010136",
    },
    {
        "category": "NYT Wirecutter Picks",
        "department": "Gift Shop",
        "category_id": 1000010392,
        "url": "https://www.llbean.com/llb/shop/1000010392",
    },
    {
        "category": "Stocking Stuffers",
        "department": "Gift Shop",
        "category_id": 20010550,
        "url": "https://www.llbean.com/llb/shop/20010550",
    },
    {
        "category": "Food Gift Sets",
        "department": "Gift Shop",
        "category_id": 1000010393,
        "url": "https://www.llbean.com/llb/shop/1000010393",
    },
    {
        "category": "Gifts Under $75",
        "department": "Gift Shop",
        "category_id": 20011144,
        "url": "https://www.llbean.com/llb/shop/20011144",
    },
    {
        "category": "Gifts under $50",
        "department": "Gift Shop",
        "category_id": 20010549,
        "url": "https://www.llbean.com/llb/shop/20010549",
    },
    {
        "category": "Gifts Under $25",
        "department": "Gift Shop",
        "category_id": 20011145,
        "url": "https://www.llbean.com/llb/shop/20011145",
    },
    {
        "category": "NEW",
        "department": "NEW",
        "category_id": 511742,
        "url": "https://www.llbean.com/llb/shop/511742",
    },
    {
        "category": "NEW / Women's",
        "department": "NEW",
        "category_id": 20010101,
        "url": "https://www.llbean.com/llb/shop/20010101",
    },
    {
        "category": "NEW / Clothing [511744]",
        "department": "NEW",
        "category_id": 511744,
        "url": "https://www.llbean.com/llb/shop/511744",
    },
    {
        "category": "NEW / Outerwear [508877]",
        "department": "NEW",
        "category_id": 508877,
        "url": "https://www.llbean.com/llb/shop/508877",
    },
    {
        "category": "NEW / Footwear [508896]",
        "department": "NEW",
        "category_id": 508896,
        "url": "https://www.llbean.com/llb/shop/508896",
    },
    {
        "category": "NEW / Men's",
        "department": "NEW",
        "category_id": 20010102,
        "url": "https://www.llbean.com/llb/shop/20010102",
    },
    {
        "category": "NEW / Clothing [511743]",
        "department": "NEW",
        "category_id": 511743,
        "url": "https://www.llbean.com/llb/shop/511743",
    },
    {
        "category": "NEW / Outerwear [508868]",
        "department": "NEW",
        "category_id": 508868,
        "url": "https://www.llbean.com/llb/shop/508868",
    },
    {
        "category": "NEW / Footwear [508895]",
        "department": "NEW",
        "category_id": 508895,
        "url": "https://www.llbean.com/llb/shop/508895",
    },
    {
        "category": "NEW / Kids'",
        "department": "NEW",
        "category_id": 20010103,
        "url": "https://www.llbean.com/llb/shop/20010103",
    },
    {
        "category": "NEW / Clothing [511786]",
        "department": "NEW",
        "category_id": 511786,
        "url": "https://www.llbean.com/llb/shop/511786",
    },
    {
        "category": "NEW / Outerwear [518580]",
        "department": "NEW",
        "category_id": 518580,
        "url": "https://www.llbean.com/llb/shop/518580",
    },
    {
        "category": "NEW / Footwear [514692]",
        "department": "NEW",
        "category_id": 514692,
        "url": "https://www.llbean.com/llb/shop/514692",
    },
    {
        "category": "NEW / Outdoor Equipment",
        "department": "NEW",
        "category_id": 511747,
        "url": "https://www.llbean.com/llb/shop/511747",
    },
    {
        "category": "NEW / Bags & Travel",
        "department": "NEW",
        "category_id": 511749,
        "url": "https://www.llbean.com/llb/shop/511749",
    },
    {
        "category": "NEW / Home Goods",
        "department": "NEW",
        "category_id": 511750,
        "url": "https://www.llbean.com/llb/shop/511750",
    },
    {
        "category": "Clothing / Clothing",
        "department": "Clothing",
        "category_id": 12,
        "url": "https://www.llbean.com/llb/shop/12",
    },
    {
        "category": "Clothing / Women's",
        "department": "Clothing",
        "category_id": 27,
        "url": "https://www.llbean.com/llb/shop/27",
    },
    {
        "category": "Clothing / Shop by Size Range [516869]",
        "department": "Clothing",
        "category_id": 516869,
        "url": "https://www.llbean.com/llb/shop/516869",
    },
    {
        "category": "Clothing / Plus Sizes",
        "department": "Clothing",
        "category_id": 617,
        "url": "https://www.llbean.com/llb/shop/617",
    },
    {
        "category": "Clothing / Shirts & Tops [503109]",
        "department": "Clothing",
        "category_id": 503109,
        "url": "https://www.llbean.com/llb/shop/503109",
    },
    {
        "category": "Clothing / Sweatshirts & Fleece [518642]",
        "department": "Clothing",
        "category_id": 518642,
        "url": "https://www.llbean.com/llb/shop/518642",
    },
    {
        "category": "Clothing / Sweaters [503111]",
        "department": "Clothing",
        "category_id": 503111,
        "url": "https://www.llbean.com/llb/shop/503111",
    },
    {
        "category": "Clothing / Shorts & Skorts [518641]",
        "department": "Clothing",
        "category_id": 518641,
        "url": "https://www.llbean.com/llb/shop/518641",
    },
    {
        "category": "Clothing / Pants & Jeans [503110]",
        "department": "Clothing",
        "category_id": 503110,
        "url": "https://www.llbean.com/llb/shop/503110",
    },
    {
        "category": "Clothing / Dresses [503112]",
        "department": "Clothing",
        "category_id": 503112,
        "url": "https://www.llbean.com/llb/shop/503112",
    },
    {
        "category": "Clothing / Swimwear [503114]",
        "department": "Clothing",
        "category_id": 503114,
        "url": "https://www.llbean.com/llb/shop/503114",
    },
    {
        "category": "Clothing / Sleepwear [503113]",
        "department": "Clothing",
        "category_id": 503113,
        "url": "https://www.llbean.com/llb/shop/503113",
    },
    {
        "category": "Clothing / Base Layers [511210]",
        "department": "Clothing",
        "category_id": 511210,
        "url": "https://www.llbean.com/llb/shop/511210",
    },
    {
        "category": "Clothing / Petite Sizes",
        "department": "Clothing",
        "category_id": 889,
        "url": "https://www.llbean.com/llb/shop/889",
    },
    {
        "category": "Clothing / Shirts & Tops [506438]",
        "department": "Clothing",
        "category_id": 506438,
        "url": "https://www.llbean.com/llb/shop/506438",
    },
    {
        "category": "Clothing / Sweaters [510523]",
        "department": "Clothing",
        "category_id": 510523,
        "url": "https://www.llbean.com/llb/shop/510523",
    },
    {
        "category": "Clothing / Sweatshirts & Fleece [518639]",
        "department": "Clothing",
        "category_id": 518639,
        "url": "https://www.llbean.com/llb/shop/518639",
    },
    {
        "category": "Clothing / Pants & Jeans [506440]",
        "department": "Clothing",
        "category_id": 506440,
        "url": "https://www.llbean.com/llb/shop/506440",
    },
    {
        "category": "Clothing / Dresses [506450]",
        "department": "Clothing",
        "category_id": 506450,
        "url": "https://www.llbean.com/llb/shop/506450",
    },
    {
        "category": "Clothing / Sleepwear [506456]",
        "department": "Clothing",
        "category_id": 506456,
        "url": "https://www.llbean.com/llb/shop/506456",
    },
    {
        "category": "Clothing / Base Layers [513168]",
        "department": "Clothing",
        "category_id": 513168,
        "url": "https://www.llbean.com/llb/shop/513168",
    },
    {
        "category": "Clothing / Tall Sizes [518021]",
        "department": "Clothing",
        "category_id": 518021,
        "url": "https://www.llbean.com/llb/shop/518021",
    },
    {
        "category": "Clothing / Tees & Tanks",
        "department": "Clothing",
        "category_id": 504209,
        "url": "https://www.llbean.com/llb/shop/504209",
    },
    {
        "category": "Clothing / Shirts & Tops [607]",
        "department": "Clothing",
        "category_id": 607,
        "url": "https://www.llbean.com/llb/shop/607",
    },
    {
        "category": "Shirts & Button-Downs",
        "department": "Clothing",
        "category_id": 502972,
        "url": "https://www.llbean.com/llb/shop/502972",
    },
    {
        "category": "Clothing / Flannel Shirts [506332]",
        "department": "Clothing",
        "category_id": 506332,
        "url": "https://www.llbean.com/llb/shop/506332",
    },
    {
        "category": "Clothing / Shirt-Jackets [518515]",
        "department": "Clothing",
        "category_id": 518515,
        "url": "https://www.llbean.com/llb/shop/518515",
    },
    {
        "category": "Clothing / Sweaters [611]",
        "department": "Clothing",
        "category_id": 611,
        "url": "https://www.llbean.com/llb/shop/611",
    },
    {
        "category": "Clothing / Sweatshirts [886]",
        "department": "Clothing",
        "category_id": 886,
        "url": "https://www.llbean.com/llb/shop/886",
    },
    {
        "category": "Clothing / Fleece [504732]",
        "department": "Clothing",
        "category_id": 504732,
        "url": "https://www.llbean.com/llb/shop/504732",
    },
    {
        "category": "Clothing / Jeans [513283]",
        "department": "Clothing",
        "category_id": 513283,
        "url": "https://www.llbean.com/llb/shop/513283",
    },
    {
        "category": "Clothing / Pants [622]",
        "department": "Clothing",
        "category_id": 622,
        "url": "https://www.llbean.com/llb/shop/622",
    },
    {
        "category": "Clothing / Pants [504199]",
        "department": "Clothing",
        "category_id": 504199,
        "url": "https://www.llbean.com/llb/shop/504199",
    },
    {
        "category": "Leggings & Tights",
        "department": "Clothing",
        "category_id": 518324,
        "url": "https://www.llbean.com/llb/shop/518324",
    },
    {
        "category": "Cropped & Capri",
        "department": "Clothing",
        "category_id": 516133,
        "url": "https://www.llbean.com/llb/shop/516133",
    },
    {
        "category": "Clothing / Shorts & Skorts [513280]",
        "department": "Clothing",
        "category_id": 513280,
        "url": "https://www.llbean.com/llb/shop/513280",
    },
    {
        "category": "Clothing / Dresses & Skirts",
        "department": "Clothing",
        "category_id": 506213,
        "url": "https://www.llbean.com/llb/shop/506213",
    },
    {
        "category": "Clothing / Swimwear [624]",
        "department": "Clothing",
        "category_id": 624,
        "url": "https://www.llbean.com/llb/shop/624",
    },
    {
        "category": "Separates",
        "department": "Clothing",
        "category_id": 517610,
        "url": "https://www.llbean.com/llb/shop/517610",
    },
    {
        "category": "Clothing / Tops [503320]",
        "department": "Clothing",
        "category_id": 503320,
        "url": "https://www.llbean.com/llb/shop/503320",
    },
    {
        "category": "Clothing / Bottoms",
        "department": "Clothing",
        "category_id": 507505,
        "url": "https://www.llbean.com/llb/shop/507505",
    },
    {
        "category": "One-Piece",
        "department": "Clothing",
        "category_id": 503314,
        "url": "https://www.llbean.com/llb/shop/503314",
    },
    {
        "category": "Cover-Ups & Rash Guards",
        "department": "Clothing",
        "category_id": 516246,
        "url": "https://www.llbean.com/llb/shop/516246",
    },
    {
        "category": "Board & Swim Shorts",
        "department": "Clothing",
        "category_id": 516247,
        "url": "https://www.llbean.com/llb/shop/516247",
    },
    {
        "category": "Clothing / Sleepwear [613]",
        "department": "Clothing",
        "category_id": 613,
        "url": "https://www.llbean.com/llb/shop/613",
    },
    {
        "category": "Pajamas & Nightgowns",
        "department": "Clothing",
        "category_id": 502983,
        "url": "https://www.llbean.com/llb/shop/502983",
    },
    {
        "category": "Clothing / Robes [502982]",
        "department": "Clothing",
        "category_id": 502982,
        "url": "https://www.llbean.com/llb/shop/502982",
    },
    {
        "category": "Clothing / Base Layers [503056]",
        "department": "Clothing",
        "category_id": 503056,
        "url": "https://www.llbean.com/llb/shop/503056",
    },
    {
        "category": "Clothing / Activewear [509757]",
        "department": "Clothing",
        "category_id": 509757,
        "url": "https://www.llbean.com/llb/shop/509757",
    },
    {
        "category": "Clothing / Shirts [502975]",
        "department": "Clothing",
        "category_id": 502975,
        "url": "https://www.llbean.com/llb/shop/502975",
    },
    {
        "category": "Clothing / Sweatshirts & Fleece [515996]",
        "department": "Clothing",
        "category_id": 515996,
        "url": "https://www.llbean.com/llb/shop/515996",
    },
    {
        "category": "Clothing / Pants [505698]",
        "department": "Clothing",
        "category_id": 505698,
        "url": "https://www.llbean.com/llb/shop/505698",
    },
    {
        "category": "Clothing / Shorts & Skorts [512834]",
        "department": "Clothing",
        "category_id": 512834,
        "url": "https://www.llbean.com/llb/shop/512834",
    },
    {
        "category": "Clothing / Accessories [614]",
        "department": "Clothing",
        "category_id": 614,
        "url": "https://www.llbean.com/llb/shop/614",
    },
    {
        "category": "Clothing / Hats & Headwear [502976]",
        "department": "Clothing",
        "category_id": 502976,
        "url": "https://www.llbean.com/llb/shop/502976",
    },
    {
        "category": "Clothing / Winter Hats & Beanies [516612]",
        "department": "Clothing",
        "category_id": 516612,
        "url": "https://www.llbean.com/llb/shop/516612",
    },
    {
        "category": "Clothing / Rain & Sun Hats [516614]",
        "department": "Clothing",
        "category_id": 516614,
        "url": "https://www.llbean.com/llb/shop/516614",
    },
    {
        "category": "Clothing / Baseball Caps & Visors [516615]",
        "department": "Clothing",
        "category_id": 516615,
        "url": "https://www.llbean.com/llb/shop/516615",
    },
    {
        "category": "Clothing / Gloves & Mittens [502977]",
        "department": "Clothing",
        "category_id": 502977,
        "url": "https://www.llbean.com/llb/shop/502977",
    },
    {
        "category": "Clothing / Scarves & Neck Gaiters [513945]",
        "department": "Clothing",
        "category_id": 513945,
        "url": "https://www.llbean.com/llb/shop/513945",
    },
    {
        "category": "Underwear",
        "department": "Clothing",
        "category_id": 512672,
        "url": "https://www.llbean.com/llb/shop/512672",
    },
    {
        "category": "Clothing / Socks [502980]",
        "department": "Clothing",
        "category_id": 502980,
        "url": "https://www.llbean.com/llb/shop/502980",
    },
    {
        "category": "Clothing / Belts [502979]",
        "department": "Clothing",
        "category_id": 502979,
        "url": "https://www.llbean.com/llb/shop/502979",
    },
    {
        "category": "Sunglasses",
        "department": "Clothing",
        "category_id": 804,
        "url": "https://www.llbean.com/llb/shop/804",
    },
    {
        "category": "Clothing / Men's",
        "department": "Clothing",
        "category_id": 26,
        "url": "https://www.llbean.com/llb/shop/26",
    },
    {
        "category": "Clothing / Shop by Size Range [516868]",
        "department": "Clothing",
        "category_id": 516868,
        "url": "https://www.llbean.com/llb/shop/516868",
    },
    {
        "category": "Clothing / Tall Sizes [813]",
        "department": "Clothing",
        "category_id": 813,
        "url": "https://www.llbean.com/llb/shop/813",
    },
    {
        "category": "Clothing / Shirts [506186]",
        "department": "Clothing",
        "category_id": 506186,
        "url": "https://www.llbean.com/llb/shop/506186",
    },
    {
        "category": "Clothing / Sweaters [506189]",
        "department": "Clothing",
        "category_id": 506189,
        "url": "https://www.llbean.com/llb/shop/506189",
    },
    {
        "category": "Clothing / Sweatshirts & Fleece [518635]",
        "department": "Clothing",
        "category_id": 518635,
        "url": "https://www.llbean.com/llb/shop/518635",
    },
    {
        "category": "Clothing / Pants & Jeans [506187]",
        "department": "Clothing",
        "category_id": 506187,
        "url": "https://www.llbean.com/llb/shop/506187",
    },
    {
        "category": "Clothing / Sleepwear [512110]",
        "department": "Clothing",
        "category_id": 512110,
        "url": "https://www.llbean.com/llb/shop/512110",
    },
    {
        "category": "Clothing / Base Layers [518636]",
        "department": "Clothing",
        "category_id": 518636,
        "url": "https://www.llbean.com/llb/shop/518636",
    },
    {
        "category": "Clothing / XXXL Sizes",
        "department": "Clothing",
        "category_id": 518728,
        "url": "https://www.llbean.com/llb/shop/518728",
    },
    {
        "category": "Men's 28\" and 29\" Inseams",
        "department": "Clothing",
        "category_id": 518729,
        "url": "https://www.llbean.com/llb/shop/518729",
    },
    {
        "category": "Clothing / T-Shirts & Polos",
        "department": "Clothing",
        "category_id": 20010166,
        "url": "https://www.llbean.com/llb/shop/20010166",
    },
    {
        "category": "T-Shirts",
        "department": "Clothing",
        "category_id": 504193,
        "url": "https://www.llbean.com/llb/shop/504193",
    },
    {
        "category": "Polo Shirts",
        "department": "Clothing",
        "category_id": 506786,
        "url": "https://www.llbean.com/llb/shop/506786",
    },
    {
        "category": "Clothing / Shirts [589]",
        "department": "Clothing",
        "category_id": 589,
        "url": "https://www.llbean.com/llb/shop/589",
    },
    {
        "category": "Clothing / Flannel Shirts [505538]",
        "department": "Clothing",
        "category_id": 505538,
        "url": "https://www.llbean.com/llb/shop/505538",
    },
    {
        "category": "Casual Button-Down Shirts",
        "department": "Clothing",
        "category_id": 506874,
        "url": "https://www.llbean.com/llb/shop/506874",
    },
    {
        "category": "Clothing / Shirt-Jackets [518514]",
        "department": "Clothing",
        "category_id": 518514,
        "url": "https://www.llbean.com/llb/shop/518514",
    },
    {
        "category": "Henleys",
        "department": "Clothing",
        "category_id": 514115,
        "url": "https://www.llbean.com/llb/shop/514115",
    },
    {
        "category": "Dress Shirts",
        "department": "Clothing",
        "category_id": 504190,
        "url": "https://www.llbean.com/llb/shop/504190",
    },
    {
        "category": "Clothing / Sweaters [594]",
        "department": "Clothing",
        "category_id": 594,
        "url": "https://www.llbean.com/llb/shop/594",
    },
    {
        "category": "Clothing / Sweatshirts [907]",
        "department": "Clothing",
        "category_id": 907,
        "url": "https://www.llbean.com/llb/shop/907",
    },
    {
        "category": "Clothing / Fleece [506674]",
        "department": "Clothing",
        "category_id": 506674,
        "url": "https://www.llbean.com/llb/shop/506674",
    },
    {
        "category": "Clothing / Jeans [513284]",
        "department": "Clothing",
        "category_id": 513284,
        "url": "https://www.llbean.com/llb/shop/513284",
    },
    {
        "category": "Clothing / Pants [502921]",
        "department": "Clothing",
        "category_id": 502921,
        "url": "https://www.llbean.com/llb/shop/502921",
    },
    {
        "category": "Clothing / Shorts [908]",
        "department": "Clothing",
        "category_id": 908,
        "url": "https://www.llbean.com/llb/shop/908",
    },
    {
        "category": "Clothing / Swimwear [511548]",
        "department": "Clothing",
        "category_id": 511548,
        "url": "https://www.llbean.com/llb/shop/511548",
    },
    {
        "category": "Swim Trunks",
        "department": "Clothing",
        "category_id": 516602,
        "url": "https://www.llbean.com/llb/shop/516602",
    },
    {
        "category": "Rash Guards",
        "department": "Clothing",
        "category_id": 516603,
        "url": "https://www.llbean.com/llb/shop/516603",
    },
    {
        "category": "Clothing / Sleepwear [595]",
        "department": "Clothing",
        "category_id": 595,
        "url": "https://www.llbean.com/llb/shop/595",
    },
    {
        "category": "Pajamas",
        "department": "Clothing",
        "category_id": 502849,
        "url": "https://www.llbean.com/llb/shop/502849",
    },
    {
        "category": "Clothing / Robes [502851]",
        "department": "Clothing",
        "category_id": 502851,
        "url": "https://www.llbean.com/llb/shop/502851",
    },
    {
        "category": "Clothing / Base Layers [516180]",
        "department": "Clothing",
        "category_id": 516180,
        "url": "https://www.llbean.com/llb/shop/516180",
    },
    {
        "category": "Clothing / Activewear [509723]",
        "department": "Clothing",
        "category_id": 509723,
        "url": "https://www.llbean.com/llb/shop/509723",
    },
    {
        "category": "Clothing / Shirts [512864]",
        "department": "Clothing",
        "category_id": 512864,
        "url": "https://www.llbean.com/llb/shop/512864",
    },
    {
        "category": "Clothing / Sweatshirts & Fleece [515982]",
        "department": "Clothing",
        "category_id": 515982,
        "url": "https://www.llbean.com/llb/shop/515982",
    },
    {
        "category": "Clothing / Pants [506778]",
        "department": "Clothing",
        "category_id": 506778,
        "url": "https://www.llbean.com/llb/shop/506778",
    },
    {
        "category": "Clothing / Shorts [512860]",
        "department": "Clothing",
        "category_id": 512860,
        "url": "https://www.llbean.com/llb/shop/512860",
    },
    {
        "category": "Clothing / Accessories [596]",
        "department": "Clothing",
        "category_id": 596,
        "url": "https://www.llbean.com/llb/shop/596",
    },
    {
        "category": "Clothing / Hats & Headwear [502857]",
        "department": "Clothing",
        "category_id": 502857,
        "url": "https://www.llbean.com/llb/shop/502857",
    },
    {
        "category": "Clothing / Winter Hats & Beanies [502860]",
        "department": "Clothing",
        "category_id": 502860,
        "url": "https://www.llbean.com/llb/shop/502860",
    },
    {
        "category": "Clothing / Rain & Sun Hats [502858]",
        "department": "Clothing",
        "category_id": 502858,
        "url": "https://www.llbean.com/llb/shop/502858",
    },
    {
        "category": "Clothing / Baseball Caps & Visors [502859]",
        "department": "Clothing",
        "category_id": 502859,
        "url": "https://www.llbean.com/llb/shop/502859",
    },
    {
        "category": "Clothing / Gloves & Mittens [502856]",
        "department": "Clothing",
        "category_id": 502856,
        "url": "https://www.llbean.com/llb/shop/502856",
    },
    {
        "category": "Clothing / Scarves & Neck Gaiters [502953]",
        "department": "Clothing",
        "category_id": 502953,
        "url": "https://www.llbean.com/llb/shop/502953",
    },
    {
        "category": "Underwear & Boxers",
        "department": "Clothing",
        "category_id": 516179,
        "url": "https://www.llbean.com/llb/shop/516179",
    },
    {
        "category": "Clothing / Socks [502854]",
        "department": "Clothing",
        "category_id": 502854,
        "url": "https://www.llbean.com/llb/shop/502854",
    },
    {
        "category": "Clothing / Belts [502855]",
        "department": "Clothing",
        "category_id": 502855,
        "url": "https://www.llbean.com/llb/shop/502855",
    },
    {
        "category": "Wallets",
        "department": "Clothing",
        "category_id": 506664,
        "url": "https://www.llbean.com/llb/shop/506664",
    },
    {
        "category": "Clothing / Kids'",
        "department": "Clothing",
        "category_id": 28,
        "url": "https://www.llbean.com/llb/shop/28",
    },
    {
        "category": "Clothing / Tops [503368]",
        "department": "Clothing",
        "category_id": 503368,
        "url": "https://www.llbean.com/llb/shop/503368",
    },
    {
        "category": "Clothing / Pants & Shorts",
        "department": "Clothing",
        "category_id": 503570,
        "url": "https://www.llbean.com/llb/shop/503570",
    },
    {
        "category": "Clothing / Sleepwear [503560]",
        "department": "Clothing",
        "category_id": 503560,
        "url": "https://www.llbean.com/llb/shop/503560",
    },
    {
        "category": "Clothing / Base Layers [513852]",
        "department": "Clothing",
        "category_id": 513852,
        "url": "https://www.llbean.com/llb/shop/513852",
    },
    {
        "category": "Clothing / Accessories [503563]",
        "department": "Clothing",
        "category_id": 503563,
        "url": "https://www.llbean.com/llb/shop/503563",
    },
    {
        "category": "Clothing / Toddler & Baby",
        "department": "Clothing",
        "category_id": 289,
        "url": "https://www.llbean.com/llb/shop/289",
    },
    {
        "category": "Outerwear / Outerwear",
        "department": "Outerwear",
        "category_id": 516567,
        "url": "https://www.llbean.com/llb/shop/516567",
    },
    {
        "category": "Outerwear / Women's",
        "department": "Outerwear",
        "category_id": 610,
        "url": "https://www.llbean.com/llb/shop/610",
    },
    {
        "category": "Outerwear / Shop by Size Range [518627]",
        "department": "Outerwear",
        "category_id": 518627,
        "url": "https://www.llbean.com/llb/shop/518627",
    },
    {
        "category": "Outerwear / Plus Sizes",
        "department": "Outerwear",
        "category_id": 503108,
        "url": "https://www.llbean.com/llb/shop/503108",
    },
    {
        "category": "Outerwear / Petite Sizes",
        "department": "Outerwear",
        "category_id": 506446,
        "url": "https://www.llbean.com/llb/shop/506446",
    },
    {
        "category": "Outerwear / Tall Sizes [518637]",
        "department": "Outerwear",
        "category_id": 518637,
        "url": "https://www.llbean.com/llb/shop/518637",
    },
    {
        "category": "Outerwear / Insulated Jackets [504735]",
        "department": "Outerwear",
        "category_id": 504735,
        "url": "https://www.llbean.com/llb/shop/504735",
    },
    {
        "category": "Outerwear / Casual Jackets [504734]",
        "department": "Outerwear",
        "category_id": 504734,
        "url": "https://www.llbean.com/llb/shop/504734",
    },
    {
        "category": "Outerwear / Rain Jackets & Shells [506593]",
        "department": "Outerwear",
        "category_id": 506593,
        "url": "https://www.llbean.com/llb/shop/506593",
    },
    {
        "category": "Outerwear / Windbreakers [506594]",
        "department": "Outerwear",
        "category_id": 506594,
        "url": "https://www.llbean.com/llb/shop/506594",
    },
    {
        "category": "Outerwear / Vests [504729]",
        "department": "Outerwear",
        "category_id": 504729,
        "url": "https://www.llbean.com/llb/shop/504729",
    },
    {
        "category": "Outerwear / Snow & Rain Pants [516609]",
        "department": "Outerwear",
        "category_id": 516609,
        "url": "https://www.llbean.com/llb/shop/516609",
    },
    {
        "category": "Outerwear / Accessories [518844]",
        "department": "Outerwear",
        "category_id": 518844,
        "url": "https://www.llbean.com/llb/shop/518844",
    },
    {
        "category": "Outerwear / Men's",
        "department": "Outerwear",
        "category_id": 593,
        "url": "https://www.llbean.com/llb/shop/593",
    },
    {
        "category": "Outerwear / Shop by Size Range [518626]",
        "department": "Outerwear",
        "category_id": 518626,
        "url": "https://www.llbean.com/llb/shop/518626",
    },
    {
        "category": "Outerwear / Tall Sizes [506188]",
        "department": "Outerwear",
        "category_id": 506188,
        "url": "https://www.llbean.com/llb/shop/506188",
    },
    {
        "category": "Outerwear / XXXL Sizes",
        "department": "Outerwear",
        "category_id": 518839,
        "url": "https://www.llbean.com/llb/shop/518839",
    },
    {
        "category": "Outerwear / Insulated Jackets [506673]",
        "department": "Outerwear",
        "category_id": 506673,
        "url": "https://www.llbean.com/llb/shop/506673",
    },
    {
        "category": "Outerwear / Casual Jackets [506677]",
        "department": "Outerwear",
        "category_id": 506677,
        "url": "https://www.llbean.com/llb/shop/506677",
    },
    {
        "category": "Outerwear / Rain Jackets & Shells [506675]",
        "department": "Outerwear",
        "category_id": 506675,
        "url": "https://www.llbean.com/llb/shop/506675",
    },
    {
        "category": "Outerwear / Windbreakers [506676]",
        "department": "Outerwear",
        "category_id": 506676,
        "url": "https://www.llbean.com/llb/shop/506676",
    },
    {
        "category": "Outerwear / Vests [504715]",
        "department": "Outerwear",
        "category_id": 504715,
        "url": "https://www.llbean.com/llb/shop/504715",
    },
    {
        "category": "Outerwear / Snow & Rain Pants [516604]",
        "department": "Outerwear",
        "category_id": 516604,
        "url": "https://www.llbean.com/llb/shop/516604",
    },
    {
        "category": "Outerwear / Accessories [518845]",
        "department": "Outerwear",
        "category_id": 518845,
        "url": "https://www.llbean.com/llb/shop/518845",
    },
    {
        "category": "Outerwear / Kids'",
        "department": "Outerwear",
        "category_id": 503369,
        "url": "https://www.llbean.com/llb/shop/503369",
    },
    {
        "category": "Outerwear / Insulated Jackets [509976]",
        "department": "Outerwear",
        "category_id": 509976,
        "url": "https://www.llbean.com/llb/shop/509976",
    },
    {
        "category": "Fleece & Lightweight Jackets",
        "department": "Outerwear",
        "category_id": 1000010293,
        "url": "https://www.llbean.com/llb/shop/1000010293",
    },
    {
        "category": "Rain Jackets",
        "department": "Outerwear",
        "category_id": 517473,
        "url": "https://www.llbean.com/llb/shop/517473",
    },
    {
        "category": "Pants & Suits",
        "department": "Outerwear",
        "category_id": 503565,
        "url": "https://www.llbean.com/llb/shop/503565",
    },
    {
        "category": "Outerwear / Toddler & Baby",
        "department": "Outerwear",
        "category_id": 518610,
        "url": "https://www.llbean.com/llb/shop/518610",
    },
    {
        "category": "Footwear / Footwear",
        "department": "Footwear",
        "category_id": 474,
        "url": "https://www.llbean.com/llb/shop/474",
    },
    {
        "category": "Footwear / Women's",
        "department": "Footwear",
        "category_id": 630,
        "url": "https://www.llbean.com/llb/shop/630",
    },
    {
        "category": "Footwear / Boots [506708]",
        "department": "Footwear",
        "category_id": 506708,
        "url": "https://www.llbean.com/llb/shop/506708",
    },
    {
        "category": "Footwear / Hiking Boots & Shoes [507000]",
        "department": "Footwear",
        "category_id": 507000,
        "url": "https://www.llbean.com/llb/shop/507000",
    },
    {
        "category": "Footwear / Casual [503070]",
        "department": "Footwear",
        "category_id": 503070,
        "url": "https://www.llbean.com/llb/shop/503070",
    },
    {
        "category": "Footwear / Rain [506713]",
        "department": "Footwear",
        "category_id": 506713,
        "url": "https://www.llbean.com/llb/shop/506713",
    },
    {
        "category": "Footwear / Bean Boots [513859]",
        "department": "Footwear",
        "category_id": 513859,
        "url": "https://www.llbean.com/llb/shop/513859",
    },
    {
        "category": "Footwear / Snow [506711]",
        "department": "Footwear",
        "category_id": 506711,
        "url": "https://www.llbean.com/llb/shop/506711",
    },
    {
        "category": "Footwear / Hunting [507963]",
        "department": "Footwear",
        "category_id": 507963,
        "url": "https://www.llbean.com/llb/shop/507963",
    },
    {
        "category": "Footwear / Sneakers & Shoes [506705]",
        "department": "Footwear",
        "category_id": 506705,
        "url": "https://www.llbean.com/llb/shop/506705",
    },
    {
        "category": "Footwear / Walking [516630]",
        "department": "Footwear",
        "category_id": 516630,
        "url": "https://www.llbean.com/llb/shop/516630",
    },
    {
        "category": "Footwear / Casual [503077]",
        "department": "Footwear",
        "category_id": 503077,
        "url": "https://www.llbean.com/llb/shop/503077",
    },
    {
        "category": "Footwear / Running [503066]",
        "department": "Footwear",
        "category_id": 503066,
        "url": "https://www.llbean.com/llb/shop/503066",
    },
    {
        "category": "Footwear / Hiking [516629]",
        "department": "Footwear",
        "category_id": 516629,
        "url": "https://www.llbean.com/llb/shop/516629",
    },
    {
        "category": "Footwear / Sandals & Water Shoes [503423]",
        "department": "Footwear",
        "category_id": 503423,
        "url": "https://www.llbean.com/llb/shop/503423",
    },
    {
        "category": "Footwear / Sandals [503443]",
        "department": "Footwear",
        "category_id": 503443,
        "url": "https://www.llbean.com/llb/shop/503443",
    },
    {
        "category": "Flip-Flops",
        "department": "Footwear",
        "category_id": 506589,
        "url": "https://www.llbean.com/llb/shop/506589",
    },
    {
        "category": "Footwear / Water Shoes [503441]",
        "department": "Footwear",
        "category_id": 503441,
        "url": "https://www.llbean.com/llb/shop/503441",
    },
    {
        "category": "Footwear / Slippers [503422]",
        "department": "Footwear",
        "category_id": 503422,
        "url": "https://www.llbean.com/llb/shop/503422",
    },
    {
        "category": "Footwear / Accessories [20010704]",
        "department": "Footwear",
        "category_id": 20010704,
        "url": "https://www.llbean.com/llb/shop/20010704",
    },
    {
        "category": "Footwear / Men's",
        "department": "Footwear",
        "category_id": 629,
        "url": "https://www.llbean.com/llb/shop/629",
    },
    {
        "category": "Footwear / Boots [506794]",
        "department": "Footwear",
        "category_id": 506794,
        "url": "https://www.llbean.com/llb/shop/506794",
    },
    {
        "category": "Footwear / Hiking Boots & Shoes [506795]",
        "department": "Footwear",
        "category_id": 506795,
        "url": "https://www.llbean.com/llb/shop/506795",
    },
    {
        "category": "Footwear / Casual [506772]",
        "department": "Footwear",
        "category_id": 506772,
        "url": "https://www.llbean.com/llb/shop/506772",
    },
    {
        "category": "Footwear / Rain [511065]",
        "department": "Footwear",
        "category_id": 511065,
        "url": "https://www.llbean.com/llb/shop/511065",
    },
    {
        "category": "Footwear / Bean Boots [513858]",
        "department": "Footwear",
        "category_id": 513858,
        "url": "https://www.llbean.com/llb/shop/513858",
    },
    {
        "category": "Footwear / Snow [506796]",
        "department": "Footwear",
        "category_id": 506796,
        "url": "https://www.llbean.com/llb/shop/506796",
    },
    {
        "category": "Footwear / Hunting [508843]",
        "department": "Footwear",
        "category_id": 508843,
        "url": "https://www.llbean.com/llb/shop/508843",
    },
    {
        "category": "Footwear / Sneakers & Shoes [506791]",
        "department": "Footwear",
        "category_id": 506791,
        "url": "https://www.llbean.com/llb/shop/506791",
    },
    {
        "category": "Footwear / Casual [506764]",
        "department": "Footwear",
        "category_id": 506764,
        "url": "https://www.llbean.com/llb/shop/506764",
    },
    {
        "category": "Footwear / Walking [516623]",
        "department": "Footwear",
        "category_id": 516623,
        "url": "https://www.llbean.com/llb/shop/516623",
    },
    {
        "category": "Footwear / Hiking [516622]",
        "department": "Footwear",
        "category_id": 516622,
        "url": "https://www.llbean.com/llb/shop/516622",
    },
    {
        "category": "Footwear / Running [506765]",
        "department": "Footwear",
        "category_id": 506765,
        "url": "https://www.llbean.com/llb/shop/506765",
    },
    {
        "category": "Footwear / Sandals & Water Shoes [503381]",
        "department": "Footwear",
        "category_id": 503381,
        "url": "https://www.llbean.com/llb/shop/503381",
    },
    {
        "category": "Footwear / Sandals [516626]",
        "department": "Footwear",
        "category_id": 516626,
        "url": "https://www.llbean.com/llb/shop/516626",
    },
    {
        "category": "Footwear / Water Shoes [516624]",
        "department": "Footwear",
        "category_id": 516624,
        "url": "https://www.llbean.com/llb/shop/516624",
    },
    {
        "category": "Footwear / Slippers [503380]",
        "department": "Footwear",
        "category_id": 503380,
        "url": "https://www.llbean.com/llb/shop/503380",
    },
    {
        "category": "Footwear / Accessories [514536]",
        "department": "Footwear",
        "category_id": 514536,
        "url": "https://www.llbean.com/llb/shop/514536",
    },
    {
        "category": "Footwear / Kids'",
        "department": "Footwear",
        "category_id": 651,
        "url": "https://www.llbean.com/llb/shop/651",
    },
    {
        "category": "Hiking Boots and Shoes",
        "department": "Footwear",
        "category_id": 503723,
        "url": "https://www.llbean.com/llb/shop/503723",
    },
    {
        "category": "Rain & Snow Boots",
        "department": "Footwear",
        "category_id": 503719,
        "url": "https://www.llbean.com/llb/shop/503719",
    },
    {
        "category": "Footwear / Slippers [503721]",
        "department": "Footwear",
        "category_id": 503721,
        "url": "https://www.llbean.com/llb/shop/503721",
    },
    {
        "category": "Footwear / Sandals & Water Shoes [503575]",
        "department": "Footwear",
        "category_id": 503575,
        "url": "https://www.llbean.com/llb/shop/503575",
    },
    {
        "category": "Footwear / Socks",
        "department": "Footwear",
        "category_id": 513665,
        "url": "https://www.llbean.com/llb/shop/513665",
    },
    {
        "category": "Footwear / Toddler & Baby",
        "department": "Footwear",
        "category_id": 632,
        "url": "https://www.llbean.com/llb/shop/632",
    },
    {
        "category": "Outdoor Equipment / Outdoor Equipment",
        "department": "Outdoor Equipment",
        "category_id": 29,
        "url": "https://www.llbean.com/llb/shop/29",
    },
    {
        "category": "Outdoor Equipment / Camping & Hiking",
        "department": "Outdoor Equipment",
        "category_id": 915,
        "url": "https://www.llbean.com/llb/shop/915",
    },
    {
        "category": "Tents & Shelters",
        "department": "Outdoor Equipment",
        "category_id": 1096,
        "url": "https://www.llbean.com/llb/shop/1096",
    },
    {
        "category": "Tents",
        "department": "Outdoor Equipment",
        "category_id": 506832,
        "url": "https://www.llbean.com/llb/shop/506832",
    },
    {
        "category": "Sun & Bug Shelters",
        "department": "Outdoor Equipment",
        "category_id": 512954,
        "url": "https://www.llbean.com/llb/shop/512954",
    },
    {
        "category": "Footprints & Accessories",
        "department": "Outdoor Equipment",
        "category_id": 507851,
        "url": "https://www.llbean.com/llb/shop/507851",
    },
    {
        "category": "Sleeping Bags, Pads & Blankets",
        "department": "Outdoor Equipment",
        "category_id": 1097,
        "url": "https://www.llbean.com/llb/shop/1097",
    },
    {
        "category": "Sleeping Bags",
        "department": "Outdoor Equipment",
        "category_id": 506831,
        "url": "https://www.llbean.com/llb/shop/506831",
    },
    {
        "category": "Sleeping Bag Accessories",
        "department": "Outdoor Equipment",
        "category_id": 3892,
        "url": "https://www.llbean.com/llb/shop/3892",
    },
    {
        "category": "Sleeping Pads & Cots",
        "department": "Outdoor Equipment",
        "category_id": 512955,
        "url": "https://www.llbean.com/llb/shop/512955",
    },
    {
        "category": "Hiking Backpacks",
        "department": "Outdoor Equipment",
        "category_id": 916,
        "url": "https://www.llbean.com/llb/shop/916",
    },
    {
        "category": "Outdoor Equipment / Backpacks",
        "department": "Outdoor Equipment",
        "category_id": 1098,
        "url": "https://www.llbean.com/llb/shop/1098",
    },
    {
        "category": "Hydration Packs & Reservoirs",
        "department": "Outdoor Equipment",
        "category_id": 516632,
        "url": "https://www.llbean.com/llb/shop/516632",
    },
    {
        "category": "Waist Packs",
        "department": "Outdoor Equipment",
        "category_id": 850,
        "url": "https://www.llbean.com/llb/shop/850",
    },
    {
        "category": "Hiking Poles & Gaiters",
        "department": "Outdoor Equipment",
        "category_id": 504412,
        "url": "https://www.llbean.com/llb/shop/504412",
    },
    {
        "category": "Hiking Poles",
        "department": "Outdoor Equipment",
        "category_id": 507761,
        "url": "https://www.llbean.com/llb/shop/507761",
    },
    {
        "category": "Flashlights, Headlamps & Lanterns",
        "department": "Outdoor Equipment",
        "category_id": 918,
        "url": "https://www.llbean.com/llb/shop/918",
    },
    {
        "category": "Flashlights",
        "department": "Outdoor Equipment",
        "category_id": 506864,
        "url": "https://www.llbean.com/llb/shop/506864",
    },
    {
        "category": "Headlamps",
        "department": "Outdoor Equipment",
        "category_id": 507967,
        "url": "https://www.llbean.com/llb/shop/507967",
    },
    {
        "category": "Lanterns",
        "department": "Outdoor Equipment",
        "category_id": 506867,
        "url": "https://www.llbean.com/llb/shop/506867",
    },
    {
        "category": "Camping Furniture",
        "department": "Outdoor Equipment",
        "category_id": 9925,
        "url": "https://www.llbean.com/llb/shop/9925",
    },
    {
        "category": "Outdoor Equipment / Hammocks",
        "department": "Outdoor Equipment",
        "category_id": 502034,
        "url": "https://www.llbean.com/llb/shop/502034",
    },
    {
        "category": "Chairs",
        "department": "Outdoor Equipment",
        "category_id": 9051,
        "url": "https://www.llbean.com/llb/shop/9051",
    },
    {
        "category": "Tables",
        "department": "Outdoor Equipment",
        "category_id": 500192,
        "url": "https://www.llbean.com/llb/shop/500192",
    },
    {
        "category": "Camping Kitchen",
        "department": "Outdoor Equipment",
        "category_id": 1099,
        "url": "https://www.llbean.com/llb/shop/1099",
    },
    {
        "category": "Coolers",
        "department": "Outdoor Equipment",
        "category_id": 9970,
        "url": "https://www.llbean.com/llb/shop/9970",
    },
    {
        "category": "Outdoor Equipment / Outdoor Accessories",
        "department": "Outdoor Equipment",
        "category_id": 516713,
        "url": "https://www.llbean.com/llb/shop/516713",
    },
    {
        "category": "Beach Towels & Outdoor Blankets",
        "department": "Outdoor Equipment",
        "category_id": 514485,
        "url": "https://www.llbean.com/llb/shop/514485",
    },
    {
        "category": "Knives & Tools",
        "department": "Outdoor Equipment",
        "category_id": 917,
        "url": "https://www.llbean.com/llb/shop/917",
    },
    {
        "category": "Knives",
        "department": "Outdoor Equipment",
        "category_id": 506870,
        "url": "https://www.llbean.com/llb/shop/506870",
    },
    {
        "category": "Knife Sharpeners & Accessories",
        "department": "Outdoor Equipment",
        "category_id": 508820,
        "url": "https://www.llbean.com/llb/shop/508820",
    },
    {
        "category": "Outdoor Equipment / Fishing",
        "department": "Outdoor Equipment",
        "category_id": 507923,
        "url": "https://www.llbean.com/llb/shop/507923",
    },
    {
        "category": "Waders & Wading Boots",
        "department": "Outdoor Equipment",
        "category_id": 1109,
        "url": "https://www.llbean.com/llb/shop/1109",
    },
    {
        "category": "Waders",
        "department": "Outdoor Equipment",
        "category_id": 3934,
        "url": "https://www.llbean.com/llb/shop/3934",
    },
    {
        "category": "Wading Boots",
        "department": "Outdoor Equipment",
        "category_id": 3937,
        "url": "https://www.llbean.com/llb/shop/3937",
    },
    {
        "category": "Wading Accessories",
        "department": "Outdoor Equipment",
        "category_id": 4905,
        "url": "https://www.llbean.com/llb/shop/4905",
    },
    {
        "category": "Vest Packs & Storage",
        "department": "Outdoor Equipment",
        "category_id": 512608,
        "url": "https://www.llbean.com/llb/shop/512608",
    },
    {
        "category": "Vest Packs & Gear Bags",
        "department": "Outdoor Equipment",
        "category_id": 1193,
        "url": "https://www.llbean.com/llb/shop/1193",
    },
    {
        "category": "Rod & Reel Cases",
        "department": "Outdoor Equipment",
        "category_id": 4332,
        "url": "https://www.llbean.com/llb/shop/4332",
    },
    {
        "category": "Fly & Tackle Boxes",
        "department": "Outdoor Equipment",
        "category_id": 500145,
        "url": "https://www.llbean.com/llb/shop/500145",
    },
    {
        "category": "Rods",
        "department": "Outdoor Equipment",
        "category_id": 516648,
        "url": "https://www.llbean.com/llb/shop/516648",
    },
    {
        "category": "Outdoor Equipment / Fly [506543]",
        "department": "Outdoor Equipment",
        "category_id": 506543,
        "url": "https://www.llbean.com/llb/shop/506543",
    },
    {
        "category": "Outdoor Equipment / Spin [500042]",
        "department": "Outdoor Equipment",
        "category_id": 500042,
        "url": "https://www.llbean.com/llb/shop/500042",
    },
    {
        "category": "Reels",
        "department": "Outdoor Equipment",
        "category_id": 516649,
        "url": "https://www.llbean.com/llb/shop/516649",
    },
    {
        "category": "Outdoor Equipment / Fly [1111]",
        "department": "Outdoor Equipment",
        "category_id": 1111,
        "url": "https://www.llbean.com/llb/shop/1111",
    },
    {
        "category": "Outdoor Equipment / Spin [500043]",
        "department": "Outdoor Equipment",
        "category_id": 500043,
        "url": "https://www.llbean.com/llb/shop/500043",
    },
    {
        "category": "Rod & Reel Combos",
        "department": "Outdoor Equipment",
        "category_id": 516650,
        "url": "https://www.llbean.com/llb/shop/516650",
    },
    {
        "category": "Outdoor Equipment / Fly [2136]",
        "department": "Outdoor Equipment",
        "category_id": 2136,
        "url": "https://www.llbean.com/llb/shop/2136",
    },
    {
        "category": "Outdoor Equipment / Spin [9965]",
        "department": "Outdoor Equipment",
        "category_id": 9965,
        "url": "https://www.llbean.com/llb/shop/9965",
    },
    {
        "category": "Flies & Lures",
        "department": "Outdoor Equipment",
        "category_id": 500155,
        "url": "https://www.llbean.com/llb/shop/500155",
    },
    {
        "category": "Freshwater Flies",
        "department": "Outdoor Equipment",
        "category_id": 513956,
        "url": "https://www.llbean.com/llb/shop/513956",
    },
    {
        "category": "Saltwater Flies",
        "department": "Outdoor Equipment",
        "category_id": 8179,
        "url": "https://www.llbean.com/llb/shop/8179",
    },
    {
        "category": "Fly Lines, Leaders & Tippets",
        "department": "Outdoor Equipment",
        "category_id": 1112,
        "url": "https://www.llbean.com/llb/shop/1112",
    },
    {
        "category": "Fly Line",
        "department": "Outdoor Equipment",
        "category_id": 3943,
        "url": "https://www.llbean.com/llb/shop/3943",
    },
    {
        "category": "Leaders & Tippet",
        "department": "Outdoor Equipment",
        "category_id": 3945,
        "url": "https://www.llbean.com/llb/shop/3945",
    },
    {
        "category": "Fly-Line Accessories",
        "department": "Outdoor Equipment",
        "category_id": 4400,
        "url": "https://www.llbean.com/llb/shop/4400",
    },
    {
        "category": "Tools & Accessories",
        "department": "Outdoor Equipment",
        "category_id": 3948,
        "url": "https://www.llbean.com/llb/shop/3948",
    },
    {
        "category": "Outdoor Equipment / Clothing",
        "department": "Outdoor Equipment",
        "category_id": 507930,
        "url": "https://www.llbean.com/llb/shop/507930",
    },
    {
        "category": "Outdoor Equipment / Men's [507949]",
        "department": "Outdoor Equipment",
        "category_id": 507949,
        "url": "https://www.llbean.com/llb/shop/507949",
    },
    {
        "category": "Outdoor Equipment / Shirts [8172]",
        "department": "Outdoor Equipment",
        "category_id": 8172,
        "url": "https://www.llbean.com/llb/shop/8172",
    },
    {
        "category": "Outdoor Equipment / Pants & Shorts [500356]",
        "department": "Outdoor Equipment",
        "category_id": 500356,
        "url": "https://www.llbean.com/llb/shop/500356",
    },
    {
        "category": "Outdoor Equipment / Jackets & Vests [9963]",
        "department": "Outdoor Equipment",
        "category_id": 9963,
        "url": "https://www.llbean.com/llb/shop/9963",
    },
    {
        "category": "Outdoor Equipment / Accessories [500170]",
        "department": "Outdoor Equipment",
        "category_id": 500170,
        "url": "https://www.llbean.com/llb/shop/500170",
    },
    {
        "category": "Outdoor Equipment / Women's [507950]",
        "department": "Outdoor Equipment",
        "category_id": 507950,
        "url": "https://www.llbean.com/llb/shop/507950",
    },
    {
        "category": "Outdoor Equipment / Shirts [8171]",
        "department": "Outdoor Equipment",
        "category_id": 8171,
        "url": "https://www.llbean.com/llb/shop/8171",
    },
    {
        "category": "Outdoor Equipment / Pants & Shorts [500357]",
        "department": "Outdoor Equipment",
        "category_id": 500357,
        "url": "https://www.llbean.com/llb/shop/500357",
    },
    {
        "category": "Outdoor Equipment / Jackets & Vests [510558]",
        "department": "Outdoor Equipment",
        "category_id": 510558,
        "url": "https://www.llbean.com/llb/shop/510558",
    },
    {
        "category": "Outdoor Equipment / Accessories [508851]",
        "department": "Outdoor Equipment",
        "category_id": 508851,
        "url": "https://www.llbean.com/llb/shop/508851",
    },
    {
        "category": "Outdoor Equipment / Kids'",
        "department": "Outdoor Equipment",
        "category_id": 516647,
        "url": "https://www.llbean.com/llb/shop/516647",
    },
    {
        "category": "Beach Gear",
        "department": "Outdoor Equipment",
        "category_id": 518885,
        "url": "https://www.llbean.com/llb/shop/518885",
    },
    {
        "category": "Water Bottles & Drinkware",
        "department": "Outdoor Equipment",
        "category_id": 516664,
        "url": "https://www.llbean.com/llb/shop/516664",
    },
    {
        "category": "Drinkware & Thermoses",
        "department": "Outdoor Equipment",
        "category_id": 516675,
        "url": "https://www.llbean.com/llb/shop/516675",
    },
    {
        "category": "Water Bottles",
        "department": "Outdoor Equipment",
        "category_id": 506932,
        "url": "https://www.llbean.com/llb/shop/506932",
    },
    {
        "category": "Outdoor Equipment / Hunting",
        "department": "Outdoor Equipment",
        "category_id": 507929,
        "url": "https://www.llbean.com/llb/shop/507929",
    },
    {
        "category": "Packs, Bags & Vest Packs",
        "department": "Outdoor Equipment",
        "category_id": 508805,
        "url": "https://www.llbean.com/llb/shop/508805",
    },
    {
        "category": "Archery Gear",
        "department": "Outdoor Equipment",
        "category_id": 507001,
        "url": "https://www.llbean.com/llb/shop/507001",
    },
    {
        "category": "Shooting Sports & Gun Safety",
        "department": "Outdoor Equipment",
        "category_id": 516640,
        "url": "https://www.llbean.com/llb/shop/516640",
    },
    {
        "category": "Cases",
        "department": "Outdoor Equipment",
        "category_id": 3963,
        "url": "https://www.llbean.com/llb/shop/3963",
    },
    {
        "category": "Hunting Accessories",
        "department": "Outdoor Equipment",
        "category_id": 516646,
        "url": "https://www.llbean.com/llb/shop/516646",
    },
    {
        "category": "Clothing & Footwear",
        "department": "Outdoor Equipment",
        "category_id": 507932,
        "url": "https://www.llbean.com/llb/shop/507932",
    },
    {
        "category": "Outdoor Equipment / Men's [506557]",
        "department": "Outdoor Equipment",
        "category_id": 506557,
        "url": "https://www.llbean.com/llb/shop/506557",
    },
    {
        "category": "Outdoor Equipment / Shirts [506577]",
        "department": "Outdoor Equipment",
        "category_id": 506577,
        "url": "https://www.llbean.com/llb/shop/506577",
    },
    {
        "category": "Outdoor Equipment / Sweaters & Sweatshirts [506576]",
        "department": "Outdoor Equipment",
        "category_id": 506576,
        "url": "https://www.llbean.com/llb/shop/506576",
    },
    {
        "category": "Outdoor Equipment / Pants & Bibs [506578]",
        "department": "Outdoor Equipment",
        "category_id": 506578,
        "url": "https://www.llbean.com/llb/shop/506578",
    },
    {
        "category": "Outdoor Equipment / Outerwear & Vests [506569]",
        "department": "Outdoor Equipment",
        "category_id": 506569,
        "url": "https://www.llbean.com/llb/shop/506569",
    },
    {
        "category": "Outdoor Equipment / Underwear & Base Layers [506575]",
        "department": "Outdoor Equipment",
        "category_id": 506575,
        "url": "https://www.llbean.com/llb/shop/506575",
    },
    {
        "category": "Outdoor Equipment / Accessories [514347]",
        "department": "Outdoor Equipment",
        "category_id": 514347,
        "url": "https://www.llbean.com/llb/shop/514347",
    },
    {
        "category": "Outdoor Equipment / Women's [507965]",
        "department": "Outdoor Equipment",
        "category_id": 507965,
        "url": "https://www.llbean.com/llb/shop/507965",
    },
    {
        "category": "Outdoor Equipment / Sweaters & Sweatshirts [516637]",
        "department": "Outdoor Equipment",
        "category_id": 516637,
        "url": "https://www.llbean.com/llb/shop/516637",
    },
    {
        "category": "Outdoor Equipment / Pants & Bibs [508853]",
        "department": "Outdoor Equipment",
        "category_id": 508853,
        "url": "https://www.llbean.com/llb/shop/508853",
    },
    {
        "category": "Outdoor Equipment / Outerwear & Vests [508852]",
        "department": "Outdoor Equipment",
        "category_id": 508852,
        "url": "https://www.llbean.com/llb/shop/508852",
    },
    {
        "category": "Outdoor Equipment / Underwear & Base Layers [508856]",
        "department": "Outdoor Equipment",
        "category_id": 508856,
        "url": "https://www.llbean.com/llb/shop/508856",
    },
    {
        "category": "Outdoor Equipment / Accessories [516639]",
        "department": "Outdoor Equipment",
        "category_id": 516639,
        "url": "https://www.llbean.com/llb/shop/516639",
    },
    {
        "category": "Outdoor Equipment / Winter Sports",
        "department": "Outdoor Equipment",
        "category_id": 516714,
        "url": "https://www.llbean.com/llb/shop/516714",
    },
    {
        "category": "Snowshoeing",
        "department": "Outdoor Equipment",
        "category_id": 509573,
        "url": "https://www.llbean.com/llb/shop/509573",
    },
    {
        "category": "Snowshoes and Sets",
        "department": "Outdoor Equipment",
        "category_id": 509581,
        "url": "https://www.llbean.com/llb/shop/509581",
    },
    {
        "category": "Outdoor Equipment / Accessories [513506]",
        "department": "Outdoor Equipment",
        "category_id": 513506,
        "url": "https://www.llbean.com/llb/shop/513506",
    },
    {
        "category": "Sleds & Snow Toys",
        "department": "Outdoor Equipment",
        "category_id": 513503,
        "url": "https://www.llbean.com/llb/shop/513503",
    },
    {
        "category": "Sleds & Snow Tubes",
        "department": "Outdoor Equipment",
        "category_id": 513508,
        "url": "https://www.llbean.com/llb/shop/513508",
    },
    {
        "category": "Sled Accessories",
        "department": "Outdoor Equipment",
        "category_id": 513509,
        "url": "https://www.llbean.com/llb/shop/513509",
    },
    {
        "category": "Bags & Travel / Bags & Travel",
        "department": "Bags & Travel",
        "category_id": 50,
        "url": "https://www.llbean.com/llb/shop/50",
    },
    {
        "category": "Boat and Totes",
        "department": "Bags & Travel",
        "category_id": 514029,
        "url": "https://www.llbean.com/llb/shop/514029",
    },
    {
        "category": "Everyday Bags & Totes",
        "department": "Bags & Travel",
        "category_id": 516672,
        "url": "https://www.llbean.com/llb/shop/516672",
    },
    {
        "category": "Tote Bags",
        "department": "Bags & Travel",
        "category_id": 677,
        "url": "https://www.llbean.com/llb/shop/677",
    },
    {
        "category": "Everyday Backpacks",
        "department": "Bags & Travel",
        "category_id": 518805,
        "url": "https://www.llbean.com/llb/shop/518805",
    },
    {
        "category": "Crossbody Bags",
        "department": "Bags & Travel",
        "category_id": 847,
        "url": "https://www.llbean.com/llb/shop/847",
    },
    {
        "category": "School Backpacks & Lunch Boxes",
        "department": "Bags & Travel",
        "category_id": 816,
        "url": "https://www.llbean.com/llb/shop/816",
    },
    {
        "category": "School Backpacks",
        "department": "Bags & Travel",
        "category_id": 818,
        "url": "https://www.llbean.com/llb/shop/818",
    },
    {
        "category": "Bags & Travel / Lunch Boxes",
        "department": "Bags & Travel",
        "category_id": 514248,
        "url": "https://www.llbean.com/llb/shop/514248",
    },
    {
        "category": "Bags & Travel / Accessories",
        "department": "Bags & Travel",
        "category_id": 514250,
        "url": "https://www.llbean.com/llb/shop/514250",
    },
    {
        "category": "Bags & Travel / Luggage & Duffle Bags",
        "department": "Bags & Travel",
        "category_id": 516673,
        "url": "https://www.llbean.com/llb/shop/516673",
    },
    {
        "category": "Travel Backpacks",
        "department": "Bags & Travel",
        "category_id": 514260,
        "url": "https://www.llbean.com/llb/shop/514260",
    },
    {
        "category": "Luggage",
        "department": "Bags & Travel",
        "category_id": 903,
        "url": "https://www.llbean.com/llb/shop/903",
    },
    {
        "category": "Duffle Bags",
        "department": "Bags & Travel",
        "category_id": 904,
        "url": "https://www.llbean.com/llb/shop/904",
    },
    {
        "category": "Bags & Travel / Toiletry Bags & Organizers",
        "department": "Bags & Travel",
        "category_id": 507361,
        "url": "https://www.llbean.com/llb/shop/507361",
    },
    {
        "category": "Bag Charms & Accessories",
        "department": "Bags & Travel",
        "category_id": 203,
        "url": "https://www.llbean.com/llb/shop/203",
    },
    {
        "category": "Home Goods / Home Goods",
        "department": "Home Goods",
        "category_id": 31,
        "url": "https://www.llbean.com/llb/shop/31",
    },
    {
        "category": "Bedding",
        "department": "Home Goods",
        "category_id": 131,
        "url": "https://www.llbean.com/llb/shop/131",
    },
    {
        "category": "Sheets",
        "department": "Home Goods",
        "category_id": 1156,
        "url": "https://www.llbean.com/llb/shop/1156",
    },
    {
        "category": "Quilts & Bedspreads",
        "department": "Home Goods",
        "category_id": 504700,
        "url": "https://www.llbean.com/llb/shop/504700",
    },
    {
        "category": "Quilts",
        "department": "Home Goods",
        "category_id": 1159,
        "url": "https://www.llbean.com/llb/shop/1159",
    },
    {
        "category": "Bedspreads & Coverlets",
        "department": "Home Goods",
        "category_id": 4099,
        "url": "https://www.llbean.com/llb/shop/4099",
    },
    {
        "category": "Comforters & Covers",
        "department": "Home Goods",
        "category_id": 1158,
        "url": "https://www.llbean.com/llb/shop/1158",
    },
    {
        "category": "Comforters",
        "department": "Home Goods",
        "category_id": 4096,
        "url": "https://www.llbean.com/llb/shop/4096",
    },
    {
        "category": "Comforter Covers",
        "department": "Home Goods",
        "category_id": 4094,
        "url": "https://www.llbean.com/llb/shop/4094",
    },
    {
        "category": "Blankets & Throws",
        "department": "Home Goods",
        "category_id": 1157,
        "url": "https://www.llbean.com/llb/shop/1157",
    },
    {
        "category": "Mattress Pads",
        "department": "Home Goods",
        "category_id": 506595,
        "url": "https://www.llbean.com/llb/shop/506595",
    },
    {
        "category": "Bed Skirts",
        "department": "Home Goods",
        "category_id": 504698,
        "url": "https://www.llbean.com/llb/shop/504698",
    },
    {
        "category": "Pillows",
        "department": "Home Goods",
        "category_id": 1161,
        "url": "https://www.llbean.com/llb/shop/1161",
    },
    {
        "category": "Furniture",
        "department": "Home Goods",
        "category_id": 129,
        "url": "https://www.llbean.com/llb/shop/129",
    },
    {
        "category": "Outdoor Furniture",
        "department": "Home Goods",
        "category_id": 515463,
        "url": "https://www.llbean.com/llb/shop/515463",
    },
    {
        "category": "Patio Sofas & Sets",
        "department": "Home Goods",
        "category_id": 518298,
        "url": "https://www.llbean.com/llb/shop/518298",
    },
    {
        "category": "Patio Chairs",
        "department": "Home Goods",
        "category_id": 515464,
        "url": "https://www.llbean.com/llb/shop/515464",
    },
    {
        "category": "Outdoor Tables",
        "department": "Home Goods",
        "category_id": 508639,
        "url": "https://www.llbean.com/llb/shop/508639",
    },
    {
        "category": "Outdoor Cushions & Pillows",
        "department": "Home Goods",
        "category_id": 506688,
        "url": "https://www.llbean.com/llb/shop/506688",
    },
    {
        "category": "Umbrellas",
        "department": "Home Goods",
        "category_id": 507714,
        "url": "https://www.llbean.com/llb/shop/507714",
    },
    {
        "category": "Indoor Furniture",
        "department": "Home Goods",
        "category_id": 516261,
        "url": "https://www.llbean.com/llb/shop/516261",
    },
    {
        "category": "Sofas",
        "department": "Home Goods",
        "category_id": 506638,
        "url": "https://www.llbean.com/llb/shop/506638",
    },
    {
        "category": "Chairs & Ottomans",
        "department": "Home Goods",
        "category_id": 8831,
        "url": "https://www.llbean.com/llb/shop/8831",
    },
    {
        "category": "Storage",
        "department": "Home Goods",
        "category_id": 506632,
        "url": "https://www.llbean.com/llb/shop/506632",
    },
    {
        "category": "Beds",
        "department": "Home Goods",
        "category_id": 1146,
        "url": "https://www.llbean.com/llb/shop/1146",
    },
    {
        "category": "Bath",
        "department": "Home Goods",
        "category_id": 900,
        "url": "https://www.llbean.com/llb/shop/900",
    },
    {
        "category": "Bath & Beach Towels",
        "department": "Home Goods",
        "category_id": 514487,
        "url": "https://www.llbean.com/llb/shop/514487",
    },
    {
        "category": "Bath Mats",
        "department": "Home Goods",
        "category_id": 506598,
        "url": "https://www.llbean.com/llb/shop/506598",
    },
    {
        "category": "Fireplace & Hearth",
        "department": "Home Goods",
        "category_id": 510044,
        "url": "https://www.llbean.com/llb/shop/510044",
    },
    {
        "category": "Rugs & Mats",
        "department": "Home Goods",
        "category_id": 514001,
        "url": "https://www.llbean.com/llb/shop/514001",
    },
    {
        "category": "Indoor",
        "department": "Home Goods",
        "category_id": 506691,
        "url": "https://www.llbean.com/llb/shop/506691",
    },
    {
        "category": "Indoor-Outdoor",
        "department": "Home Goods",
        "category_id": 506690,
        "url": "https://www.llbean.com/llb/shop/506690",
    },
    {
        "category": "Waterhog Mats",
        "department": "Home Goods",
        "category_id": 506645,
        "url": "https://www.llbean.com/llb/shop/506645",
    },
    {
        "category": "Home Decor",
        "department": "Home Goods",
        "category_id": 312,
        "url": "https://www.llbean.com/llb/shop/312",
    },
    {
        "category": "Baskets & Totes",
        "department": "Home Goods",
        "category_id": 7434,
        "url": "https://www.llbean.com/llb/shop/7434",
    },
    {
        "category": "Home Accessories",
        "department": "Home Goods",
        "category_id": 516853,
        "url": "https://www.llbean.com/llb/shop/516853",
    },
    {
        "category": "Holiday",
        "department": "Home Goods",
        "category_id": 509902,
        "url": "https://www.llbean.com/llb/shop/509902",
    },
    {
        "category": "Stockings",
        "department": "Home Goods",
        "category_id": 513739,
        "url": "https://www.llbean.com/llb/shop/513739",
    },
    {
        "category": "Decorations",
        "department": "Home Goods",
        "category_id": 509903,
        "url": "https://www.llbean.com/llb/shop/509903",
    },
    {
        "category": "Throw Pillows",
        "department": "Home Goods",
        "category_id": 506607,
        "url": "https://www.llbean.com/llb/shop/506607",
    },
    {
        "category": "Wreaths & Greenery",
        "department": "Home Goods",
        "category_id": 509909,
        "url": "https://www.llbean.com/llb/shop/509909",
    },
    {
        "category": "Backyard & Patio",
        "department": "Home Goods",
        "category_id": 132,
        "url": "https://www.llbean.com/llb/shop/132",
    },
    {
        "category": "Grills & Fire Pits",
        "department": "Home Goods",
        "category_id": 506840,
        "url": "https://www.llbean.com/llb/shop/506840",
    },
    {
        "category": "Home Goods / Hammocks",
        "department": "Home Goods",
        "category_id": 508647,
        "url": "https://www.llbean.com/llb/shop/508647",
    },
    {
        "category": "Games & Outdoor Toys",
        "department": "Home Goods",
        "category_id": 515482,
        "url": "https://www.llbean.com/llb/shop/515482",
    },
    {
        "category": "Games & Books",
        "department": "Home Goods",
        "category_id": 506621,
        "url": "https://www.llbean.com/llb/shop/506621",
    },
    {
        "category": "Books",
        "department": "Home Goods",
        "category_id": 510164,
        "url": "https://www.llbean.com/llb/shop/510164",
    },
    {
        "category": "Dog Supplies",
        "department": "Home Goods",
        "category_id": 134,
        "url": "https://www.llbean.com/llb/shop/134",
    },
    {
        "category": "Beds & Blankets",
        "department": "Home Goods",
        "category_id": 507408,
        "url": "https://www.llbean.com/llb/shop/507408",
    },
    {
        "category": "Collars, Leads & Leashes",
        "department": "Home Goods",
        "category_id": 507065,
        "url": "https://www.llbean.com/llb/shop/507065",
    },
    {
        "category": "Bowls &  Mats",
        "department": "Home Goods",
        "category_id": 507031,
        "url": "https://www.llbean.com/llb/shop/507031",
    },
    {
        "category": "Kennels",
        "department": "Home Goods",
        "category_id": 507067,
        "url": "https://www.llbean.com/llb/shop/507067",
    },
    {
        "category": "Home Goods / Jackets & Vests",
        "department": "Home Goods",
        "category_id": 507029,
        "url": "https://www.llbean.com/llb/shop/507029",
    },
    {
        "category": "Dog Toys & Accessories",
        "department": "Home Goods",
        "category_id": 507025,
        "url": "https://www.llbean.com/llb/shop/507025",
    },
    {
        "category": "Dog Training",
        "department": "Home Goods",
        "category_id": 507026,
        "url": "https://www.llbean.com/llb/shop/507026",
    },
    {
        "category": "Electronics",
        "department": "Home Goods",
        "category_id": 516641,
        "url": "https://www.llbean.com/llb/shop/516641",
    },
    {
        "category": "Home Goods / Accessories",
        "department": "Home Goods",
        "category_id": 516644,
        "url": "https://www.llbean.com/llb/shop/516644",
    },
    {
        "category": "Gourmet Treats",
        "department": "Home Goods",
        "category_id": 514907,
        "url": "https://www.llbean.com/llb/shop/514907",
    },
    {
        "category": "Sale",
        "department": "Sale",
        "category_id": 32,
        "url": "https://www.llbean.com/llb/shop/32",
    },
    {
        "category": "Sale / Clothing [516686]",
        "department": "Sale",
        "category_id": 516686,
        "url": "https://www.llbean.com/llb/shop/516686",
    },
    {
        "category": "Sale / Men's [298]",
        "department": "Sale",
        "category_id": 298,
        "url": "https://www.llbean.com/llb/shop/298",
    },
    {
        "category": "Sale / T-Shirts & Polos",
        "department": "Sale",
        "category_id": 20010167,
        "url": "https://www.llbean.com/llb/shop/20010167",
    },
    {
        "category": "Sale / Shirts",
        "department": "Sale",
        "category_id": 507223,
        "url": "https://www.llbean.com/llb/shop/507223",
    },
    {
        "category": "Sale / Sweatshirts [507224]",
        "department": "Sale",
        "category_id": 507224,
        "url": "https://www.llbean.com/llb/shop/507224",
    },
    {
        "category": "Sale / Fleece [518873]",
        "department": "Sale",
        "category_id": 518873,
        "url": "https://www.llbean.com/llb/shop/518873",
    },
    {
        "category": "Sale / Sweaters [518081]",
        "department": "Sale",
        "category_id": 518081,
        "url": "https://www.llbean.com/llb/shop/518081",
    },
    {
        "category": "Sale / Pants & Jeans [516419]",
        "department": "Sale",
        "category_id": 516419,
        "url": "https://www.llbean.com/llb/shop/516419",
    },
    {
        "category": "Sale / Shorts",
        "department": "Sale",
        "category_id": 6719,
        "url": "https://www.llbean.com/llb/shop/6719",
    },
    {
        "category": "Sale / Swimwear [516420]",
        "department": "Sale",
        "category_id": 516420,
        "url": "https://www.llbean.com/llb/shop/516420",
    },
    {
        "category": "Sale / Sleepwear [516421]",
        "department": "Sale",
        "category_id": 516421,
        "url": "https://www.llbean.com/llb/shop/516421",
    },
    {
        "category": "Sale / Base Layers [502575]",
        "department": "Sale",
        "category_id": 502575,
        "url": "https://www.llbean.com/llb/shop/502575",
    },
    {
        "category": "Sale / Accessories [502577]",
        "department": "Sale",
        "category_id": 502577,
        "url": "https://www.llbean.com/llb/shop/502577",
    },
    {
        "category": "Sale / Activewear [503991]",
        "department": "Sale",
        "category_id": 503991,
        "url": "https://www.llbean.com/llb/shop/503991",
    },
    {
        "category": "Sale / Women's [302]",
        "department": "Sale",
        "category_id": 302,
        "url": "https://www.llbean.com/llb/shop/302",
    },
    {
        "category": "Sale / Tees & Tanks",
        "department": "Sale",
        "category_id": 20010165,
        "url": "https://www.llbean.com/llb/shop/20010165",
    },
    {
        "category": "Sale / Shirts & Tops",
        "department": "Sale",
        "category_id": 6705,
        "url": "https://www.llbean.com/llb/shop/6705",
    },
    {
        "category": "Sale / Sweatshirts [8979]",
        "department": "Sale",
        "category_id": 8979,
        "url": "https://www.llbean.com/llb/shop/8979",
    },
    {
        "category": "Sale / Fleece [518874]",
        "department": "Sale",
        "category_id": 518874,
        "url": "https://www.llbean.com/llb/shop/518874",
    },
    {
        "category": "Sale / Sweaters [518078]",
        "department": "Sale",
        "category_id": 518078,
        "url": "https://www.llbean.com/llb/shop/518078",
    },
    {
        "category": "Sale / Shorts & Skorts",
        "department": "Sale",
        "category_id": 502180,
        "url": "https://www.llbean.com/llb/shop/502180",
    },
    {
        "category": "Sale / Pants & Jeans [6709]",
        "department": "Sale",
        "category_id": 6709,
        "url": "https://www.llbean.com/llb/shop/6709",
    },
    {
        "category": "Sale / Dresses & Skirts",
        "department": "Sale",
        "category_id": 502066,
        "url": "https://www.llbean.com/llb/shop/502066",
    },
    {
        "category": "Sale / Swimwear [8356]",
        "department": "Sale",
        "category_id": 8356,
        "url": "https://www.llbean.com/llb/shop/8356",
    },
    {
        "category": "Sale / Base Layers [516425]",
        "department": "Sale",
        "category_id": 516425,
        "url": "https://www.llbean.com/llb/shop/516425",
    },
    {
        "category": "Sale / Sleepwear [502177]",
        "department": "Sale",
        "category_id": 502177,
        "url": "https://www.llbean.com/llb/shop/502177",
    },
    {
        "category": "Sale / Accessories [506209]",
        "department": "Sale",
        "category_id": 506209,
        "url": "https://www.llbean.com/llb/shop/506209",
    },
    {
        "category": "Sale / Activewear [8049]",
        "department": "Sale",
        "category_id": 8049,
        "url": "https://www.llbean.com/llb/shop/8049",
    },
    {
        "category": "Sale / Kids' [503676]",
        "department": "Sale",
        "category_id": 503676,
        "url": "https://www.llbean.com/llb/shop/503676",
    },
    {
        "category": "Sale / Tops",
        "department": "Sale",
        "category_id": 503753,
        "url": "https://www.llbean.com/llb/shop/503753",
    },
    {
        "category": "Sale / Bottoms",
        "department": "Sale",
        "category_id": 503754,
        "url": "https://www.llbean.com/llb/shop/503754",
    },
    {
        "category": "Sale / Sleepwear [507478]",
        "department": "Sale",
        "category_id": 507478,
        "url": "https://www.llbean.com/llb/shop/507478",
    },
    {
        "category": "Long Underwear",
        "department": "Sale",
        "category_id": 513014,
        "url": "https://www.llbean.com/llb/shop/513014",
    },
    {
        "category": "Kids' Accessories on Sale",
        "department": "Sale",
        "category_id": 510023,
        "url": "https://www.llbean.com/llb/shop/510023",
    },
    {
        "category": "Sale / Toddler & Baby",
        "department": "Sale",
        "category_id": 6731,
        "url": "https://www.llbean.com/llb/shop/6731",
    },
    {
        "category": "Sale / Outerwear [518521]",
        "department": "Sale",
        "category_id": 518521,
        "url": "https://www.llbean.com/llb/shop/518521",
    },
    {
        "category": "Sale / Men's [6723]",
        "department": "Sale",
        "category_id": 6723,
        "url": "https://www.llbean.com/llb/shop/6723",
    },
    {
        "category": "Sale / Women's [6703]",
        "department": "Sale",
        "category_id": 6703,
        "url": "https://www.llbean.com/llb/shop/6703",
    },
    {
        "category": "Sale / Kids' [503677]",
        "department": "Sale",
        "category_id": 503677,
        "url": "https://www.llbean.com/llb/shop/503677",
    },
    {
        "category": "Sale / Footwear [516689]",
        "department": "Sale",
        "category_id": 516689,
        "url": "https://www.llbean.com/llb/shop/516689",
    },
    {
        "category": "Sale / Men's [7955]",
        "department": "Sale",
        "category_id": 7955,
        "url": "https://www.llbean.com/llb/shop/7955",
    },
    {
        "category": "Sale / Boots [516691]",
        "department": "Sale",
        "category_id": 516691,
        "url": "https://www.llbean.com/llb/shop/516691",
    },
    {
        "category": "Sale / Sneakers & Shoes [516690]",
        "department": "Sale",
        "category_id": 516690,
        "url": "https://www.llbean.com/llb/shop/516690",
    },
    {
        "category": "Sale / Sandals & Water Shoes [516693]",
        "department": "Sale",
        "category_id": 516693,
        "url": "https://www.llbean.com/llb/shop/516693",
    },
    {
        "category": "Sale / Slippers [516692]",
        "department": "Sale",
        "category_id": 516692,
        "url": "https://www.llbean.com/llb/shop/516692",
    },
    {
        "category": "Sale / Socks [516694]",
        "department": "Sale",
        "category_id": 516694,
        "url": "https://www.llbean.com/llb/shop/516694",
    },
    {
        "category": "Sale / Accessories [516695]",
        "department": "Sale",
        "category_id": 516695,
        "url": "https://www.llbean.com/llb/shop/516695",
    },
    {
        "category": "Sale / Women's [6715]",
        "department": "Sale",
        "category_id": 6715,
        "url": "https://www.llbean.com/llb/shop/6715",
    },
    {
        "category": "Sale / Boots [502269]",
        "department": "Sale",
        "category_id": 502269,
        "url": "https://www.llbean.com/llb/shop/502269",
    },
    {
        "category": "Sale / Sneakers & Shoes [502050]",
        "department": "Sale",
        "category_id": 502050,
        "url": "https://www.llbean.com/llb/shop/502050",
    },
    {
        "category": "Sale / Sandals & Water Shoes [502267]",
        "department": "Sale",
        "category_id": 502267,
        "url": "https://www.llbean.com/llb/shop/502267",
    },
    {
        "category": "Sale / Slippers [502266]",
        "department": "Sale",
        "category_id": 502266,
        "url": "https://www.llbean.com/llb/shop/502266",
    },
    {
        "category": "Sale / Socks [516696]",
        "department": "Sale",
        "category_id": 516696,
        "url": "https://www.llbean.com/llb/shop/516696",
    },
    {
        "category": "Sale / Accessories [516697]",
        "department": "Sale",
        "category_id": 516697,
        "url": "https://www.llbean.com/llb/shop/516697",
    },
    {
        "category": "Sale / Kids' [503755]",
        "department": "Sale",
        "category_id": 503755,
        "url": "https://www.llbean.com/llb/shop/503755",
    },
    {
        "category": "Sale / Outdoor Equipment [509104]",
        "department": "Sale",
        "category_id": 509104,
        "url": "https://www.llbean.com/llb/shop/509104",
    },
    {
        "category": "Sale / Camping & Hiking",
        "department": "Sale",
        "category_id": 511644,
        "url": "https://www.llbean.com/llb/shop/511644",
    },
    {
        "category": "Sale / Hunting",
        "department": "Sale",
        "category_id": 9200,
        "url": "https://www.llbean.com/llb/shop/9200",
    },
    {
        "category": "Sale / Fishing",
        "department": "Sale",
        "category_id": 502035,
        "url": "https://www.llbean.com/llb/shop/502035",
    },
    {
        "category": "Paddling",
        "department": "Sale",
        "category_id": 510692,
        "url": "https://www.llbean.com/llb/shop/510692",
    },
    {
        "category": "Cycling",
        "department": "Sale",
        "category_id": 508295,
        "url": "https://www.llbean.com/llb/shop/508295",
    },
    {
        "category": "Sale / Winter Sports",
        "department": "Sale",
        "category_id": 508294,
        "url": "https://www.llbean.com/llb/shop/508294",
    },
    {
        "category": "Games & Recreation",
        "department": "Sale",
        "category_id": 516422,
        "url": "https://www.llbean.com/llb/shop/516422",
    },
    {
        "category": "Car Racks & Cargo Boxes on Sale",
        "department": "Sale",
        "category_id": 510830,
        "url": "https://www.llbean.com/llb/shop/510830",
    },
    {
        "category": "Sale / Outdoor Accessories",
        "department": "Sale",
        "category_id": 516423,
        "url": "https://www.llbean.com/llb/shop/516423",
    },
    {
        "category": "Sale / Bags & Travel [305]",
        "department": "Sale",
        "category_id": 305,
        "url": "https://www.llbean.com/llb/shop/305",
    },
    {
        "category": "Sale / Backpacks",
        "department": "Sale",
        "category_id": 511658,
        "url": "https://www.llbean.com/llb/shop/511658",
    },
    {
        "category": "Sale / Lunch Boxes",
        "department": "Sale",
        "category_id": 513285,
        "url": "https://www.llbean.com/llb/shop/513285",
    },
    {
        "category": "Bags & Totes",
        "department": "Sale",
        "category_id": 8917,
        "url": "https://www.llbean.com/llb/shop/8917",
    },
    {
        "category": "Sale / Luggage & Duffle Bags",
        "department": "Sale",
        "category_id": 8918,
        "url": "https://www.llbean.com/llb/shop/8918",
    },
    {
        "category": "Travel Accessories",
        "department": "Sale",
        "category_id": 516700,
        "url": "https://www.llbean.com/llb/shop/516700",
    },
    {
        "category": "Sale / Toiletry Bags & Organizers",
        "department": "Sale",
        "category_id": 516699,
        "url": "https://www.llbean.com/llb/shop/516699",
    },
    {
        "category": "Sale / Home Goods [307]",
        "department": "Sale",
        "category_id": 307,
        "url": "https://www.llbean.com/llb/shop/307",
    },
    {
        "category": "New to Sale",
        "department": "Sale",
        "category_id": 508925,
        "url": "https://www.llbean.com/llb/shop/508925",
    },
    {
        "category": "Sale / Clothing [516680]",
        "department": "Sale",
        "category_id": 516680,
        "url": "https://www.llbean.com/llb/shop/516680",
    },
    {
        "category": "Sale / Men's [508928]",
        "department": "Sale",
        "category_id": 508928,
        "url": "https://www.llbean.com/llb/shop/508928",
    },
    {
        "category": "Sale / Women's [508929]",
        "department": "Sale",
        "category_id": 508929,
        "url": "https://www.llbean.com/llb/shop/508929",
    },
    {
        "category": "Sale / Kids' [508930]",
        "department": "Sale",
        "category_id": 508930,
        "url": "https://www.llbean.com/llb/shop/508930",
    },
    {
        "category": "Sale / Outerwear [518702]",
        "department": "Sale",
        "category_id": 518702,
        "url": "https://www.llbean.com/llb/shop/518702",
    },
    {
        "category": "Sale / Footwear [516682]",
        "department": "Sale",
        "category_id": 516682,
        "url": "https://www.llbean.com/llb/shop/516682",
    },
    {
        "category": "Sale / Outdoor Equipment [509138]",
        "department": "Sale",
        "category_id": 509138,
        "url": "https://www.llbean.com/llb/shop/509138",
    },
    {
        "category": "Sale / Bags & Travel [508933]",
        "department": "Sale",
        "category_id": 508933,
        "url": "https://www.llbean.com/llb/shop/508933",
    },
    {
        "category": "Sale / Home Goods [508932]",
        "department": "Sale",
        "category_id": 508932,
        "url": "https://www.llbean.com/llb/shop/508932",
    },
    {
        "category": "Two-A-Day Daily Markdown",
        "department": "Sale",
        "category_id": 504987,
        "url": "https://www.llbean.com/llb/shop/504987",
    },
    {
        "category": "Sale / Clothing and Home Goods [556]",
        "department": "Sale",
        "category_id": 556,
        "url": "https://www.llbean.com/llb/shop/556",
    },
    {
        "category": "Sale / Clothing and Home Goods [577]",
        "department": "Sale",
        "category_id": 577,
        "url": "https://www.llbean.com/llb/shop/577",
    },
    {
        "category": "Sale / Daily Markdown [510312]",
        "department": "Sale",
        "category_id": 510312,
        "url": "https://www.llbean.com/llb/shop/510312",
    },
    {
        "category": "Sale / Daily Markdown [510310]",
        "department": "Sale",
        "category_id": 510310,
        "url": "https://www.llbean.com/llb/shop/510310",
    },
    {
        "category": "Sale / Daily Markdown [510311]",
        "department": "Sale",
        "category_id": 510311,
        "url": "https://www.llbean.com/llb/shop/510311",
    },
    {
        "category": "Outdoor Experiences",
        "department": "Outdoor Experiences",
        "category_id": 518571,
        "url": "https://www.llbean.com/llb/shop/518571",
    },
    {
        "category": "Outdoor Discovery Programs",
        "department": "Outdoor Experiences",
        "category_id": 518707,
        "url": "https://www.llbean.com/llb/shop/518707",
    },
    {
        "category": "Events & Activities",
        "department": "Outdoor Experiences",
        "category_id": 518363,
        "url": "https://www.llbean.com/llb/shop/518363",
    },
    {
        "category": "Flagship Grand Opening",
        "department": "Outdoor Experiences",
        "category_id": 20011038,
        "url": "https://www.llbean.com/llb/shop/20011038",
    },
    {
        "category": "Northern Lights",
        "department": "Outdoor Experiences",
        "category_id": 512152,
        "url": "https://www.llbean.com/llb/shop/512152",
    },
    {
        "category": "Winter in New England",
        "department": "Outdoor Experiences",
        "category_id": 513045,
        "url": "https://www.llbean.com/llb/shop/513045",
    },
    {
        "category": "Summer in the Park",
        "department": "Outdoor Experiences",
        "category_id": 518418,
        "url": "https://www.llbean.com/llb/shop/518418",
    },
    {
        "category": "Beach Boxes",
        "department": "Outdoor Experiences",
        "category_id": 518451,
        "url": "https://www.llbean.com/llb/shop/518451",
    },
    {
        "category": "Be An Outsider at Work",
        "department": "Outdoor Experiences",
        "category_id": 517153,
        "url": "https://www.llbean.com/llb/shop/517153",
    },
    {
        "category": "Bootmobile",
        "department": "Outdoor Experiences",
        "category_id": 518708,
        "url": "https://www.llbean.com/llb/shop/518708",
    },
    {
        "category": "Meet the Fleet",
        "department": "Outdoor Experiences",
        "category_id": 20010251,
        "url": "https://www.llbean.com/llb/shop/20010251",
    },
    {
        "category": "Bootlegger Bios",
        "department": "Outdoor Experiences",
        "category_id": 20010252,
        "url": "https://www.llbean.com/llb/shop/20010252",
    },
    {
        "category": "Bootmobile History",
        "department": "Outdoor Experiences",
        "category_id": 20010253,
        "url": "https://www.llbean.com/llb/shop/20010253",
    },
    {
        "category": "Explore L.L.Bean",
        "department": "Explore L.L.Bean",
        "category_id": 518342,
        "url": "https://www.llbean.com/llb/shop/518342",
    },
]
