MENARDS_CATEGORIES = {
    "halloween-animated-decorations": "https://www.menards.com/main/holiday-decorations/halloween/halloween-animated-decorations/c-19081.htm",
    "appliances": "https://www.menards.com/main/appliances/c-5570.htm",
    "automotive": "https://www.menards.com/main/tools/automotive/c-9097.htm",
    "bath": "https://www.menards.com/main/bath/c-5867.htm",
    "building-materials": "https://www.menards.com/main/building-materials/c-5640.htm",
    "clothing": "https://www.menards.com/main/clothing/c-7079.htm",
    "doors-windows-millwork": "https://www.menards.com/main/doors-windows-millwork/c-7550.htm",
    "electrical": "https://www.menards.com/main/electrical/c-6290.htm",
    "flooring-rugs": "https://www.menards.com/main/flooring-rugs/c-6512.htm",
    "furniture-home": "https://www.menards.com/main/grocery-home/c-19741.htm",
    "grocery": "https://www.menards.com/main/grocery-home/grocery/c-1552918768160.htm",
    "hardware": "https://www.menards.com/main/hardware/c-8693.htm",
    "heating-cooling": "https://www.menards.com/main/heating-cooling/c-6796.htm",
    "holiday-decorations": "https://www.menards.com/main/holiday-decorations/c-1548786202463.htm",
    "kitchen": "https://www.menards.com/main/kitchen/c-7200.htm",
    "lawn-garden": "https://www.menards.com/main/lawn-garden/c-4324230408371061.htm",
    "lighting-ceiling-fans": "https://www.menards.com/main/lighting-ceiling-fans/c-7476.htm",
    "outdoor-living-patio": "https://www.menards.com/main/outdoor%20living%20%26%20patio/c-7727.htm",
    "paint": "https://www.menards.com/main/paint/c-7918.htm",
    "pet-wildlife": "https://www.menards.com/main/pet-wildlife/c-19743.htm",
}
