from __future__ import annotations

"""Nike US category inventory.

Extracted from the Nike.com desktop global navigation (issue #134). The
hierarchy is preserved as ``department -> group -> subcategory -> url``.

Six URLs are reachable from two departments (for example
``/w/sunglasses-arlyp`` is linked from both Men and Women accessories, and
``/w/nikeskims-b2asd`` from both Women and NikeSKIMS). The spider
deduplicates by URL and keeps the first department in the inventory order below.
"""

NIKE_CATEGORIES: dict[str, dict[str, dict[str, str]]] = {
    "Men": {
        "New & Featured": {
            "New & Featured": "https://www.nike.com/w/new-mens-3n82yznik1",
            "New Arrivals": "https://www.nike.com/w/new-mens-3n82yznik1",
            "Best Sellers": "https://www.nike.com/w/mens-best-76m50znik1",
            "Latest Drops": "https://www.nike.com/w/new-upcoming-drops-k0gk",
            "Nike Sportswear": "https://www.nike.com/w/mens-lifestyle-13jrmznik1",
            "Shop All Sale": "https://www.nike.com/w/mens-sale-3yaepznik1",
        },
        "Shoes": {
            "Shoes": "https://www.nike.com/w/mens-shoes-nik1zy7ok",
            "All Shoes": "https://www.nike.com/w/mens-shoes-nik1zy7ok",
            "Basketball": "https://www.nike.com/w/mens-basketball-shoes-3glsmznik1zy7ok",
            "Jordan": "https://www.nike.com/w/mens-jordan-shoes-37eefznik1zy7ok",
            "Running": "https://www.nike.com/w/mens-running-shoes-37v7jznik1zy7ok",
            "Sandals & Slides": "https://www.nike.com/w/mens-sandals-slides-fl76znik1",
            "Sportswear": "https://www.nike.com/w/mens-lifestyle-shoes-13jrmznik1zy7ok",
            "Training & Gym": "https://www.nike.com/w/mens-training-gym-shoes-58jtoznik1zy7ok",
            "Custom Shoes": "https://www.nike.com/w/mens-nike-by-you-shoes-6ealhznik1zy7ok",
        },
        "Clothing": {
            "Clothing": "https://www.nike.com/w/mens-clothing-6ymx6znik1",
            "All Clothing": "https://www.nike.com/w/mens-clothing-6ymx6znik1",
            "Fleece": "https://www.nike.com/w/mens-fleece-4xh6qznik1",
            "Hoodies & Sweatshirts": "https://www.nike.com/w/mens-hoodies-and-pullovers-6riveznik1",
            "Jackets & Vests": "https://www.nike.com/w/mens-jackets-vests-50r7yznik1",
            "Pants": "https://www.nike.com/w/mens-pants-and-tights-2kq19znik1",
            "Shorts": "https://www.nike.com/w/mens-shorts-38fphznik1",
            "Swim": "https://www.nike.com/w/mens-surf-swimming-3c2djznik1",
            "Tops & Graphic Tees": "https://www.nike.com/w/mens-tops-t-shirts-9om13znik1",
        },
        "Accessories": {
            "Accessories": "https://www.nike.com/w/mens-accessories-equipment-awwpwznik1",
            "All Accessories": "https://www.nike.com/w/mens-accessories-equipment-awwpwznik1",
            "Bags & Backpacks": "https://www.nike.com/w/mens-bags-and-backpacks-9xy71znik1",
            "Hats & Headwear": "https://www.nike.com/w/mens-hats-visors-and-headbands-52r49znik1",
            "Socks": "https://www.nike.com/w/mens-socks-7ny3qznik1",
            "Sunglasses": "https://www.nike.com/w/sunglasses-arlyp",
        },
    },
    "Women": {
        "New & Featured": {
            "New & Featured": "https://www.nike.com/w/new-womens-3n82yz5e1x6",
            "New Arrivals": "https://www.nike.com/w/new-womens-3n82yz5e1x6",
            "Best Sellers": "https://www.nike.com/w/womens-best-5e1x6z76m50",
            "Nike Sportswear": "https://www.nike.com/w/womens-lifestyle-13jrmz5e1x6",
            "NikeSKIMS": "https://www.nike.com/w/nikeskims-b2asd",
            "Shop All Sale": "https://www.nike.com/w/womens-sale-3yaepz5e1x6",
        },
        "Shop by Color": {
            "Shop by Color": "https://www.nike.com/w/womens-matching-sets-clothing-2lukpz5e1x6z6ymx6",
            "Dark Neutrals": "https://www.nike.com/w/womens-color-shop-brown-4elb3z5e1x6",
            "Illusion Green": "https://www.nike.com/w/womens-color-shop-green-5e1x6z9cm3q",
            "Midnight Blue": "https://www.nike.com/w/womens-color-shop-blues-5e1x6z7wk8r",
            "Pink Rise": "https://www.nike.com/w/womens-color-shop-fierce-pinks-4x3uaz5e1x6",
            "Warm Neutrals": "https://www.nike.com/w/womens-color-shop-new-neutrals-5e1x6z98ed2",
        },
        "Shoes": {
            "Shoes": "https://www.nike.com/w/womens-shoes-5e1x6zy7ok",
            "All Shoes": "https://www.nike.com/w/womens-shoes-5e1x6zy7ok",
            "Basketball": "https://www.nike.com/w/womens-basketball-shoes-3glsmz5e1x6zy7ok",
            "Jordan": "https://www.nike.com/w/womens-jordan-shoes-37eefz5e1x6zy7ok",
            "Running": "https://www.nike.com/w/womens-running-shoes-37v7jz5e1x6zy7ok",
            "Sandals & Slides": "https://www.nike.com/w/womens-sandals-slides-5e1x6zfl76",
            "Sportswear": "https://www.nike.com/w/womens-lifestyle-shoes-13jrmz5e1x6zy7ok",
            "Training & Gym": "https://www.nike.com/w/womens-training-gym-shoes-58jtoz5e1x6zy7ok",
            "Custom Shoes": "https://www.nike.com/w/womens-nike-by-you-shoes-5e1x6z6ealhzy7ok",
        },
        "Clothing": {
            "Clothing": "https://www.nike.com/w/womens-clothing-5e1x6z6ymx6",
            "All Clothing": "https://www.nike.com/w/womens-clothing-5e1x6z6ymx6",
            "Bras": "https://www.nike.com/w/womens-sports-bras-40qgmz5e1x6",
            "Fleece": "https://www.nike.com/w/womens-fleece-4xh6qz5e1x6",
            "Hoodies & Sweatshirts": "https://www.nike.com/w/womens-hoodies-and-pullovers-5e1x6z6rive",
            "Jackets & Vests": "https://www.nike.com/w/womens-jackets-vests-50r7yz5e1x6",
            "Leggings": "https://www.nike.com/w/womens-tights-leggings-29sh2z5e1x6",
            "Matching Sets": "https://www.nike.com/w/womens-matching-sets-clothing-2lukpz5e1x6z6ymx6",
            "Pants": "https://www.nike.com/w/womens-pants-and-tights-2kq19z5e1x6",
            "Shorts": "https://www.nike.com/w/womens-shorts-38fphz5e1x6",
            "Skirts & Dresses": "https://www.nike.com/w/womens-skirts-and-dresses-5e1x6z8y3qp",
            "Swim": "https://www.nike.com/w/womens-surf-swimming-3c2djz5e1x6",
            "Tops & Graphics Tees": "https://www.nike.com/w/womens-tops-t-shirts-5e1x6z9om13",
        },
        "Accessories": {
            "Accessories": "https://www.nike.com/w/womens-accessories-equipment-5e1x6zawwpw",
            "All Accessories": "https://www.nike.com/w/womens-accessories-equipment-5e1x6zawwpw",
            "Bags & Backpacks": "https://www.nike.com/w/womens-bags-and-backpacks-5e1x6z9xy71",
            "Hats & Headwear": "https://www.nike.com/w/womens-hats-visors-and-headbands-52r49z5e1x6",
            "Socks": "https://www.nike.com/w/womens-socks-5e1x6z7ny3q",
            "Sunglasses": "https://www.nike.com/w/sunglasses-arlyp",
        },
    },
    "Kids": {
        "New & Featured": {
            "New & Featured": "https://www.nike.com/w/new-kids-3n82yzv4dh",
            "New Arrivals": "https://www.nike.com/w/new-kids-3n82yzv4dh",
            "Best Sellers": "https://www.nike.com/w/kids-best-76m50zv4dh",
            "Nike Sportswear": "https://www.nike.com/w/kids-lifestyle-13jrmzv4dh",
            "Nike x LEGO®": "https://www.nike.com/w/nike-lego-collection-58jr",
            "Shop All Sale": "https://www.nike.com/w/kids-sale-3yaepzv4dh",
        },
        "Shoes": {
            "Shoes": "https://www.nike.com/w/kids-shoes-v4dhzy7ok",
            "All Shoes": "https://www.nike.com/w/kids-shoes-v4dhzy7ok",
            "Teens (13-15 yrs)": "https://www.nike.com/w/teen-collection-shoes-6hguezy7ok",
            "Big Kids (7-12 yrs)": "https://www.nike.com/w/big-kids-shoes-agibjzv4dhzy7ok",
            "Little Kids (3-7 yrs)": "https://www.nike.com/w/little-kids-shoes-6dacezv4dhzy7ok",
            "Baby & Toddler (0-3 yrs)": "https://www.nike.com/w/baby-toddler-kids-shoes-2j488zv4dhzy7ok",
        },
        "Clothing": {
            "Clothing": "https://www.nike.com/w/kids-clothing-6ymx6zv4dh",
            "All Clothing": "https://www.nike.com/w/kids-clothing-6ymx6zv4dh",
            "Teens (13-15 yrs)": "https://www.nike.com/w/teen-collection-clothing-6hguez6ymx6",
            "Big Kids (7-12 yrs)": "https://www.nike.com/w/big-kids-clothing-6ymx6zagibjzv4dh",
            "Little Kids (3-7 yrs)": "https://www.nike.com/w/little-kids-clothing-6dacez6ymx6zv4dh",
            "Baby & Toddler (0-3 yrs)": "https://www.nike.com/w/baby-toddler-kids-clothing-2j488z6ymx6zv4dh",
        },
        "Accessories": {
            "Accessories": "https://www.nike.com/w/kids-accessories-equipment-awwpwzv4dh",
            "All Accessories": "https://www.nike.com/w/kids-accessories-equipment-awwpwzv4dh",
            "Bags & Backpacks": "https://www.nike.com/w/kids-bags-and-backpacks-9xy71zv4dh",
            "Hats & Headwear": "https://www.nike.com/w/kids-hats-visors-and-headbands-52r49zv4dh",
            "Socks": "https://www.nike.com/w/kids-socks-7ny3qzv4dh",
        },
        "Shop By Sport": {
            "Basketball": "https://www.nike.com/w/kids-basketball-3glsmzv4dh",
            "Gymnastics": "https://www.nike.com/w/gymnastics-dance-inspired-2obuy",
            "Fan Gear": "https://www.nike.com/w/kids-fan-gear-b170ozv4dh",
            "Football": "https://www.nike.com/w/kids-football-3hj8mzv4dh",
            "Running": "https://www.nike.com/w/kids-running-37v7jzv4dh",
            "Soccer": "https://www.nike.com/w/kids-soccer-1gdj0zv4dh",
        },
    },
    "Jordan": {
        "New & Featured": {
            "New & Featured": "https://www.nike.com/w/new-jordan-37eefz3n82y",
            "New Arrivals": "https://www.nike.com/w/new-jordan-37eefz3n82y",
            "Best Sellers": "https://www.nike.com/w/best-jordan-37eefz76m50",
            "Heat Check": "https://www.nike.com/w/jordan-heat-check-1n7xt",
            "Shop All Sale": "https://www.nike.com/w/sale-jordan-37eefz3yaep",
        },
        "Men": {
            "Men": "https://www.nike.com/w/mens-jordan-37eefznik1",
            "Shop All": "https://www.nike.com/w/mens-jordan-37eefznik1",
            "Shoes": "https://www.nike.com/w/mens-jordan-shoes-37eefznik1zy7ok",
            "AJ1": "https://www.nike.com/w/mens-jordan-1-shoes-4fokyznik1zy7ok",
            "Clothing": "https://www.nike.com/w/mens-jordan-clothing-37eefz6ymx6znik1",
            "Accessories": "https://www.nike.com/w/jordan-accessories-equipment-37eefzawwpw",
        },
        "Women": {
            "Women": "https://www.nike.com/w/womens-jordan-37eefz5e1x6",
            "Shop All": "https://www.nike.com/w/womens-jordan-37eefz5e1x6",
            "Shoes": "https://www.nike.com/w/womens-jordan-shoes-37eefz5e1x6zy7ok",
            "AJ1": "https://www.nike.com/w/womens-jordan-1-shoes-4fokyz5e1x6zy7ok",
            "Clothing": "https://www.nike.com/w/womens-jordan-clothing-37eefz5e1x6z6ymx6",
            "Accessories": "https://www.nike.com/w/jordan-accessories-equipment-37eefzawwpw",
        },
        "Kids": {
            "Kids": "https://www.nike.com/w/kids-jordan-37eefzv4dh",
            "Shop All": "https://www.nike.com/w/kids-jordan-37eefzv4dh",
            "Shoes": "https://www.nike.com/w/kids-jordan-shoes-37eefzv4dhzy7ok",
            "AJ1": "https://www.nike.com/w/jordan-1-shoes-1onraz3aqegz4fokyzy7ok",
            "Clothing": "https://www.nike.com/w/kids-jordan-clothing-37eefz6ymx6zv4dh",
            "Accessories": "https://www.nike.com/w/kids-jordan-accessories-equipment-37eefzawwpwzv4dh",
        },
        "Sport": {
            "Basketball": "https://www.nike.com/w/jordan-basketball-37eefz3glsm",
            "Golf": "https://www.nike.com/w/jordan-golf-23q9wz37eef",
            "Cleats": "https://www.nike.com/w/jordan-cleats-spikes-37eefz5ufbh",
        },
    },
    "NikeSKIMS": {
        "All Shoes": {
            "All Shoes": "https://www.nike.com/w/nikeskims-shoes-b2asdzy7ok",
            "NikeSKIMS Rift": "https://www.nike.com/w/nikeskims-shoes-b2asdzy7ok",
        },
        "All Clothing": {
            "All Clothing": "https://www.nike.com/w/nikeskims-b2asd",
            "Bras": "https://www.nike.com/w/nikeskims-sports-bras-40qgmzb2asd",
            "Jackets": "https://www.nike.com/w/nikeskims-jackets-vests-50r7yzb2asd",
            "Leggings": "https://www.nike.com/w/nikeskims-tights-leggings-29sh2zb2asd",
            "Shorts": "https://www.nike.com/w/nikeskims-shorts-38fphzb2asd",
            "Tops and Tanks": "https://www.nike.com/w/nikeskims-tops-t-shirts-9om13zb2asd",
            "Accessories": "https://www.nike.com/w/nikeskims-accessories-equipment-awwpwzb2asd",
        },
        "Shop by Color": {
            "Shop by Color": "https://www.nike.com/w/nikeskims-b2asd",
            "Carob Brown": "https://www.nike.com/w/nikeskims-brown-557pqzb2asd",
            "Citrine": "https://www.nike.com/w/nikeskims-yellow-ayp69zb2asd",
            "Ivory": "https://www.nike.com/w/nikeskims-white-4g797zb2asd",
            "Obsidian": "https://www.nike.com/w/nikeskims-black-90poyzb2asd",
        },
        "Shop by Material": {
            "Shop by Material": "https://www.nike.com/w/nikeskims-b2asd",
            "Airy": "https://www.nike.com/w/nikeskims-nikeskims-airy-5c1qqzb2asd",
            "Matte": "https://www.nike.com/w/nikeskims-nikeskims-matte-5s3enzb2asd",
            "Performance Cotton Blend": "https://www.nike.com/w/nikeskims-performance-cotton-blend-93ehs",
            "Satin Shine": "https://www.nike.com/w/nikeskims-nikeskims-satin-shine-97fc5zb2asd",
            "Seamless": "https://www.nike.com/w/nikeskims-nikeskims-seamless-6lh4szb2asd",
            "Stretch Knit 2.0": "https://www.nike.com/w/nikeskims-nikeskims-stretch-knit-21jwlzb2asd",
            "Stretch Nylon": "https://www.nike.com/w/nikeskims-stretch-nylon-7sut9",
            "Studio Stretch": "https://www.nike.com/w/nikeskims-studio-stretch-admbq",
            "Weightless": "https://www.nike.com/w/nikeskims-nikeskims-weightless-4csx8zb2asd",
        },
        "NikeSKIMS Guides": {
            "NikeSKIMS Guides": "https://www.nike.com/w/nikeskims-b2asd",
        },
    },
    "Sport": {
        "Basketball": {
            "Shoes": "https://www.nike.com/w/basketball-shoes-3glsmzy7ok",
            "Apparel": "https://www.nike.com/w/basketball-clothing-3glsmz6ymx6",
            "Equipment": "https://www.nike.com/w/basketball-accessories-equipment-3glsmzawwpw",
            "Kobe": "https://www.nike.com/w/kobe-pgd6",
            "Jordan": "https://www.nike.com/w/jordan-basketball-37eefz3glsm",
        },
        "Court": {
            "Tennis": "https://www.nike.com/w/tennis-ed1q",
            "Pickleball": "https://www.nike.com/w/pickleball-273vc",
            "Shoes": "https://www.nike.com/w/tennis-shoes-ed1qzy7ok",
            "Apparel": "https://www.nike.com/w/tennis-clothing-6ymx6zed1q",
            "Equipment": "https://www.nike.com/w/tennis-gear-6bvfkzed1q",
        },
        "Soccer": {
            "Cleats": "https://www.nike.com/w/soccer-shoes-1gdj0zy7ok",
            "Indoor Footwear": "https://www.nike.com/w/indoor-court-soccer-shoes-1gdj0z8yh10zy7ok",
            "Apparel": "https://www.nike.com/w/soccer-clothing-1gdj0z6ymx6",
            "Equipment": "https://www.nike.com/w/soccer-accessories-equipment-1gdj0zawwpw",
        },
        "Training": {
            "Prime": "https://www.nike.com/w/prime-7frqv",
            "Train": "https://www.nike.com/w/training-gym-58jto",
            "Hybrid": "https://www.nike.com/w/hybrid-training-8wvhh",
            "Strength": "https://www.nike.com/w/strength-training-45gbi",
            "Studio": "https://www.nike.com/w/yoga-pilates-59fco",
            "Recover": "https://www.nike.com/w/recover-5vfyy",
        },
        "Running": {
            "Road": "https://www.nike.com/w/road-running-shoes-37v7jz8kwewzy7ok",
            "Race": "https://www.nike.com/w/road-racing-shoes-9gdhkzy7ok",
            "Trail": "https://www.nike.com/w/acg-trail-running-75jcnz93bsd",
            "Track & Field": "https://www.nike.com/w/track-field-shoes-7nem3zy7ok",
            "Apparel": "https://www.nike.com/w/running-clothing-37v7jz6ymx6",
            "Equipment": "https://www.nike.com/w/running-accessories-equipment-37v7jzawwpw",
        },
        "Golf": {
            "Shoes": "https://www.nike.com/w/golf-shoes-23q9wzy7ok",
            "Apparel": "https://www.nike.com/w/golf-clothing-23q9wz6ymx6",
            "Equipment": "https://www.nike.com/w/golf-accessories-equipment-23q9wzawwpw",
        },
        "More Sports": {
            "Cheer": "https://www.nike.com/w/cheerleading-1cyjk",
            "Gymnastics": "https://www.nike.com/w/gymnastics-dance-inspired-2obuy",
            "Lacrosse": "https://www.nike.com/w/lacrosse-4nvmr",
            "Skateboarding": "https://www.nike.com/w/skateboarding-8mfrf",
            "Softball": "https://www.nike.com/w/softball-2dlpv",
            "Volleyball": "https://www.nike.com/w/volleyball-tc2u",
            "Wrestling": "https://www.nike.com/w/wrestling-52dy6",
        },
        "Locker Room": {
            "NBA Gear": "https://www.nike.com/w/nba-1vofi",
            "NFL Gear": "https://www.nike.com/w/nfl-9bklc",
            "MLB Gear": "https://www.nike.com/w/mlb-b0g9x",
            "WNBA Gear": "https://www.nike.com/w/wnba-6ef6n",
            "NCAA Gear": "https://www.nike.com/w/college-teams-2wq2g",
            "NWSL Gear": "https://www.nike.com/w/national-womens-soccer-league-5yy3b",
            "Soccer Club Gear": "https://www.nike.com/w/soccer-clubs-6fu9q",
            "Federations Gear": "https://www.nike.com/w/national-team-soccer-1gdj0zav9de",
        },
        "All Conditions Gear": {
            "Trail Run": "https://www.nike.com/w/acg-trail-running-75jcnz93bsd",
            "Hike": "https://www.nike.com/w/acg-hiking-90dwjz93bsd",
            "Explore": "https://www.nike.com/w/acg-explore-1v964z93bsd",
        },
    },
}
