# Petco category inventory.
#
# Generated from the server-rendered petco.com mega-menu, which emits one
# `/category/<l1>[/<l2>...]/` link per taxonomy node (22 roots / 286 nodes at
# authoring time, 2026-10-03). Paths mirror the site's own category hierarchy,
# so `-a category=cat-cat-food-dry-cat-food` reproduces the breadcrumb order.
from __future__ import annotations

import re


PETCO_CATEGORY_INVENTORY = {'Autoship Eligible Products': {'url': 'https://www.petco.com/shop/en/petcostore/category/autoship-eligible-products'},
 'Back To School': {'url': 'https://www.petco.com/shop/en/petcostore/category/back-to-school'},
 'Bird': {'url': 'https://www.petco.com/shop/en/petcostore/category/bird',
          'subcategories': {'Bird Cleanup And Odor Control': {'url': 'https://www.petco.com/shop/en/petcostore/category/bird/bird-cleanup-and-odor-control'},
                            'Bird Food And Treats': {'url': 'https://www.petco.com/shop/en/petcostore/category/bird/bird-food-and-treats',
                                                     'subcategories': {'Bird Food': {'url': 'https://www.petco.com/shop/en/petcostore/category/bird/bird-food-and-treats/bird-food'}}},
                            'Bird Grooming And Bathing': {'url': 'https://www.petco.com/shop/en/petcostore/category/bird/bird-grooming-and-bathing'},
                            'Bird Health And Wellness': {'url': 'https://www.petco.com/shop/en/petcostore/category/bird/bird-health-and-wellness'},
                            'Bird Houses': {'url': 'https://www.petco.com/shop/en/petcostore/category/bird/bird-houses'},
                            'Bird Perches Swings And Playstands': {'url': 'https://www.petco.com/shop/en/petcostore/category/bird/bird-perches-swings-and-playstands'},
                            'Cages For Birds': {'url': 'https://www.petco.com/shop/en/petcostore/category/bird/cages-for-birds'},
                            'Cockatiel Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/bird/cockatiel-supplies'},
                            'Conure Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/bird/conure-supplies'},
                            'Finch Canary Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/bird/finch-canary-supplies'},
                            'Litter And Liners For Birds': {'url': 'https://www.petco.com/shop/en/petcostore/category/bird/litter-and-liners-for-birds'},
                            'Lovebird Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/bird/lovebird-supplies'},
                            'Parakeet Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/bird/parakeet-supplies'},
                            'Parrot Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/bird/parrot-supplies'},
                            'Pet Birds': {'url': 'https://www.petco.com/shop/en/petcostore/category/bird/pet-birds'},
                            'Toys For Birds': {'url': 'https://www.petco.com/shop/en/petcostore/category/bird/toys-for-birds'},
                            'Waterers And Feeders For Birds': {'url': 'https://www.petco.com/shop/en/petcostore/category/bird/waterers-and-feeders-for-birds'},
                            'Wild Bird': {'url': 'https://www.petco.com/shop/en/petcostore/category/bird/wild-bird'}}},
 'Buy Online Pick Up In Store Products': {'url': 'https://www.petco.com/shop/en/petcostore/category/buy-online-pick-up-in-store-products'},
 'Cat': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat',
         'subcategories': {'Cat Beds And Bedding': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-beds-and-bedding'},
                           'Cat Clothes And Outfits': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-clothes-and-outfits'},
                           'Cat Collars Leashes And Harnesses': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-collars-leashes-and-harnesses'},
                           'Cat Containment': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-containment'},
                           'Cat Feeding Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-feeding-supplies'},
                           'Cat Flea And Tick': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-flea-and-tick'},
                           'Cat Food': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-food',
                                        'subcategories': {'Cat Broths And Food Toppers': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-food/cat-broths-and-food-toppers',
                                                                                          'subcategories': {'Cat Food Toppings': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-food/cat-broths-and-food-toppers/cat-food-toppings'}}},
                                                          'Dry Cat Food': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-food/dry-cat-food'},
                                                          'Kitten Food': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-food/kitten-food'},
                                                          'Premium Cat Food': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-food/premium-cat-food'},
                                                          'Prescription Cat Food And Treats': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-food/prescription-cat-food-and-treats'},
                                                          'Raw Fresh And Frozen Cat Food': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-food/raw-fresh-and-frozen-cat-food'},
                                                          'Wet Cat Food': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-food/wet-cat-food'}}},
                           'Cat Furniture And Scratchers': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-furniture-and-scratchers'},
                           'Cat Grooming And Bathing': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-grooming-and-bathing'},
                           'Cat Health And Wellness': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-health-and-wellness',
                                                       'subcategories': {'Cat Calming Aids': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-health-and-wellness/cat-calming-aids'},
                                                                         'Cat Vitamins And Supplements': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-health-and-wellness/cat-vitamins-and-supplements'},
                                                                         'Dental Care For Cat': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-health-and-wellness/dental-care-for-cat'},
                                                                         'Hairball Control For Cats': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-health-and-wellness/hairball-control-for-cats'}}},
                           'Cat Litter Litter Boxes And Accessories': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-litter-litter-boxes-and-accessories',
                                                                       'subcategories': {'Cat Litter': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-litter-litter-boxes-and-accessories/cat-litter'},
                                                                                         'Cat Litter Boxes And Accessories': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-litter-litter-boxes-and-accessories/cat-litter-boxes-and-accessories'}}},
                           'Cat Toys': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-toys'},
                           'Cat Treats': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-treats',
                                          'subcategories': {'Cat Crunchy Treats': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-treats/cat-crunchy-treats'},
                                                            'Cat Dental Treats And Chews': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-treats/cat-dental-treats-and-chews'},
                                                            'Cat Soft And Chewy Treats': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-treats/cat-soft-and-chewy-treats'},
                                                            'Cat Treats Catnip': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-treats/cat-treats-catnip'},
                                                            'Lickable Cat Treats': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cat-treats/lickable-cat-treats'}}},
                           'Cleaning Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat/cleaning-supplies'}}},
 'Cat Dog Chow': {'url': 'https://www.petco.com/shop/en/petcostore/category/cat-dog-chow'},
 'Dog': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog',
         'subcategories': {'Dog And Puppy Flea And Tick': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-and-puppy-flea-and-tick'},
                           'Dog Apparel': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-apparel'},
                           'Dog Beds And Bedding': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-beds-and-bedding'},
                           'Dog Collars Leashes And Harnesses': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-collars-leashes-and-harnesses'},
                           'Dog Crates Kennels Gates Doors Pens And Housing Accessories': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-crates-kennels-gates-doors-pens-and-housing-accessories'},
                           'Dog Feeding Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-feeding-supplies'},
                           'Dog Food': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-food',
                                        'subcategories': {'Dog Breed Size': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-food/dog-breed-size'},
                                                          'Dog Dietary Preferences': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-food/dog-dietary-preferences'},
                                                          'Dog Food Broth And Toppers': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-food/dog-food-broth-and-toppers'},
                                                          'Dog Health Conditions': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-food/dog-health-conditions'},
                                                          'Dog Life Stage': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-food/dog-life-stage'},
                                                          'Dry Dog Food': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-food/dry-dog-food'},
                                                          'Fresh Frozen Freeze Dried Dog Food': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-food/fresh-frozen-freeze-dried-dog-food'},
                                                          'Prescription Dog Food And Treats': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-food/prescription-dog-food-and-treats'},
                                                          'Wet Dog Food': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-food/wet-dog-food'}}},
                           'Dog Grooming And Bathing': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-grooming-and-bathing'},
                           'Dog Health And Wellness': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-health-and-wellness',
                                                       'subcategories': {'Dental Care': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-health-and-wellness/dental-care'},
                                                                         'Dog Calming Aids': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-health-and-wellness/dog-calming-aids'},
                                                                         'Dog Dna Tests': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-health-and-wellness/dog-dna-tests'},
                                                                         'Dog First Aid': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-health-and-wellness/dog-first-aid'},
                                                                         'Dog Vitamins': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-health-and-wellness/dog-vitamins'}}},
                           'Dog Poop Bags And Clean Up': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-poop-bags-and-clean-up'},
                           'Dog Toys': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-toys'},
                           'Dog Training': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-training'},
                           'Dog Treats And Chews': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-treats-and-chews',
                                                    'subcategories': {'Dog Biscuits Cookies And Snacks': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-treats-and-chews/dog-biscuits-cookies-and-snacks'},
                                                                      'Dog Dental Treats And Chews': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-treats-and-chews/dog-dental-treats-and-chews'},
                                                                      'Dog Natural Chews Bones': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-treats-and-chews/dog-natural-chews-bones'},
                                                                      'Dog Training Treats': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-treats-and-chews/dog-training-treats'},
                                                                      'Jerky Dog Treats': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-treats-and-chews/jerky-dog-treats'},
                                                                      'Soft And Chewy Dog Treats': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/dog-treats-and-chews/soft-and-chewy-dog-treats'}}},
                           'Travel Outdoor Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/dog/travel-outdoor-supplies'}}},
 'Fall Shop': {'url': 'https://www.petco.com/shop/en/petcostore/category/fall-shop',
               'subcategories': {'Cozy Pet Beds And Furniture': {'url': 'https://www.petco.com/shop/en/petcostore/category/fall-shop/cozy-pet-beds-and-furniture'}}},
 'Farm And Feed': {'url': 'https://www.petco.com/shop/en/petcostore/category/farm-and-feed',
                   'subcategories': {'Chicken Shop': {'url': 'https://www.petco.com/shop/en/petcostore/category/farm-and-feed/chicken-shop',
                                                      'subcategories': {'Chicken Poultry Feed': {'url': 'https://www.petco.com/shop/en/petcostore/category/farm-and-feed/chicken-shop/chicken-poultry-feed'},
                                                                        'Duck And Goose Shop': {'url': 'https://www.petco.com/shop/en/petcostore/category/farm-and-feed/chicken-shop/duck-and-goose-shop'},
                                                                        'Poultry Chicken Coops Accessories': {'url': 'https://www.petco.com/shop/en/petcostore/category/farm-and-feed/chicken-shop/poultry-chicken-coops-accessories'},
                                                                        'Poultry Chicken Feeders Waterers': {'url': 'https://www.petco.com/shop/en/petcostore/category/farm-and-feed/chicken-shop/poultry-chicken-feeders-waterers'}}},
                                     'Horse Shop': {'url': 'https://www.petco.com/shop/en/petcostore/category/farm-and-feed/horse-shop',
                                                    'subcategories': {'Horse Feed And Treats': {'url': 'https://www.petco.com/shop/en/petcostore/category/farm-and-feed/horse-shop/horse-feed-and-treats'},
                                                                      'Horse Gooming': {'url': 'https://www.petco.com/shop/en/petcostore/category/farm-and-feed/horse-shop/horse-gooming'},
                                                                      'Horse Health And Wellness': {'url': 'https://www.petco.com/shop/en/petcostore/category/farm-and-feed/horse-shop/horse-health-and-wellness'},
                                                                      'Horse Stable Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/farm-and-feed/horse-shop/horse-stable-supplies'},
                                                                      'Horse Tack Saddlery': {'url': 'https://www.petco.com/shop/en/petcostore/category/farm-and-feed/horse-shop/horse-tack-saddlery'}}},
                                     'Pig Shop': {'url': 'https://www.petco.com/shop/en/petcostore/category/farm-and-feed/pig-shop',
                                                  'subcategories': {'Pig Feeders Waterers Feeding Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/farm-and-feed/pig-shop/pig-feeders-waterers-feeding-supplies'},
                                                                    'Pig Food And Treats': {'url': 'https://www.petco.com/shop/en/petcostore/category/farm-and-feed/pig-shop/pig-food-and-treats'},
                                                                    'Pig Toys': {'url': 'https://www.petco.com/shop/en/petcostore/category/farm-and-feed/pig-shop/pig-toys'}}}}},
 'Fish': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish',
          'subcategories': {'Air Pumps Airstones': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/air-pumps-airstones'},
                            'Aquatic Life': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/aquatic-life',
                                             'subcategories': {'Freshwater Fish': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/aquatic-life/freshwater-fish'},
                                                               'Live Saltwater Fish': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/aquatic-life/live-saltwater-fish'}}},
                            'Feeding Accessories': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/feeding-accessories'},
                            'Fish Aquarium Equipment': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-aquarium-equipment'},
                            'Fish Aquariums Kits': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-aquariums-kits',
                                                    'subcategories': {'Aquarium Stands Cabinets': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-aquariums-kits/aquarium-stands-cabinets'},
                                                                      'Freestanding Large Fish Tanks': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-aquariums-kits/freestanding-large-fish-tanks',
                                                                                                        'subcategories': {'Aquariums 11 To 19 Gallons': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-aquariums-kits/freestanding-large-fish-tanks/aquariums-11-to-19-gallons'},
                                                                                                                          'Aquariums 20 To 39 Gallons': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-aquariums-kits/freestanding-large-fish-tanks/aquariums-20-to-39-gallons'},
                                                                                                                          'Aquariums 40 To 54 Gallons': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-aquariums-kits/freestanding-large-fish-tanks/aquariums-40-to-54-gallons'},
                                                                                                                          'Aquariums Up To Ten Gallons': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-aquariums-kits/freestanding-large-fish-tanks/aquariums-up-to-ten-gallons'}}}}},
                            'Fish Food': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-food',
                                          'subcategories': {'Freshwater Fish Food': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-food/freshwater-fish-food'},
                                                            'Frozen Fish Food': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-food/frozen-fish-food'},
                                                            'Live Fish Foods': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-food/live-fish-foods'},
                                                            'Saltwater Fish Food': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-food/saltwater-fish-food'}}},
                            'Fish Tank Cleaning': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-tank-cleaning'},
                            'Fish Tank Decor': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-tank-decor',
                                                'subcategories': {'Aquarium Rocks And Coral': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-tank-decor/aquarium-rocks-and-coral'},
                                                                  'Fish Decor Wood Logs': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-tank-decor/fish-decor-wood-logs'},
                                                                  'Fish Tank Backgrounds': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-tank-decor/fish-tank-backgrounds'},
                                                                  'Fish Tank Ornaments': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-tank-decor/fish-tank-ornaments'}}},
                            'Fish Tank Filtration': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-tank-filtration'},
                            'Fish Tank Hoods Lighting': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-tank-hoods-lighting'},
                            'Fish Tank Maintenance': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-tank-maintenance'},
                            'Fish Tank Sand Gravel Substrate': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-tank-sand-gravel-substrate'},
                            'Fish Water Care': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-water-care',
                                                'subcategories': {'Fish Tank Algae Control': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-water-care/fish-tank-algae-control'},
                                                                  'Fish Tank Reef Additives': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-water-care/fish-tank-reef-additives'},
                                                                  'Fish Tank Salt Mixes': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-water-care/fish-tank-salt-mixes'},
                                                                  'Fish Tank Testing Kits': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-water-care/fish-tank-testing-kits'},
                                                                  'Fish Tank Water': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-water-care/fish-tank-water'},
                                                                  'Fish Tank Water Conditioners Additives': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/fish-water-care/fish-tank-water-conditioners-additives'}}},
                            'Live Plants': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/live-plants',
                                            'subcategories': {'Live Plants 1': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/live-plants/live-plants-1'}}},
                            'Planted Shrimp Tank': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/planted-shrimp-tank'},
                            'Pond Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/fish/pond-supplies'}}},
 'Gardening With Pets': {'url': 'https://www.petco.com/shop/en/petcostore/category/gardening-with-pets'},
 'Halloween Shop': {'url': 'https://www.petco.com/shop/en/petcostore/category/halloween-shop',
                    'subcategories': {'Halloween Accessories': {'url': 'https://www.petco.com/shop/en/petcostore/category/halloween-shop/halloween-accessories'},
                                      'Halloween Costumes': {'url': 'https://www.petco.com/shop/en/petcostore/category/halloween-shop/halloween-costumes',
                                                             'subcategories': {'Halloween Cat Costumes': {'url': 'https://www.petco.com/shop/en/petcostore/category/halloween-shop/halloween-costumes/halloween-cat-costumes'},
                                                                               'Halloween Dog Costumes': {'url': 'https://www.petco.com/shop/en/petcostore/category/halloween-shop/halloween-costumes/halloween-dog-costumes'}}},
                                      'Halloween Home Essentials': {'url': 'https://www.petco.com/shop/en/petcostore/category/halloween-shop/halloween-home-essentials'},
                                      'Halloween Safety Shop': {'url': 'https://www.petco.com/shop/en/petcostore/category/halloween-shop/halloween-safety-shop'},
                                      'Halloween Toys': {'url': 'https://www.petco.com/shop/en/petcostore/category/halloween-shop/halloween-toys'},
                                      'Halloween Treats Toys': {'url': 'https://www.petco.com/shop/en/petcostore/category/halloween-shop/halloween-treats-toys'}}},
 'My Human': {'url': 'https://www.petco.com/shop/en/petcostore/category/my-human',
              'subcategories': {'Apparel': {'url': 'https://www.petco.com/shop/en/petcostore/category/my-human/apparel'},
                                'Arts And Crafts': {'url': 'https://www.petco.com/shop/en/petcostore/category/my-human/arts-and-crafts'},
                                'Games And Toys': {'url': 'https://www.petco.com/shop/en/petcostore/category/my-human/games-and-toys'},
                                'Gifting': {'url': 'https://www.petco.com/shop/en/petcostore/category/my-human/gifting',
                                            'subcategories': {'Gifts For Cat Lovers': {'url': 'https://www.petco.com/shop/en/petcostore/category/my-human/gifting/gifts-for-cat-lovers'},
                                                              'Gifts For Dog Lovers': {'url': 'https://www.petco.com/shop/en/petcostore/category/my-human/gifting/gifts-for-dog-lovers'}}},
                                'Home Goods': {'url': 'https://www.petco.com/shop/en/petcostore/category/my-human/home-goods',
                                               'subcategories': {'Garden And Yard': {'url': 'https://www.petco.com/shop/en/petcostore/category/my-human/home-goods/garden-and-yard'},
                                                                 'Home Decor': {'url': 'https://www.petco.com/shop/en/petcostore/category/my-human/home-goods/home-decor',
                                                                                'subcategories': {'Decorative Objects And Trays': {'url': 'https://www.petco.com/shop/en/petcostore/category/my-human/home-goods/home-decor/decorative-objects-and-trays'},
                                                                                                  'Picture Frames': {'url': 'https://www.petco.com/shop/en/petcostore/category/my-human/home-goods/home-decor/picture-frames'}}},
                                                                 'Kitchen Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/my-human/home-goods/kitchen-supplies'},
                                                                 'My Human Furniture': {'url': 'https://www.petco.com/shop/en/petcostore/category/my-human/home-goods/my-human-furniture'}}},
                                'Human Cleaning Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/my-human/human-cleaning-supplies'},
                                'Office Supplies And Stationery': {'url': 'https://www.petco.com/shop/en/petcostore/category/my-human/office-supplies-and-stationery',
                                                                   'subcategories': {'Cards And Gifting': {'url': 'https://www.petco.com/shop/en/petcostore/category/my-human/office-supplies-and-stationery/cards-and-gifting'}}}}},
 'Pet Jerseys And Sports Gear': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-jerseys-and-sports-gear'},
 'Pet Pharmacy': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-pharmacy',
                  'subcategories': {'Cat Rx': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-pharmacy/cat-rx',
                                               'subcategories': {'Rx Cat Allergy Relief': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-pharmacy/cat-rx/rx-cat-allergy-relief'},
                                                                 'Rx Cat Antibiotics': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-pharmacy/cat-rx/rx-cat-antibiotics'},
                                                                 'Rx Cat Ear Eye Care': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-pharmacy/cat-rx/rx-cat-ear-eye-care'},
                                                                 'Rx Cat Flea Medicine': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-pharmacy/cat-rx/rx-cat-flea-medicine'},
                                                                 'Rx Cat Heartworm': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-pharmacy/cat-rx/rx-cat-heartworm'},
                                                                 'Rx Cat Pain Relief Arthritis': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-pharmacy/cat-rx/rx-cat-pain-relief-arthritis'},
                                                                 'Rx Cat Urinary': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-pharmacy/cat-rx/rx-cat-urinary'}}},
                                    'Dog Rx': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-pharmacy/dog-rx',
                                               'subcategories': {'Flea And Tick': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-pharmacy/dog-rx/flea-and-tick'},
                                                                 'Rx Dog Allergy Relief': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-pharmacy/dog-rx/rx-dog-allergy-relief'},
                                                                 'Rx Dog Antibiotics': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-pharmacy/dog-rx/rx-dog-antibiotics'},
                                                                 'Rx Dog Anxiety': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-pharmacy/dog-rx/rx-dog-anxiety'},
                                                                 'Rx Dog Ear Eye Care': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-pharmacy/dog-rx/rx-dog-ear-eye-care'},
                                                                 'Rx Dog Heart Blood Pressure': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-pharmacy/dog-rx/rx-dog-heart-blood-pressure'},
                                                                 'Rx Dog Heartworm': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-pharmacy/dog-rx/rx-dog-heartworm'},
                                                                 'Rx Dog Pain Relief Arthritis': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-pharmacy/dog-rx/rx-dog-pain-relief-arthritis'}}},
                                    'Horse Rx': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-pharmacy/horse-rx',
                                                 'subcategories': {'Rx Horse Antibiotics': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-pharmacy/horse-rx/rx-horse-antibiotics'},
                                                                   'Rx Horse Anxiety': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-pharmacy/horse-rx/rx-horse-anxiety'},
                                                                   'Rx Horse Digestive': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-pharmacy/horse-rx/rx-horse-digestive'},
                                                                   'Rx Horse Pain Relief': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-pharmacy/horse-rx/rx-horse-pain-relief'},
                                                                   'Rx Horse Thyroid Hormone': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-pharmacy/horse-rx/rx-horse-thyroid-hormone'}}},
                                    'Pest Protection': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-pharmacy/pest-protection'}}},
 'Pet Technology': {'url': 'https://www.petco.com/shop/en/petcostore/category/pet-technology'},
 'Reptile': {'url': 'https://www.petco.com/shop/en/petcostore/category/reptile',
             'subcategories': {'Ball Python Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/reptile/ball-python-supplies'},
                               'Bearded Dragon Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/reptile/bearded-dragon-supplies'},
                               'Bioactive Zone': {'url': 'https://www.petco.com/shop/en/petcostore/category/reptile/bioactive-zone'},
                               'Chameleon Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/reptile/chameleon-supplies'},
                               'Crested Gecko Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/reptile/crested-gecko-supplies'},
                               'Decor Hideaways': {'url': 'https://www.petco.com/shop/en/petcostore/category/reptile/decor-hideaways'},
                               'Frog Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/reptile/frog-supplies'},
                               'Hermit Crab Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/reptile/hermit-crab-supplies'},
                               'Leopard Gecko Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/reptile/leopard-gecko-supplies'},
                               'Pet Reptiles': {'url': 'https://www.petco.com/shop/en/petcostore/category/reptile/pet-reptiles'},
                               'Reptile Cleanup And Odor Control': {'url': 'https://www.petco.com/shop/en/petcostore/category/reptile/reptile-cleanup-and-odor-control'},
                               'Reptile Filters Pumps': {'url': 'https://www.petco.com/shop/en/petcostore/category/reptile/reptile-filters-pumps'},
                               'Reptile Food': {'url': 'https://www.petco.com/shop/en/petcostore/category/reptile/reptile-food'},
                               'Reptile Food Water Accessories': {'url': 'https://www.petco.com/shop/en/petcostore/category/reptile/reptile-food-water-accessories'},
                               'Reptile Habitats And Enclosures': {'url': 'https://www.petco.com/shop/en/petcostore/category/reptile/reptile-habitats-and-enclosures'},
                               'Reptile Health And Wellness': {'url': 'https://www.petco.com/shop/en/petcostore/category/reptile/reptile-health-and-wellness'},
                               'Reptile Heating Lighting': {'url': 'https://www.petco.com/shop/en/petcostore/category/reptile/reptile-heating-lighting',
                                                            'subcategories': {'Heat Lamps And Bulbs': {'url': 'https://www.petco.com/shop/en/petcostore/category/reptile/reptile-heating-lighting/heat-lamps-and-bulbs'}}},
                               'Reptile Stands Covers': {'url': 'https://www.petco.com/shop/en/petcostore/category/reptile/reptile-stands-covers'},
                               'Reptile Substrate Bedding': {'url': 'https://www.petco.com/shop/en/petcostore/category/reptile/reptile-substrate-bedding'},
                               'Reptile Tank Accessories': {'url': 'https://www.petco.com/shop/en/petcostore/category/reptile/reptile-tank-accessories'},
                               'Snake Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/reptile/snake-supplies'},
                               'Spider Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/reptile/spider-supplies'},
                               'Tortoise Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/reptile/tortoise-supplies'},
                               'Turtle Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/reptile/turtle-supplies'}}},
 'Same Day Delivery Products': {'url': 'https://www.petco.com/shop/en/petcostore/category/same-day-delivery-products'},
 'Small Animal': {'url': 'https://www.petco.com/shop/en/petcostore/category/small-animal',
                  'subcategories': {'Chinchilla Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/small-animal/chinchilla-supplies'},
                                    'Ferret Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/small-animal/ferret-supplies'},
                                    'Guinea Pig Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/small-animal/guinea-pig-supplies'},
                                    'Hamster Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/small-animal/hamster-supplies'},
                                    'Pet Small Animals': {'url': 'https://www.petco.com/shop/en/petcostore/category/small-animal/pet-small-animals'},
                                    'Rabbit Shop': {'url': 'https://www.petco.com/shop/en/petcostore/category/small-animal/rabbit-shop'},
                                    'Rat Mouse Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/small-animal/rat-mouse-supplies'},
                                    'Small Animal Bedding Litter': {'url': 'https://www.petco.com/shop/en/petcostore/category/small-animal/small-animal-bedding-litter'},
                                    'Small Animal Cages Habitats': {'url': 'https://www.petco.com/shop/en/petcostore/category/small-animal/small-animal-cages-habitats'},
                                    'Small Animal Carriers': {'url': 'https://www.petco.com/shop/en/petcostore/category/small-animal/small-animal-carriers'},
                                    'Small Animal Cleanup Odor Control': {'url': 'https://www.petco.com/shop/en/petcostore/category/small-animal/small-animal-cleanup-odor-control'},
                                    'Small Animal Collars Leashes Harnesses': {'url': 'https://www.petco.com/shop/en/petcostore/category/small-animal/small-animal-collars-leashes-harnesses'},
                                    'Small Animal Feeding Supplies': {'url': 'https://www.petco.com/shop/en/petcostore/category/small-animal/small-animal-feeding-supplies'},
                                    'Small Animal Food Treats': {'url': 'https://www.petco.com/shop/en/petcostore/category/small-animal/small-animal-food-treats',
                                                                 'subcategories': {'Small Animal Food': {'url': 'https://www.petco.com/shop/en/petcostore/category/small-animal/small-animal-food-treats/small-animal-food'},
                                                                                   'Small Animal Hay Grass': {'url': 'https://www.petco.com/shop/en/petcostore/category/small-animal/small-animal-food-treats/small-animal-hay-grass'}}},
                                    'Small Animal Food Treats And Chews': {'url': 'https://www.petco.com/shop/en/petcostore/category/small-animal/small-animal-food-treats-and-chews'},
                                    'Small Animal Grooming Bathing': {'url': 'https://www.petco.com/shop/en/petcostore/category/small-animal/small-animal-grooming-bathing'},
                                    'Small Animal Health Wellness': {'url': 'https://www.petco.com/shop/en/petcostore/category/small-animal/small-animal-health-wellness'},
                                    'Small Animal Sleepers Hideaways': {'url': 'https://www.petco.com/shop/en/petcostore/category/small-animal/small-animal-sleepers-hideaways'},
                                    'Small Animal Toys Habitat Accessories': {'url': 'https://www.petco.com/shop/en/petcostore/category/small-animal/small-animal-toys-habitat-accessories'}}},
 'Top Deals': {'url': 'https://www.petco.com/shop/en/petcostore/category/top-deals',
               'subcategories': {'Bird Deals': {'url': 'https://www.petco.com/shop/en/petcostore/category/top-deals/bird-deals'},
                                 'Cat Deals': {'url': 'https://www.petco.com/shop/en/petcostore/category/top-deals/cat-deals',
                                               'subcategories': {'Cat Food Deals': {'url': 'https://www.petco.com/shop/en/petcostore/category/top-deals/cat-deals/cat-food-deals',
                                                                                    'subcategories': {'Bogo Cat Food Deals': {'url': 'https://www.petco.com/shop/en/petcostore/category/top-deals/cat-deals/cat-food-deals/bogo-cat-food-deals'}}}}},
                                 'Clearance': {'url': 'https://www.petco.com/shop/en/petcostore/category/top-deals/clearance',
                                               'subcategories': {'Cat Clearance': {'url': 'https://www.petco.com/shop/en/petcostore/category/top-deals/clearance/cat-clearance'},
                                                                 'Dog Clearance': {'url': 'https://www.petco.com/shop/en/petcostore/category/top-deals/clearance/dog-clearance'},
                                                                 'Fish Small Pet Clearance': {'url': 'https://www.petco.com/shop/en/petcostore/category/top-deals/clearance/fish-small-pet-clearance',
                                                                                              'subcategories': {'Top Deals Fish Clearance': {'url': 'https://www.petco.com/shop/en/petcostore/category/top-deals/clearance/fish-small-pet-clearance/top-deals-fish-clearance'},
                                                                                                                'Top Deals Reptile Clearance': {'url': 'https://www.petco.com/shop/en/petcostore/category/top-deals/clearance/fish-small-pet-clearance/top-deals-reptile-clearance'}}}}},
                                 'Dog Deals': {'url': 'https://www.petco.com/shop/en/petcostore/category/top-deals/dog-deals'},
                                 'Fish Deals': {'url': 'https://www.petco.com/shop/en/petcostore/category/top-deals/fish-deals',
                                                'subcategories': {'Fish Tanks Kits Stands Deals': {'url': 'https://www.petco.com/shop/en/petcostore/category/top-deals/fish-deals/fish-tanks-kits-stands-deals'}}},
                                 'Reptile Deals': {'url': 'https://www.petco.com/shop/en/petcostore/category/top-deals/reptile-deals'},
                                 'Small Pet Deals': {'url': 'https://www.petco.com/shop/en/petcostore/category/top-deals/small-pet-deals'}}},
 'Trending Now': {'url': 'https://www.petco.com/shop/en/petcostore/category/trending-now',
                  'subcategories': {'Trending Shop 2': {'url': 'https://www.petco.com/shop/en/petcostore/category/trending-now/trending-shop-2'}}},
 'Trending Shops': {'url': 'https://www.petco.com/shop/en/petcostore/category/trending-shops',
                    'subcategories': {'Everyday Essentials': {'url': 'https://www.petco.com/shop/en/petcostore/category/trending-shops/everyday-essentials',
                                                              'subcategories': {'Everyday Low Prices Flea And Tick': {'url': 'https://www.petco.com/shop/en/petcostore/category/trending-shops/everyday-essentials/everyday-low-prices-flea-and-tick'}}},
                                      'Fall Shop': {'url': 'https://www.petco.com/shop/en/petcostore/category/trending-shops/fall-shop'},
                                      'My Human Faves': {'url': 'https://www.petco.com/shop/en/petcostore/category/trending-shops/my-human-faves'},
                                      'New At Petco': {'url': 'https://www.petco.com/shop/en/petcostore/category/trending-shops/new-at-petco',
                                                       'subcategories': {'New At Petco For Birds': {'url': 'https://www.petco.com/shop/en/petcostore/category/trending-shops/new-at-petco/new-at-petco-for-birds'},
                                                                         'New At Petco For Cats': {'url': 'https://www.petco.com/shop/en/petcostore/category/trending-shops/new-at-petco/new-at-petco-for-cats'},
                                                                         'New At Petco For Dogs': {'url': 'https://www.petco.com/shop/en/petcostore/category/trending-shops/new-at-petco/new-at-petco-for-dogs'},
                                                                         'New At Petco For Fish': {'url': 'https://www.petco.com/shop/en/petcostore/category/trending-shops/new-at-petco/new-at-petco-for-fish'},
                                                                         'New At Petco For Pet Parents': {'url': 'https://www.petco.com/shop/en/petcostore/category/trending-shops/new-at-petco/new-at-petco-for-pet-parents'},
                                                                         'New At Petco For Reptiles': {'url': 'https://www.petco.com/shop/en/petcostore/category/trending-shops/new-at-petco/new-at-petco-for-reptiles'},
                                                                         'New At Petco For Small Pets': {'url': 'https://www.petco.com/shop/en/petcostore/category/trending-shops/new-at-petco/new-at-petco-for-small-pets'}}},
                                      'Summer Shop': {'url': 'https://www.petco.com/shop/en/petcostore/category/trending-shops/summer-shop'}}}}


def _slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")


def _flatten_categories() -> list[dict[str, str]]:
    """Flatten the nested inventory into `-a category=` entries.

    The category name is the slug of the full category path (`cat-cat-food-dry-cat-food`)
    so sibling departments never collide on a short leaf name.
    """

    categories: list[dict[str, str]] = []
    seen_urls: set[str] = set()
    seen_names: set[str] = set()

    def walk(node, slugs, department, subcategory):
        for label, entry in node.items():
            path = list(slugs) + [label]
            name = _slug(" ".join(path))
            if name in seen_names or entry["url"] in seen_urls:
                continue
            seen_names.add(name)
            seen_urls.add(entry["url"])
            leaf = label if path[-1] != department else subcategory
            categories.append(
                {
                    "category": name,
                    "department": department,
                    "subcategory": leaf,
                    "url": entry["url"],
                }
            )
            walk(entry.get("subcategories", {}), path, department, leaf)

    for root_label, group in PETCO_CATEGORY_INVENTORY.items():
        walk(group.get("subcategories", {}), [root_label], root_label, root_label)

    return categories


PETCO_CATEGORIES = _flatten_categories()
