"""PetSmart US category inventory captured from the first-party search API.

Source (POST, no authentication, no API key)::

    https://www.petsmart.com/api/search/1/indexes/r-US_products_best-sellers/query
    {"params": "query=&hitsPerPage=0&maxValuesPerFacet=1000&facets=custom_category_names"}

``custom_category_names`` is the facet the storefront PLPs themselves filter on
(``filters=custom_category_names:"Dog > Food > Dry Food"``), so this inventory is
the *browse taxonomy* the site actually uses for product listing -- not a list of
hand-maintained marketing URLs.

Captured: 2026-10-04 (US storefront, ``r-US_products_best-sellers``).
Result: 7 departments, 491 category paths, every entry carrying the number of
SKUs in the index that carry that exact path.

Each key is an API category path (``" > "`` separated); each value is the SKU
count for that path. Marketing-only trees (``Sale``, ``Featured Shops``,
``Featured Brands``, ``PA``, ``Pharmacy``, ...) are excluded: they are campaigns
and merchandising overlays, not browse departments.

URLs are derived from the API path with ``_segment_slug`` (the PLP route rule the
storefront uses, e.g. ``Dog > Food > Dry Food`` -> ``/dog/food/dry-food/``). All
491 derived URLs were verified on 2026-10-04; 15 of them redirect because the
storefront moved the landing page, and those are pinned in
``CANONICAL_URL_OVERRIDES`` so the inventory keeps real 200 URLs.
"""

from __future__ import annotations

import re

PETSMART_DEPARTMENTS = (
    "Bird",
    "Cat",
    "Dog",
    "Farm Animal",
    "Fish",
    "Reptile",
    "Small Pet",
)

# API category path -> SKU count in r-US_products_best-sellers (2026-10-04).
PETSMART_CATEGORY_COUNTS: dict[str, int] = {
    "Bird": 892,
    "Bird > Bird Shops": 487,
    "Bird > Bird Shops > Chicken": 20,
    "Bird > Bird Shops > Cockatiel": 193,
    "Bird > Bird Shops > Cockatiel > Cages and Accessories": 63,
    "Bird > Bird Shops > Cockatiel > Care and Health": 7,
    "Bird > Bird Shops > Cockatiel > Food and Feeding": 50,
    "Bird > Bird Shops > Cockatiel > Toys and Perches": 7,
    "Bird > Bird Shops > Conure": 195,
    "Bird > Bird Shops > Conure > Cages and Accessories": 56,
    "Bird > Bird Shops > Conure > Care and Health": 4,
    "Bird > Bird Shops > Conure > Food and Feeding": 52,
    "Bird > Bird Shops > Conure > Toys and Perches": 6,
    "Bird > Bird Shops > Finch and Canary": 110,
    "Bird > Bird Shops > Finch and Canary > Cages and Accessories": 26,
    "Bird > Bird Shops > Finch and Canary > Food and Feeding": 15,
    "Bird > Bird Shops > Finch and Canary > Toys and Perches": 6,
    "Bird > Bird Shops > Lovebird": 95,
    "Bird > Bird Shops > Lovebird > Cages and Accessories": 40,
    "Bird > Bird Shops > Lovebird > Care and Health": 6,
    "Bird > Bird Shops > Lovebird > Food and Feeding": 3,
    "Bird > Bird Shops > Lovebird > Toys and Perches": 7,
    "Bird > Bird Shops > Parakeet": 165,
    "Bird > Bird Shops > Parakeet > Cages and Accessories": 45,
    "Bird > Bird Shops > Parakeet > Care and Health": 6,
    "Bird > Bird Shops > Parakeet > Food and Feeding": 55,
    "Bird > Bird Shops > Parakeet > Toys and Perches": 19,
    "Bird > Bird Shops > Parrot": 54,
    "Bird > Bird Shops > Parrot > Cages and Accessories": 13,
    "Bird > Bird Shops > Parrot > Food and Feeding": 19,
    "Bird > Bird Shops > Wild Bird": 112,
    "Bird > Bird Shops > Wild Bird > Coops and Outdoor Habitats": 11,
    "Bird > Bird Shops > Wild Bird > Feeders and Waterers": 27,
    "Bird > Bird Shops > Wild Bird > Seed and Suet": 69,
    "Bird > Bowls and Feeders": 18,
    "Bird > Bowls and Feeders > Cups": 9,
    "Bird > Bowls and Feeders > Feeders and Treat Holders": 9,
    "Bird > Cages and Stands": 275,
    "Bird > Cages and Stands > Cage Covers": 9,
    "Bird > Cages and Stands > Cages": 230,
    "Bird > Cages and Stands > Stands": 28,
    "Bird > Cages and Stands > Travel Carriers": 8,
    "Bird > Cleaning and Odor Control": 7,
    "Bird > Cleaning and Odor Control > Cage Liners": 6,
    "Bird > Cleaning and Odor Control > Deodorizers and Waste Cleanup": 1,
    "Bird > Food and Treats": 306,
    "Bird > Food and Treats > Pet Bird Food": 162,
    "Bird > Food and Treats > Treats": 53,
    "Bird > Food and Treats > Wild Bird Food": 95,
    "Bird > Grooming": 12,
    "Bird > Grooming > Bird Baths": 2,
    "Bird > Grooming > Nail and Beak Trimmers": 10,
    "Bird > Health Care and Vitamins": 23,
    "Bird > Health Care and Vitamins > Treatments": 14,
    "Bird > Health Care and Vitamins > Vitamins and Supplements": 9,
    "Bird > Litter and Nesting": 25,
    "Bird > Litter and Nesting > Cage Liners": 6,
    "Bird > Litter and Nesting > Litter and Bedding": 8,
    "Bird > Litter and Nesting > Nesting Supplies": 11,
    "Bird > Live Birds": 9,
    "Bird > Live Birds > Conure Parakeets and More": 9,
    "Bird > Starter Kits": 8,
    "Bird > Toys Perches and Decor": 170,
    "Bird > Toys Perches and Decor > Ladders": 12,
    "Bird > Toys Perches and Decor > Mirrors": 1,
    "Bird > Toys Perches and Decor > Perches and Swings": 44,
    "Bird > Toys Perches and Decor > Toys": 113,
    "Bird > Wild Bird Food and Supplies": 93,
    "Bird > Wild Bird Food and Supplies > Coops and Outdoor Habitats": 10,
    "Bird > Wild Bird Food and Supplies > Outdoor Bird Baths": 5,
    "Bird > Wild Bird Food and Supplies > Outdoor Feeders": 39,
    "Bird > Wild Bird Food and Supplies > Wild Bird Food": 39,
    "Cat": 6575,
    "Cat > Beds and Furniture": 974,
    "Cat > Beds and Furniture > Covered Beds": 100,
    "Cat > Beds and Furniture > Cuddler Beds": 201,
    "Cat > Beds and Furniture > Furniture and Towers": 448,
    "Cat > Beds and Furniture > Heated Beds": 44,
    "Cat > Beds and Furniture > Scratchers": 182,
    "Cat > Beds and Furniture > Window Perches": 11,
    "Cat > Bowls and Feeders": 263,
    "Cat > Bowls and Feeders > Automatic Feeders": 60,
    "Cat > Bowls and Feeders > Elevated Stands": 12,
    "Cat > Bowls and Feeders > Food and Water Bowls": 123,
    "Cat > Bowls and Feeders > Placemats": 60,
    "Cat > Bowls and Feeders > Storage and Scoops": 24,
    "Cat > Cleaning and Repellents": 92,
    "Cat > Cleaning and Repellents > Furniture and Home Protection": 3,
    "Cat > Cleaning and Repellents > Pet Hair Removers": 9,
    "Cat > Cleaning and Repellents > Repellents": 17,
    "Cat > Cleaning and Repellents > Stain and Odor Removers": 72,
    "Cat > Cleaning and Repellents > Vacuums": 9,
    "Cat > Clothing and Accessories": 210,
    "Cat > Clothing and Accessories > Accessories": 63,
    "Cat > Clothing and Accessories > Clothing": 147,
    "Cat > Collars Harnesses and Leashes": 490,
    "Cat > Collars Harnesses and Leashes > Collars": 295,
    "Cat > Collars Harnesses and Leashes > Harnesses": 93,
    "Cat > Collars Harnesses and Leashes > Id Tags": 67,
    "Cat > Collars Harnesses and Leashes > Leashes": 57,
    "Cat > Crates Gates and Containment": 191,
    "Cat > Crates Gates and Containment > Carriers": 174,
    "Cat > Crates Gates and Containment > Doors": 10,
    "Cat > Crates Gates and Containment > Pens": 7,
    "Cat > Flea and Tick": 117,
    "Cat > Flea and Tick > Combs and Tools": 3,
    "Cat > Flea and Tick > Flea Shampoos and Dips": 12,
    "Cat > Flea and Tick > Flea and Tick Collars": 8,
    "Cat > Flea and Tick > Flea and Tick Pet Sprays": 11,
    "Cat > Flea and Tick > Flea and Tick Pills": 10,
    "Cat > Flea and Tick > Home and Yard Treatment": 16,
    "Cat > Flea and Tick > Spot On": 62,
    "Cat > Food and Treats": 2939,
    "Cat > Food and Treats > Catnip and Grass": 12,
    "Cat > Food and Treats > Dry Food": 673,
    "Cat > Food and Treats > Food Toppers": 290,
    "Cat > Food and Treats > Freeze Dried Food": 20,
    "Cat > Food and Treats > Frozen Food": 2,
    "Cat > Food and Treats > Kitten Food": 284,
    "Cat > Food and Treats > Milk Replacers": 3,
    "Cat > Food and Treats > Treats": 416,
    "Cat > Food and Treats > Veterinary Diets": 183,
    "Cat > Food and Treats > Wet Food": 1693,
    "Cat > Grooming Supplies": 105,
    "Cat > Grooming Supplies > Brushes Combs and Blowdryers": 23,
    "Cat > Grooming Supplies > Nail Clippers and Caps": 11,
    "Cat > Grooming Supplies > Shampoos and Conditioners": 32,
    "Cat > Grooming Supplies > Wipes and Deodorizers": 43,
    "Cat > Health and Wellness": 390,
    "Cat > Health and Wellness > Anxiety and Calming Care": 55,
    "Cat > Health and Wellness > Dental and Breath Care": 60,
    "Cat > Health and Wellness > Dewormers": 15,
    "Cat > Health and Wellness > Diarrhea and Digestion Relief": 11,
    "Cat > Health and Wellness > Dummy Category to Ignore Articles in PIM": 13,
    "Cat > Health and Wellness > Ear and Eye Care": 30,
    "Cat > Health and Wellness > First Aid and Recovery": 67,
    "Cat > Health and Wellness > Hairball Remedy": 19,
    "Cat > Health and Wellness > Hot Spot and Itch Relief": 12,
    "Cat > Health and Wellness > Milk Replacers and Nursing Kits": 8,
    "Cat > Health and Wellness > Pill Administration": 5,
    "Cat > Health and Wellness > Vitamins and Supplements": 171,
    "Cat > Kitten Supplies": 3,
    "Cat > Litter and Waste Disposal": 526,
    "Cat > Litter and Waste Disposal > Deodorizers and Filters": 49,
    "Cat > Litter and Waste Disposal > Litter": 195,
    "Cat > Litter and Waste Disposal > Litter Boxes": 217,
    "Cat > Litter and Waste Disposal > Mats and Liners": 49,
    "Cat > Litter and Waste Disposal > Waste Disposal": 34,
    "Cat > Toys": 536,
    "Cat > Toys > Balls and Chasers": 6,
    "Cat > Toys > Catnip and Grass": 54,
    "Cat > Toys > Hunting and Stalking Toys": 3,
    "Cat > Toys > Interactive and Electronic": 77,
    "Cat > Toys > Multi Pack": 5,
    "Cat > Toys > Plush Balls and Mice": 152,
    "Cat > Toys > Scratchers": 150,
    "Cat > Toys > Teasers and Wands": 65,
    "Cat > Toys > Toy Storage": 7,
    "Cat > Toys > Tunnels Tents and Sacks": 24,
    "Cat > Vitamins and Supplements": 166,
    "Cat > Vitamins and Supplements > Anxiety and Calming": 24,
    "Cat > Vitamins and Supplements > Dietary Supplements": 4,
    "Cat > Vitamins and Supplements > Hairball Control": 16,
    "Cat > Vitamins and Supplements > Hip and Joint": 24,
    "Cat > Vitamins and Supplements > Immune System and Allergy": 34,
    "Cat > Vitamins and Supplements > Multivitamins": 9,
    "Cat > Vitamins and Supplements > Probiotic and Digestive": 25,
    "Cat > Vitamins and Supplements > Skin and Coat": 23,
    "Cat > Vitamins and Supplements > Urinary and Kidney": 24,
    "Dog": 25633,
    "Dog > Beds and Furniture": 2313,
    "Dog > Beds and Furniture > Blankets": 106,
    "Dog > Beds and Furniture > Cooling and Heating Beds": 91,
    "Dog > Beds and Furniture > Crate Mats": 243,
    "Dog > Beds and Furniture > Cuddler Beds": 587,
    "Dog > Beds and Furniture > Elevated Beds": 37,
    "Dog > Beds and Furniture > Orthopedic Beds": 512,
    "Dog > Beds and Furniture > Pillow Beds": 653,
    "Dog > Beds and Furniture > Ramps and Steps": 96,
    "Dog > Bowls and Feeders": 620,
    "Dog > Bowls and Feeders > Automatic Feeders": 59,
    "Dog > Bowls and Feeders > Elevated Stands": 20,
    "Dog > Bowls and Feeders > Food and Water Bowls": 360,
    "Dog > Bowls and Feeders > Placemats": 127,
    "Dog > Bowls and Feeders > Storage and Scoops": 61,
    "Dog > Cleaning Supplies": 458,
    "Dog > Cleaning Supplies > Furniture and Car Protection": 24,
    "Dog > Cleaning Supplies > Pet Hair Removers": 14,
    "Dog > Cleaning Supplies > Stain and Odor Removers": 95,
    "Dog > Cleaning Supplies > Vacuums": 25,
    "Dog > Cleaning Supplies > Waste Disposal": 305,
    "Dog > Clothing and Shoes": 7212,
    "Dog > Clothing and Shoes > Bandanas Bows and Hats": 226,
    "Dog > Clothing and Shoes > Boots Shoes and Socks": 223,
    "Dog > Clothing and Shoes > Costumes": 872,
    "Dog > Clothing and Shoes > Dresses": 78,
    "Dog > Clothing and Shoes > Hoodies and Sweatshirts": 273,
    "Dog > Clothing and Shoes > Jackets and Coats": 1713,
    "Dog > Clothing and Shoes > Jerseys and Team Sports": 3325,
    "Dog > Clothing and Shoes > Life Jackets and Swim Suits": 94,
    "Dog > Clothing and Shoes > Pajamas": 37,
    "Dog > Clothing and Shoes > Stress and Anxiety": 4,
    "Dog > Clothing and Shoes > Sweaters": 432,
    "Dog > Clothing and Shoes > T shirts and Tank Tops": 369,
    "Dog > Collars Harnesses and Leashes": 5482,
    "Dog > Collars Harnesses and Leashes > Collars": 1694,
    "Dog > Collars Harnesses and Leashes > Flea and Tick Collars": 23,
    "Dog > Collars Harnesses and Leashes > Harnesses": 2232,
    "Dog > Collars Harnesses and Leashes > Id Tags": 236,
    "Dog > Collars Harnesses and Leashes > Leashes": 1234,
    "Dog > Collars Harnesses and Leashes > Tie Outs": 42,
    "Dog > Collars Harnesses and Leashes > Training Collars Leashes and Harnesses": 214,
    "Dog > Crates Gates and Containment": 1454,
    "Dog > Crates Gates and Containment > Car Barriers": 50,
    "Dog > Crates Gates and Containment > Car Booster Seats": 155,
    "Dog > Crates Gates and Containment > Carriers and Backpacks": 242,
    "Dog > Crates Gates and Containment > Crates and Kennels": 311,
    "Dog > Crates Gates and Containment > Dog Doors and Gates": 178,
    "Dog > Crates Gates and Containment > Fence Systems": 46,
    "Dog > Crates Gates and Containment > Houses and Pens": 158,
    "Dog > Crates Gates and Containment > Mat and Crate Covers": 286,
    "Dog > Crates Gates and Containment > Strollers and Bicycle Baskets": 43,
    "Dog > Flea and Tick": 314,
    "Dog > Flea and Tick > Combs and Tools": 6,
    "Dog > Flea and Tick > Flea Shampoos and Dips": 19,
    "Dog > Flea and Tick > Flea and Tick Collars": 15,
    "Dog > Flea and Tick > Flea and Tick Pet Sprays": 26,
    "Dog > Flea and Tick > Flea and Tick Pills": 115,
    "Dog > Flea and Tick > Home and Yard Treatment": 20,
    "Dog > Flea and Tick > Spot Ons": 118,
    "Dog > Food": 2972,
    "Dog > Food > Canned Food": 738,
    "Dog > Food > Dry Food": 1794,
    "Dog > Food > Food Toppers": 256,
    "Dog > Food > Fresh and Frozen Food": 192,
    "Dog > Food > Fresh and Frozen Food > Fresh Food": 35,
    "Dog > Food > Fresh and Frozen Food > Frozen Food": 79,
    "Dog > Food > Milk Replacers": 2,
    "Dog > Food > Puppy Food": 319,
    "Dog > Food > Veterinary Diets": 246,
    "Dog > Grooming Supplies": 447,
    "Dog > Grooming Supplies > Brushes Combs and Blowdryers": 103,
    "Dog > Grooming Supplies > Eye Ear Nose and Paw Care": 26,
    "Dog > Grooming Supplies > Hair Clippers and Trimmers": 55,
    "Dog > Grooming Supplies > Nail Clippers and Grinders": 25,
    "Dog > Grooming Supplies > Shampoos and Conditioners": 137,
    "Dog > Grooming Supplies > Shower and Bathing Supplies": 21,
    "Dog > Grooming Supplies > Wipes and Deodorizers": 88,
    "Dog > Health and Wellness": 1293,
    "Dog > Health and Wellness > Anxiety and Calming Care": 87,
    "Dog > Health and Wellness > Dental and Breath Care": 258,
    "Dog > Health and Wellness > Dewormers": 55,
    "Dog > Health and Wellness > Diarrhea and Digestion Relief": 66,
    "Dog > Health and Wellness > Ear and Eye Care": 67,
    "Dog > Health and Wellness > First Aid and Recovery": 196,
    "Dog > Health and Wellness > Hot Spot and Itch Relief": 52,
    "Dog > Health and Wellness > Milk Replacers and Nursing Kits": 14,
    "Dog > Health and Wellness > Nose and Paw Care": 14,
    "Dog > Health and Wellness > Pill Administration": 20,
    "Dog > Health and Wellness > Test Kits": 5,
    "Dog > Health and Wellness > Vitamins and Supplements": 627,
    "Dog > Puppy Supplies": 6,
    "Dog > Toys": 2356,
    "Dog > Toys > Chew Toys": 388,
    "Dog > Toys > Fetch Toys": 272,
    "Dog > Toys > Interactive Toys": 258,
    "Dog > Toys > Plush Toys": 1332,
    "Dog > Toys > Rope and Tug Toys": 93,
    "Dog > Toys > Toy Storage": 22,
    "Dog > Training and Behavior": 437,
    "Dog > Training and Behavior > Bark Control": 23,
    "Dog > Training and Behavior > Cameras and Monitors": 9,
    "Dog > Training and Behavior > Clicker Training": 5,
    "Dog > Training and Behavior > Deterrents": 21,
    "Dog > Training and Behavior > Potty Training": 117,
    "Dog > Training and Behavior > Training Collars Leashes and Harnesses": 161,
    "Dog > Training and Behavior > Training Treats": 59,
    "Dog > Training and Behavior > Training and Behavior Accessories": 73,
    "Dog > Treats": 1132,
    "Dog > Treats > Birthday Cakes and Treats": 47,
    "Dog > Treats > Biscuits Cookies and Bakery Treats": 161,
    "Dog > Treats > Bones Bully Sticks and Chews": 431,
    "Dog > Treats > Dental Treats and Chews": 213,
    "Dog > Treats > Frozen Treats and Ice Cream": 12,
    "Dog > Treats > Jerky Treats": 67,
    "Dog > Treats > Puppy Treats": 90,
    "Dog > Treats > Soft and Chewy Treats": 168,
    "Dog > Treats > Training Treats": 110,
    "Dog > Vitamins and Supplements": 577,
    "Dog > Vitamins and Supplements > Anxiety and Calming": 80,
    "Dog > Vitamins and Supplements > Dietary Supplements": 19,
    "Dog > Vitamins and Supplements > Eye Care": 5,
    "Dog > Vitamins and Supplements > Heart and Liver": 22,
    "Dog > Vitamins and Supplements > Hip and Joint": 141,
    "Dog > Vitamins and Supplements > Immune System and Allergy": 85,
    "Dog > Vitamins and Supplements > Multivitamins": 80,
    "Dog > Vitamins and Supplements > Probiotic and Digestive": 96,
    "Dog > Vitamins and Supplements > Skin and Coat": 111,
    "Dog > Vitamins and Supplements > Stool Eating Deterrent": 6,
    "Dog > Vitamins and Supplements > Urinary and Kidney": 25,
    "Farm Animal": 258,
    "Farm Animal > Chicken and Poultry": 112,
    "Farm Animal > Chicken and Poultry > Accessories": 9,
    "Farm Animal > Chicken and Poultry > Care and Supplements": 12,
    "Farm Animal > Chicken and Poultry > Coops": 30,
    "Farm Animal > Chicken and Poultry > Feed": 60,
    "Farm Animal > Chicken and Poultry > Feeder and Waterers": 2,
    "Farm Animal > Chicken and Poultry > Nesting and Egg Supplies": 6,
    "Farm Animal > Cow": 4,
    "Farm Animal > Cow > DNU Care and Supplements": 1,
    "Farm Animal > Cow > Feed": 4,
    "Farm Animal > Duck": 36,
    "Farm Animal > Duck > Accessories": 2,
    "Farm Animal > Duck > Care and Supplements": 2,
    "Farm Animal > Duck > Feed": 23,
    "Farm Animal > Duck > Feeder and Waterers": 2,
    "Farm Animal > Duck > Hutches and Pens": 9,
    "Farm Animal > Goat": 10,
    "Farm Animal > Goat > Care and Supplements": 1,
    "Farm Animal > Goat > Feed": 10,
    "Farm Animal > Horse": 118,
    "Farm Animal > Horse > Care and Supplements": 81,
    "Farm Animal > Horse > Feed": 39,
    "Farm Animal > Pig": 14,
    "Farm Animal > Pig > Feed": 14,
    "Farm Animal > Sheep": 5,
    "Farm Animal > Sheep > Feed": 5,
    "Fish": 1977,
    "Fish > Decor Gravel and Substrate": 602,
    "Fish > Decor Gravel and Substrate > Aquarium Substrate": 69,
    "Fish > Decor Gravel and Substrate > Artificial Plants": 128,
    "Fish > Decor Gravel and Substrate > Backgrounds": 10,
    "Fish > Decor Gravel and Substrate > Gravel Sand and Stones": 94,
    "Fish > Decor Gravel and Substrate > Live Plants": 87,
    "Fish > Decor Gravel and Substrate > Ornaments": 302,
    "Fish > Decor Gravel and Substrate > Plant Food and Fertilizers": 11,
    "Fish > Filters and Pumps": 328,
    "Fish > Filters and Pumps > Air and Water Pumps": 63,
    "Fish > Filters and Pumps > Filter Media": 157,
    "Fish > Filters and Pumps > Filters": 89,
    "Fish > Filters and Pumps > Replacement Parts": 26,
    "Fish > Fish Shops": 1680,
    "Fish > Fish Shops > Betta": 766,
    "Fish > Fish Shops > Cichlid": 1115,
    "Fish > Fish Shops > Goldfish": 1144,
    "Fish > Fish Shops > Koi and Pond": 190,
    "Fish > Fish Shops > Live Plants": 82,
    "Fish > Fish Shops > Marine and Freshwater": 1403,
    "Fish > Food and Care": 488,
    "Fish > Food and Care > Disease Treatment": 16,
    "Fish > Food and Care > Feeders": 15,
    "Fish > Food and Care > Food": 194,
    "Fish > Food and Care > Plant Care": 17,
    "Fish > Food and Care > Pond Care": 70,
    "Fish > Food and Care > Salt Water Aquarium Care": 51,
    "Fish > Food and Care > Water Care and Conditioning": 122,
    "Fish > Food and Care > Water Quality Testers": 16,
    "Fish > Heating and Lighting": 121,
    "Fish > Heating and Lighting > Heaters": 33,
    "Fish > Heating and Lighting > Heating and Lighting Accessories": 8,
    "Fish > Heating and Lighting > Hoods and Glass Canopies": 18,
    "Fish > Heating and Lighting > Lights": 62,
    "Fish > Live Fish": 180,
    "Fish > Live Fish > Betta": 10,
    "Fish > Live Fish > Cichlid": 10,
    "Fish > Live Fish > Goldfish": 10,
    "Fish > Live Fish > Goldfish Betta and More": 180,
    "Fish > Live Fish > Koi and Pond": 4,
    "Fish > Live Fish > Marine and Freshwater": 104,
    "Fish > Live Fish > Shrimp": 1,
    "Fish > Maintenance and Repair": 34,
    "Fish > Maintenance and Repair > Adhesives and Sealants": 3,
    "Fish > Maintenance and Repair > Breeders and Nets": 6,
    "Fish > Maintenance and Repair > Brushes and Tank Cleaners": 14,
    "Fish > Maintenance and Repair > Vacuums": 10,
    "Fish > Maintenance and Repair > Water Changers": 2,
    "Fish > Starter Kits": 30,
    "Fish > Tanks Aquariums and Nets": 236,
    "Fish > Tanks Aquariums and Nets > Aquarium Stands": 60,
    "Fish > Tanks Aquariums and Nets > Aquariums": 173,
    "Fish > Tanks Aquariums and Nets > Tank Dividers and Containers": 4,
    "Reptile": 753,
    "Reptile > Cleaning and Water Care": 44,
    "Reptile > Cleaning and Water Care > Deodorizers": 4,
    "Reptile > Cleaning and Water Care > Filter Media": 7,
    "Reptile > Cleaning and Water Care > Filter Systems and Pumps": 14,
    "Reptile > Cleaning and Water Care > Sanitizers": 5,
    "Reptile > Cleaning and Water Care > Waste Removers": 5,
    "Reptile > Cleaning and Water Care > Water Conditioners": 11,
    "Reptile > Environmental Control and Lighting": 176,
    "Reptile > Environmental Control and Lighting > Bulbs and Lamps": 111,
    "Reptile > Environmental Control and Lighting > Heaters": 19,
    "Reptile > Environmental Control and Lighting > Humidity and Temperature Control": 22,
    "Reptile > Environmental Control and Lighting > Light Fixtures": 30,
    "Reptile > Feeders and Food Storage": 27,
    "Reptile > Feeders and Food Storage > Feeding Accessories": 12,
    "Reptile > Feeders and Food Storage > Food and Water Bowls": 15,
    "Reptile > Food": 194,
    "Reptile > Habitats and Decor": 201,
    "Reptile > Habitats and Decor > Habitat Accessories": 32,
    "Reptile > Habitats and Decor > Habitat Decor": 94,
    "Reptile > Habitats and Decor > Terrariums": 79,
    "Reptile > Live Reptiles": 29,
    "Reptile > Live Reptiles > Snakes Turtles and More": 29,
    "Reptile > Reptile Care Guides": 2,
    "Reptile > Reptile Shop": 626,
    "Reptile > Reptile Shop > Bearded Dragon": 331,
    "Reptile > Reptile Shop > Bearded Dragon > Cleaning and Care": 13,
    "Reptile > Reptile Shop > Bearded Dragon > Food": 50,
    "Reptile > Reptile Shop > Bearded Dragon > Habitats and Decor": 44,
    "Reptile > Reptile Shop > Bearded Dragon > Heating and Lighting": 66,
    "Reptile > Reptile Shop > Bearded Dragon > Substrate and Bedding": 12,
    "Reptile > Reptile Shop > Chameleon": 328,
    "Reptile > Reptile Shop > Chameleon > Cleaning and Care": 22,
    "Reptile > Reptile Shop > Chameleon > Food": 27,
    "Reptile > Reptile Shop > Chameleon > Habitats and Decor": 49,
    "Reptile > Reptile Shop > Chameleon > Heating and Lighting": 86,
    "Reptile > Reptile Shop > Chameleon > Substrate and Bedding": 22,
    "Reptile > Reptile Shop > Frog": 373,
    "Reptile > Reptile Shop > Frog > Cleaning and Care": 17,
    "Reptile > Reptile Shop > Frog > Food": 21,
    "Reptile > Reptile Shop > Frog > Habitats and Decor": 39,
    "Reptile > Reptile Shop > Frog > Heating and Lighting": 77,
    "Reptile > Reptile Shop > Frog > Substrate and Bedding": 27,
    "Reptile > Reptile Shop > Gecko and Lizard": 424,
    "Reptile > Reptile Shop > Gecko and Lizard > Cleaning and Care": 16,
    "Reptile > Reptile Shop > Gecko and Lizard > Food": 33,
    "Reptile > Reptile Shop > Gecko and Lizard > Habitats and Decor": 54,
    "Reptile > Reptile Shop > Gecko and Lizard > Heating and Lighting": 87,
    "Reptile > Reptile Shop > Gecko and Lizard > Substrate and Bedding": 31,
    "Reptile > Reptile Shop > Hermit Crab": 301,
    "Reptile > Reptile Shop > Hermit Crab > Cleaning and Care": 16,
    "Reptile > Reptile Shop > Hermit Crab > Food": 7,
    "Reptile > Reptile Shop > Hermit Crab > Habitats and Decor": 37,
    "Reptile > Reptile Shop > Hermit Crab > Heating and Lighting": 58,
    "Reptile > Reptile Shop > Hermit Crab > Substrate and Bedding": 11,
    "Reptile > Reptile Shop > Snake": 349,
    "Reptile > Reptile Shop > Snake > Cleaning and Care": 10,
    "Reptile > Reptile Shop > Snake > Food": 2,
    "Reptile > Reptile Shop > Snake > Habitats and Decor": 30,
    "Reptile > Reptile Shop > Snake > Heating and Lighting": 60,
    "Reptile > Reptile Shop > Snake > Substrate and Bedding": 23,
    "Reptile > Reptile Shop > Spiders and More": 287,
    "Reptile > Reptile Shop > Turtle": 391,
    "Reptile > Reptile Shop > Turtle > Cleaning and Care": 28,
    "Reptile > Reptile Shop > Turtle > Food": 58,
    "Reptile > Reptile Shop > Turtle > Habitats and Decor": 33,
    "Reptile > Reptile Shop > Turtle > Heating and Lighting": 78,
    "Reptile > Reptile Shop > Turtle > Substrate and Bedding": 23,
    "Reptile > Starter Kits": 25,
    "Reptile > Substrate and Bedding": 51,
    "Reptile > Vitamins and Supplements": 20,
    "Small Pet": 758,
    "Small Pet > Cages Habitats and Hutches": 138,
    "Small Pet > Cages Habitats and Hutches > Cages": 76,
    "Small Pet > Cages Habitats and Hutches > Habitat Expansions": 5,
    "Small Pet > Cages Habitats and Hutches > Play Pens": 12,
    "Small Pet > Cages Habitats and Hutches > Tunnels and Hideouts": 17,
    "Small Pet > Cages Habitats and Hutches > cusches": 30,
    "Small Pet > Cleaning and Odor Removers": 5,
    "Small Pet > Cleaning and Odor Removers > Brushes and Scrubbers": 1,
    "Small Pet > Cleaning and Odor Removers > Deodorizers": 3,
    "Small Pet > Cleaning and Odor Removers > Sanitizers": 1,
    "Small Pet > Food Treats and Hay": 277,
    "Small Pet > Food Treats and Hay > Food": 128,
    "Small Pet > Food Treats and Hay > Hay": 72,
    "Small Pet > Food Treats and Hay > Treats": 80,
    "Small Pet > Harnesses and Travel Carriers": 5,
    "Small Pet > Harnesses and Travel Carriers > Harnesses": 2,
    "Small Pet > Harnesses and Travel Carriers > Travel Carriers": 3,
    "Small Pet > Health and Grooming": 49,
    "Small Pet > Health and Grooming > Grooming Supplies": 18,
    "Small Pet > Health and Grooming > Vitamins and Supplements": 32,
    "Small Pet > Litter and Bedding": 90,
    "Small Pet > Litter and Bedding > Litter Pans": 11,
    "Small Pet > Litter and Bedding > Litter and Bedding": 79,
    "Small Pet > Live Small Pets": 28,
    "Small Pet > Live Small Pets > Hamsters Guinea Pigs and More": 28,
    "Small Pet > Small Pet Shops": 557,
    "Small Pet > Small Pet Shops > Chinchilla": 280,
    "Small Pet > Small Pet Shops > Ferret": 146,
    "Small Pet > Small Pet Shops > Guinea Pig": 340,
    "Small Pet > Small Pet Shops > Hamster and Gerbil": 276,
    "Small Pet > Small Pet Shops > Hedgehog and Sugar Glider": 211,
    "Small Pet > Small Pet Shops > Rabbit": 353,
    "Small Pet > Small Pet Shops > Rat and Mouse": 252,
    "Small Pet > Toys and Habitat Accessories": 182,
    "Small Pet > Toys and Habitat Accessories > Feeders and Water Bottles": 45,
    "Small Pet > Toys and Habitat Accessories > Small Pet Costumes": 11,
    "Small Pet > Toys and Habitat Accessories > Toys": 91,
    "Small Pet > Toys and Habitat Accessories > Tunnels and Hideouts": 37,
}

# Facet paths whose PLP route redirects elsewhere on the live storefront
# (verified 2026-10-04). Without these the inventory would ship 301/307 URLs.
CANONICAL_URL_OVERRIDES: dict[str, str] = {
    "Bird > Bird Shops > Chicken": "https://www.petsmart.com/farm-animal/chicken-and-poultry/",
    "Bird > Wild Bird Food and Supplies": "https://www.petsmart.com/bird/bird-shops/wild-bird",
    "Bird > Wild Bird Food and Supplies > Coops and Outdoor Habitats": (
        "https://www.petsmart.com/farm-animal/chicken-and-poultry/coops"
    ),
    "Bird > Wild Bird Food and Supplies > Outdoor Bird Baths": (
        "https://www.petsmart.com/bird/bird-shops/wild-bird"
    ),
    "Bird > Wild Bird Food and Supplies > Wild Bird Food": (
        "https://www.petsmart.com/bird/food-and-treats/wild-bird-food"
    ),
    "Bird > Wild Bird Food and Supplies > Outdoor Feeders": (
        "https://www.petsmart.com/bird/bird-shops/wild-bird/feeders-and-waterers"
    ),
    "Cat > Health and Wellness > Hairball Remedy": (
        "https://www.petsmart.com/cat/vitamins-and-supplements/hairball-control/"
    ),
    "Cat > Health and Wellness > Vitamins and Supplements": (
        "https://www.petsmart.com/cat/vitamins-and-supplements/"
    ),
    "Cat > Toys > Balls and Chasers": "https://www.petsmart.com/cat/toys/plush-balls-and-mice/",
    "Cat > Toys > Hunting and Stalking Toys": "https://www.petsmart.com/cat",
    "Cat > Toys > Multi Pack": "https://www.petsmart.com/cat/toys/",
    "Dog > Collars Harnesses and Leashes > Flea and Tick Collars": (
        "https://www.petsmart.com/dog/flea-and-tick/flea-and-tick-collars/"
    ),
    "Dog > Health and Wellness > Vitamins and Supplements": (
        "https://www.petsmart.com/dog/vitamins-and-supplements/"
    ),
    "Dog > Training and Behavior > Training Collars Leashes and Harnesses": (
        "https://www.petsmart.com/dog/collars-harnesses-and-leashes/"
        "training-collars-leashes-and-harnesses/"
    ),
    "Dog > Training and Behavior > Training Treats": (
        "https://www.petsmart.com/dog/treats/training-treats/"
    ),
}

_SEGMENT_RE = re.compile(r"[^a-z0-9]+")
SITE_BASE = "https://www.petsmart.com"


def _segment_slug(segment: str) -> str:
    """Slug one API path segment the way the storefront builds PLP routes."""
    return _SEGMENT_RE.sub("-", segment.replace("&", " and ").lower()).strip("-")


def category_slug(path: str) -> str:
    """``"Dog > Food > Dry Food"`` -> ``"dog/food/dry-food"``."""
    return "/".join(_segment_slug(part) for part in path.split(" > "))


def category_url(path: str) -> str:
    """Absolute storefront PLP URL for an API category path."""
    if path in CANONICAL_URL_OVERRIDES:
        return CANONICAL_URL_OVERRIDES[path]
    return f"{SITE_BASE}/{category_slug(path)}/"


def _flatten_categories() -> list[dict[str, object]]:
    categories: list[dict[str, object]] = []
    for path, item_count in sorted(
        PETSMART_CATEGORY_COUNTS.items(), key=lambda entry: tuple(entry[0].split(" > "))
    ):
        parts = path.split(" > ")
        department = parts[0]
        categories.append(
            {
                "category": category_slug(path),
                "department": department,
                "subcategory": " > ".join(parts[1:-1]) or None,
                "name": path,
                "item_count": item_count,
                "url": category_url(path),
            }
        )
    return categories


PETSMART_CATEGORIES = _flatten_categories()
