"""shopbop.com category inventory extracted from the `__shopbop_sca_hydrate__` navigation payload.

Source: https://www.shopbop.com/
Extracted: `dehydratedState.frameworkState.dd.renderTree.topLevelSlots["top-nav-1"]
            -> content.slotConfiguration.squareState.props.unfilteredNavigationData
            -> navigationCategoryGroupList`
Captured: 2026-10-05 (US / en-US).

The homepage hydration carries the complete desktop navigation as 3 department groups
(Women / Men / Beauty) -> 20 primary categories -> 311 nested section/item link entries
(8 sections carry their own product link, 307 are third-level item links), which is
**335 link nodes** in total.

Nodes are filtered down as follows:

* **20 nodes carry no `folderId`** and so are not category listings -- 11 editorial
  destinations (`/ci/...`), the designer index (`/designers` and `/designers?bu=sbm`,
  6 nodes), one hand-curated product page
  (`/seduce-plunge-bra-fleur-du/vp/v=1/1508663349.htm`), the gift card page (`/giftcard`)
  and the `/shop-men` landing page. `/designers` and `/shop-men` do return a document, but
  as `pageType="Designer"` / `pageType="MensLandingPage"` with **no** `products` React Query
  at all, so they can never yield items.
* **49 nodes repeat a URL that already appears at a shallower level** (34 distinct
  duplicate URLs). The storefront repeats each primary category link as its own section
  link and again as an `All <Category>` item link -- `/whats-new/br/v=1/13198.htm` appears
  three times. The **shallowest** node wins, so a category keeps its primary-catalog
  placement rather than an editorial cross-reference.

That leaves **315 product-bearing nodes -> 266 unique category URLs**
(Women 183, Men 70, Beauty 13). Every URL below carries a `folderId`, which is the
authoritative storefront category id and is what the PLP hydration reports back as
`folderId` (and as `queryKey[1].categoryId` in the products query).

Two normalisations are applied to the storefront's own titles: runs of whitespace are
collapsed and the result is stripped (several labels ship as `"Accessories "`), and 27
sections that carry an empty `title` -- the storefront's `imageSection` blocks -- are
omitted from the path rather than emitted as a blank segment.
"""

from __future__ import annotations


BASE_URL = "https://www.shopbop.com"


SHOPBOP_CATEGORIES = {
    "Women": {
        "Women > Active": {
            "department": "Women",
            "subcategory": "Active",
            "leaf": None,
            "folder_id": "65739",
            "url": "https://www.shopbop.com/sports/br/v=1/65739.htm",
            "category": "Women > Active",
        },
        "Women > Active > All Clothing": {
            "department": "Women",
            "subcategory": "Active",
            "leaf": "All Clothing",
            "folder_id": "65743",
            "url": "https://www.shopbop.com/sports-clothing/br/v=1/65743.htm",
            "category": "Women > Active > All Clothing",
        },
        "Women > Active > Bags & Accessories": {
            "department": "Women",
            "subcategory": "Active",
            "leaf": "Bags & Accessories",
            "folder_id": "80897",
            "url": "https://www.shopbop.com/sports-bags-accessories/br/v=1/80897.htm",
            "category": "Women > Active > Bags & Accessories",
        },
        "Women > Active > Cardio & Running": {
            "department": "Women",
            "subcategory": "Active",
            "leaf": "Cardio & Running",
            "folder_id": "74287",
            "url": "https://www.shopbop.com/sports-cardio-running/br/v=1/74287.htm",
            "category": "Women > Active > Cardio & Running",
        },
        "Women > Active > Dresses & Jumpsuits": {
            "department": "Women",
            "subcategory": "Active",
            "leaf": "Dresses & Jumpsuits",
            "folder_id": "68848",
            "url": "https://www.shopbop.com/sports-clothing-dresses-jumpsuits/br/v=1/68848.htm",
            "category": "Women > Active > Dresses & Jumpsuits",
        },
        "Women > Active > Golf": {
            "department": "Women",
            "subcategory": "Active",
            "leaf": "Golf",
            "folder_id": "74632",
            "url": "https://www.shopbop.com/sports-golf/br/v=1/74632.htm",
            "category": "Women > Active > Golf",
        },
        "Women > Active > Leggings": {
            "department": "Women",
            "subcategory": "Active",
            "leaf": "Leggings",
            "folder_id": "65749",
            "url": "https://www.shopbop.com/sports-clothing-leggings/br/v=1/65749.htm",
            "category": "Women > Active > Leggings",
        },
        "Women > Active > Matching Sets": {
            "department": "Women",
            "subcategory": "Active",
            "leaf": "Matching Sets",
            "folder_id": "65748",
            "url": "https://www.shopbop.com/sports-clothing-matching-sets/br/v=1/65748.htm",
            "category": "Women > Active > Matching Sets",
        },
        "Women > Active > Pants & Sweatpants": {
            "department": "Women",
            "subcategory": "Active",
            "leaf": "Pants & Sweatpants",
            "folder_id": "65745",
            "url": "https://www.shopbop.com/sports-clothing-sweatpants/br/v=1/65745.htm",
            "category": "Women > Active > Pants & Sweatpants",
        },
        "Women > Active > Shoes": {
            "department": "Women",
            "subcategory": "Active",
            "leaf": "Shoes",
            "folder_id": "65740",
            "url": "https://www.shopbop.com/sports-sneakers/br/v=1/65740.htm",
            "category": "Women > Active > Shoes",
        },
        "Women > Active > Shorts & Skirts": {
            "department": "Women",
            "subcategory": "Active",
            "leaf": "Shorts & Skirts",
            "folder_id": "65919",
            "url": "https://www.shopbop.com/sports-clothing-shorts-skirts/br/v=1/65919.htm",
            "category": "Women > Active > Shorts & Skirts",
        },
        "Women > Active > Sports Bras": {
            "department": "Women",
            "subcategory": "Active",
            "leaf": "Sports Bras",
            "folder_id": "65747",
            "url": "https://www.shopbop.com/sports-clothing-sports-bras/br/v=1/65747.htm",
            "category": "Women > Active > Sports Bras",
        },
        "Women > Active > Sweatshirts & Jackets": {
            "department": "Women",
            "subcategory": "Active",
            "leaf": "Sweatshirts & Jackets",
            "folder_id": "68288",
            "url": "https://www.shopbop.com/sports-clothing-sweatshirts-jackets/br/v=1/68288.htm",
            "category": "Women > Active > Sweatshirts & Jackets",
        },
        "Women > Active > Tennis & Pickleball": {
            "department": "Women",
            "subcategory": "Active",
            "leaf": "Tennis & Pickleball",
            "folder_id": "68613",
            "url": "https://www.shopbop.com/sports-tennis-pickleball/br/v=1/68613.htm",
            "category": "Women > Active > Tennis & Pickleball",
        },
        "Women > Active > Tops": {
            "department": "Women",
            "subcategory": "Active",
            "leaf": "Tops",
            "folder_id": "65744",
            "url": "https://www.shopbop.com/sports-clothing-tops/br/v=1/65744.htm",
            "category": "Women > Active > Tops",
        },
        "Women > Active > Yoga & Pilates": {
            "department": "Women",
            "subcategory": "Active",
            "leaf": "Yoga & Pilates",
            "folder_id": "65797",
            "url": "https://www.shopbop.com/sports-yoga-pilates/br/v=1/65797.htm",
            "category": "Women > Active > Yoga & Pilates",
        },
        "Women > Bags": {
            "department": "Women",
            "subcategory": "Bags",
            "leaf": None,
            "folder_id": "13505",
            "url": "https://www.shopbop.com/bags/br/v=1/13505.htm",
            "category": "Women > Bags",
        },
        "Women > Bags > Backpacks": {
            "department": "Women",
            "subcategory": "Bags",
            "leaf": "Backpacks",
            "folder_id": "13512",
            "url": "https://www.shopbop.com/bags-backpacks/br/v=1/13512.htm",
            "category": "Women > Bags > Backpacks",
        },
        "Women > Bags > Beach & Straw Bags": {
            "department": "Women",
            "subcategory": "Bags",
            "leaf": "Beach & Straw Bags",
            "folder_id": "13521",
            "url": "https://www.shopbop.com/bags-beach-straw/br/v=1/13521.htm",
            "category": "Women > Bags > Beach & Straw Bags",
        },
        "Women > Bags > Bucket Bags": {
            "department": "Women",
            "subcategory": "Bags",
            "leaf": "Bucket Bags",
            "folder_id": "36613",
            "url": "https://www.shopbop.com/bags-bucket/br/v=1/36613.htm",
            "category": "Women > Bags > Bucket Bags",
        },
        "Women > Bags > Clutches": {
            "department": "Women",
            "subcategory": "Bags",
            "leaf": "Clutches",
            "folder_id": "13511",
            "url": "https://www.shopbop.com/bags-clutches/br/v=1/13511.htm",
            "category": "Women > Bags > Clutches",
        },
        "Women > Bags > Cross Body Bags": {
            "department": "Women",
            "subcategory": "Bags",
            "leaf": "Cross Body Bags",
            "folder_id": "13513",
            "url": "https://www.shopbop.com/bags-cross-body/br/v=1/13513.htm",
            "category": "Women > Bags > Cross Body Bags",
        },
        "Women > Bags > Evening Edit": {
            "department": "Women",
            "subcategory": "Bags",
            "leaf": "Evening Edit",
            "folder_id": "80505",
            "url": "https://www.shopbop.com/bags-evening-edit/br/v=1/80505.htm",
            "category": "Women > Bags > Evening Edit",
        },
        "Women > Bags > Luggage & Weekenders": {
            "department": "Women",
            "subcategory": "Bags",
            "leaf": "Luggage & Weekenders",
            "folder_id": "13506",
            "url": "https://www.shopbop.com/bags-luggage-weekenders/br/v=1/13506.htm",
            "category": "Women > Bags > Luggage & Weekenders",
        },
        "Women > Bags > Mini Bags": {
            "department": "Women",
            "subcategory": "Bags",
            "leaf": "Mini Bags",
            "folder_id": "59452",
            "url": "https://www.shopbop.com/bags-mini/br/v=1/59452.htm",
            "category": "Women > Bags > Mini Bags",
        },
        "Women > Bags > Office-Bound Totes": {
            "department": "Women",
            "subcategory": "Bags",
            "leaf": "Office-Bound Totes",
            "folder_id": "80875",
            "url": "https://www.shopbop.com/bags-office-bound-totes/br/v=1/80875.htm",
            "category": "Women > Bags > Office-Bound Totes",
        },
        "Women > Bags > Pre-Owned Bags": {
            "department": "Women",
            "subcategory": "Bags",
            "leaf": "Pre-Owned Bags",
            "folder_id": "63752",
            "url": "https://www.shopbop.com/bags-pre-owned-bags/br/v=1/63752.htm",
            "category": "Women > Bags > Pre-Owned Bags",
        },
        "Women > Bags > Shoulder Bags": {
            "department": "Women",
            "subcategory": "Bags",
            "leaf": "Shoulder Bags",
            "folder_id": "13509",
            "url": "https://www.shopbop.com/bags-shoulder/br/v=1/13509.htm",
            "category": "Women > Bags > Shoulder Bags",
        },
        "Women > Bags > Sleek Bags: Nili Lotan": {
            "department": "Women",
            "subcategory": "Bags",
            "leaf": "Sleek Bags: Nili Lotan",
            "folder_id": "78164",
            "url": "https://www.shopbop.com/nili-lotan-bags/br/v=1/78164.htm",
            "category": "Women > Bags > Sleek Bags: Nili Lotan",
        },
        "Women > Bags > Sling & Belt Bags": {
            "department": "Women",
            "subcategory": "Bags",
            "leaf": "Sling & Belt Bags",
            "folder_id": "56475",
            "url": "https://www.shopbop.com/bags-belt/br/v=1/56475.htm",
            "category": "Women > Bags > Sling & Belt Bags",
        },
        "Women > Bags > Top Handle Bags": {
            "department": "Women",
            "subcategory": "Bags",
            "leaf": "Top Handle Bags",
            "folder_id": "13524",
            "url": "https://www.shopbop.com/bags-satchels-top-handles/br/v=1/13524.htm",
            "category": "Women > Bags > Top Handle Bags",
        },
        "Women > Bags > Totes": {
            "department": "Women",
            "subcategory": "Bags",
            "leaf": "Totes",
            "folder_id": "13507",
            "url": "https://www.shopbop.com/bags-totes/br/v=1/13507.htm",
            "category": "Women > Bags > Totes",
        },
        "Women > Bags > Travel Bag Edit": {
            "department": "Women",
            "subcategory": "Bags",
            "leaf": "Travel Bag Edit",
            "folder_id": "79360",
            "url": "https://www.shopbop.com/bags-travel-bag-edit/br/v=1/79360.htm",
            "category": "Women > Bags > Travel Bag Edit",
        },
        "Women > Bags > Wallets & Card Holders": {
            "department": "Women",
            "subcategory": "Bags",
            "leaf": "Wallets & Card Holders",
            "folder_id": "13514",
            "url": "https://www.shopbop.com/bags-wallets-card-holders/br/v=1/13514.htm",
            "category": "Women > Bags > Wallets & Card Holders",
        },
        "Women > Clothing": {
            "department": "Women",
            "subcategory": "Clothing",
            "leaf": None,
            "folder_id": "13266",
            "url": "https://www.shopbop.com/clothing/br/v=1/13266.htm",
            "category": "Women > Clothing",
        },
        "Women > Clothing > AGOLDE": {
            "department": "Women",
            "subcategory": "Clothing",
            "leaf": "AGOLDE",
            "folder_id": "22839",
            "url": "https://www.shopbop.com/agolde/br/v=1/22839.htm",
            "category": "Women > Clothing > AGOLDE",
        },
        "Women > Clothing > Activewear": {
            "department": "Women",
            "subcategory": "Clothing",
            "leaf": "Activewear",
            "folder_id": "74367",
            "url": "https://www.shopbop.com/clothing-activewear/br/v=1/74367.htm",
            "category": "Women > Clothing > Activewear",
        },
        "Women > Clothing > Dark Wash Denim": {
            "department": "Women",
            "subcategory": "Clothing",
            "leaf": "Dark Wash Denim",
            "folder_id": "80707",
            "url": "https://www.shopbop.com/our-favorites-fall-trend-edit-trend-4/br/v=1/80707.htm",
            "category": "Women > Clothing > Dark Wash Denim",
        },
        "Women > Clothing > Heritage Prints": {
            "department": "Women",
            "subcategory": "Clothing",
            "leaf": "Heritage Prints",
            "folder_id": "80709",
            "url": "https://www.shopbop.com/our-favorites-fall-trend-edit-trend-2/br/v=1/80709.htm",
            "category": "Women > Clothing > Heritage Prints",
        },
        "Women > Clothing > Hill House Home": {
            "department": "Women",
            "subcategory": "Clothing",
            "leaf": "Hill House Home",
            "folder_id": "72010",
            "url": "https://www.shopbop.com/hill-house-home/br/v=1/72010.htm",
            "category": "Women > Clothing > Hill House Home",
        },
        "Women > Clothing > Jackets & Coats": {
            "department": "Women",
            "subcategory": "Clothing",
            "leaf": "Jackets & Coats",
            "folder_id": "13414",
            "url": "https://www.shopbop.com/clothing-jackets-coats/br/v=1/13414.htm",
            "category": "Women > Clothing > Jackets & Coats",
        },
        "Women > Clothing > Jeans": {
            "department": "Women",
            "subcategory": "Clothing",
            "leaf": "Jeans",
            "folder_id": "13377",
            "url": "https://www.shopbop.com/clothing-jeans/br/v=1/13377.htm",
            "category": "Women > Clothing > Jeans",
        },
        "Women > Clothing > Jumpsuits & Rompers": {
            "department": "Women",
            "subcategory": "Clothing",
            "leaf": "Jumpsuits & Rompers",
            "folder_id": "13267",
            "url": "https://www.shopbop.com/clothing-jumpsuits-rompers/br/v=1/13267.htm",
            "category": "Women > Clothing > Jumpsuits & Rompers",
        },
        "Women > Clothing > Lingerie & Sleepwear": {
            "department": "Women",
            "subcategory": "Clothing",
            "leaf": "Lingerie & Sleepwear",
            "folder_id": "13269",
            "url": "https://www.shopbop.com/clothing-lingerie/br/v=1/13269.htm",
            "category": "Women > Clothing > Lingerie & Sleepwear",
        },
        "Women > Clothing > Lioness": {
            "department": "Women",
            "subcategory": "Clothing",
            "leaf": "Lioness",
            "folder_id": "48343",
            "url": "https://www.shopbop.com/lioness/br/v=1/48343.htm",
            "category": "Women > Clothing > Lioness",
        },
        "Women > Clothing > MOTHER": {
            "department": "Women",
            "subcategory": "Clothing",
            "leaf": "MOTHER",
            "folder_id": "10959",
            "url": "https://www.shopbop.com/mother/br/v=1/10959.htm",
            "category": "Women > Clothing > MOTHER",
        },
        "Women > Clothing > Matching Sets": {
            "department": "Women",
            "subcategory": "Clothing",
            "leaf": "Matching Sets",
            "folder_id": "13346",
            "url": "https://www.shopbop.com/clothing-matching-sets/br/v=1/13346.htm",
            "category": "Women > Clothing > Matching Sets",
        },
        "Women > Clothing > Maternity": {
            "department": "Women",
            "subcategory": "Clothing",
            "leaf": "Maternity",
            "folder_id": "13435",
            "url": "https://www.shopbop.com/clothing-maternity/br/v=1/13435.htm",
            "category": "Women > Clothing > Maternity",
        },
        "Women > Clothing > Pants": {
            "department": "Women",
            "subcategory": "Clothing",
            "leaf": "Pants",
            "folder_id": "13281",
            "url": "https://www.shopbop.com/clothing-pants/br/v=1/13281.htm",
            "category": "Women > Clothing > Pants",
        },
        "Women > Clothing > Plum Crush": {
            "department": "Women",
            "subcategory": "Clothing",
            "leaf": "Plum Crush",
            "folder_id": "80710",
            "url": "https://www.shopbop.com/our-favorites-fall-trend-edit-trend-1/br/v=1/80710.htm",
            "category": "Women > Clothing > Plum Crush",
        },
        "Women > Clothing > Shorts": {
            "department": "Women",
            "subcategory": "Clothing",
            "leaf": "Shorts",
            "folder_id": "13297",
            "url": "https://www.shopbop.com/clothing-shorts/br/v=1/13297.htm",
            "category": "Women > Clothing > Shorts",
        },
        "Women > Clothing > Skirts": {
            "department": "Women",
            "subcategory": "Clothing",
            "leaf": "Skirts",
            "folder_id": "13302",
            "url": "https://www.shopbop.com/clothing-skirts/br/v=1/13302.htm",
            "category": "Women > Clothing > Skirts",
        },
        "Women > Clothing > Standout Coats": {
            "department": "Women",
            "subcategory": "Clothing",
            "leaf": "Standout Coats",
            "folder_id": "80708",
            "url": "https://www.shopbop.com/our-favorites-fall-trend-edit-trend-3/br/v=1/80708.htm",
            "category": "Women > Clothing > Standout Coats",
        },
        "Women > Clothing > State & Lake": {
            "department": "Women",
            "subcategory": "Clothing",
            "leaf": "State & Lake",
            "folder_id": "77193",
            "url": "https://www.shopbop.com/state-lake/br/v=1/77193.htm",
            "category": "Women > Clothing > State & Lake",
        },
        "Women > Clothing > Sweaters & Knits": {
            "department": "Women",
            "subcategory": "Clothing",
            "leaf": "Sweaters & Knits",
            "folder_id": "13317",
            "url": "https://www.shopbop.com/clothing-sweaters-knits/br/v=1/13317.htm",
            "category": "Women > Clothing > Sweaters & Knits",
        },
        "Women > Clothing > Sweatshirts": {
            "department": "Women",
            "subcategory": "Clothing",
            "leaf": "Sweatshirts",
            "folder_id": "13332",
            "url": "https://www.shopbop.com/clothing-tops/br/v=1/13332.htm?f=MATopsStyle-Sweatshirt",
            "category": "Women > Clothing > Sweatshirts",
        },
        "Women > Clothing > Swimsuits & Cover-Ups": {
            "department": "Women",
            "subcategory": "Clothing",
            "leaf": "Swimsuits & Cover-Ups",
            "folder_id": "13311",
            "url": "https://www.shopbop.com/clothing-swimsuits-cover-ups/br/v=1/13311.htm",
            "category": "Women > Clothing > Swimsuits & Cover-Ups",
        },
        "Women > Clothing > Tops": {
            "department": "Women",
            "subcategory": "Clothing",
            "leaf": "Tops",
            "folder_id": "13332",
            "url": "https://www.shopbop.com/clothing-tops/br/v=1/13332.htm",
            "category": "Women > Clothing > Tops",
        },
        "Women > Clothing > Turn Heads: Runaway the Label": {
            "department": "Women",
            "subcategory": "Clothing",
            "leaf": "Turn Heads: Runaway the Label",
            "folder_id": "74009",
            "url": "https://www.shopbop.com/runaway-label/br/v=1/74009.htm",
            "category": "Women > Clothing > Turn Heads: Runaway the Label",
        },
        "Women > Designers > Asian & Pacific Islander-Led Brands": {
            "department": "Women",
            "subcategory": "Designers",
            "leaf": "Asian & Pacific Islander-Led Brands",
            "folder_id": "66797",
            "url": "https://www.shopbop.com/our-favorites-aapi-designers-owned-brands/br/v=1/66797.htm",
            "category": "Women > Designers > Asian & Pacific Islander-Led Brands",
        },
        "Women > Designers > Black-Led Brands": {
            "department": "Women",
            "subcategory": "Designers",
            "leaf": "Black-Led Brands",
            "folder_id": "66379",
            "url": "https://www.shopbop.com/our-favorites-black-designers-owned-brands/br/v=1/66379.htm",
            "category": "Women > Designers > Black-Led Brands",
        },
        "Women > Designers > Coach": {
            "department": "Women",
            "subcategory": "Designers",
            "leaf": "Coach",
            "folder_id": "52828",
            "url": "https://www.shopbop.com/coach-1941/br/v=1/52828.htm",
            "category": "Women > Designers > Coach",
        },
        "Women > Designers > Cool Classics: Madewell": {
            "department": "Women",
            "subcategory": "Designers",
            "leaf": "Cool Classics: Madewell",
            "folder_id": "7425",
            "url": "https://www.shopbop.com/madewell/br/v=1/7425.htm",
            "category": "Women > Designers > Cool Classics: Madewell",
        },
        "Women > Designers > Designer Exclusives": {
            "department": "Women",
            "subcategory": "Designers",
            "leaf": "Designer Exclusives",
            "folder_id": "13049",
            "url": "https://www.shopbop.com/exclusives/br/v=1/13049.htm",
            "category": "Women > Designers > Designer Exclusives",
        },
        "Women > Designers > It Knits: Jenni Kayne": {
            "department": "Women",
            "subcategory": "Designers",
            "leaf": "It Knits: Jenni Kayne",
            "folder_id": "71656",
            "url": "https://www.shopbop.com/jenni-kayne/br/v=1/71656.htm",
            "category": "Women > Designers > It Knits: Jenni Kayne",
        },
        "Women > Designers > Reformation": {
            "department": "Women",
            "subcategory": "Designers",
            "leaf": "Reformation",
            "folder_id": "9940",
            "url": "https://www.shopbop.com/reformation/br/v=1/9940.htm",
            "category": "Women > Designers > Reformation",
        },
        "Women > Designers > STAUD": {
            "department": "Women",
            "subcategory": "Designers",
            "leaf": "STAUD",
            "folder_id": "53407",
            "url": "https://www.shopbop.com/staud/br/v=1/53407.htm",
            "category": "Women > Designers > STAUD",
        },
        "Women > Designers > Stripe & Stare": {
            "department": "Women",
            "subcategory": "Designers",
            "leaf": "Stripe & Stare",
            "folder_id": "57570",
            "url": "https://www.shopbop.com/stripe-stare/br/v=1/57570.htm",
            "category": "Women > Designers > Stripe & Stare",
        },
        "Women > Dresses": {
            "department": "Women",
            "subcategory": "Dresses",
            "leaf": None,
            "folder_id": "13351",
            "url": "https://www.shopbop.com/clothing-dresses/br/v=1/13351.htm",
            "category": "Women > Dresses",
        },
        "Women > Dresses > Casual & Everyday": {
            "department": "Women",
            "subcategory": "Dresses",
            "leaf": "Casual & Everyday",
            "folder_id": "13351",
            "url": "https://www.shopbop.com/clothing-dresses/br/v=1/13351.htm?f=MADressOccasion-Casual+%26+Everyday",
            "category": "Women > Dresses > Casual & Everyday",
        },
        "Women > Dresses > Denim Dresses": {
            "department": "Women",
            "subcategory": "Dresses",
            "leaf": "Denim Dresses",
            "folder_id": "72240",
            "url": "https://www.shopbop.com/special-denim-dresses/br/v=1/72240.htm",
            "category": "Women > Dresses > Denim Dresses",
        },
        "Women > Dresses > Event": {
            "department": "Women",
            "subcategory": "Dresses",
            "leaf": "Event",
            "folder_id": "13351",
            "url": "https://www.shopbop.com/clothing-dresses/br/v=1/13351.htm?f=MADressOccasion-Event",
            "category": "Women > Dresses > Event",
        },
        "Women > Dresses > Knee-Length": {
            "department": "Women",
            "subcategory": "Dresses",
            "leaf": "Knee-Length",
            "folder_id": "13351",
            "url": "https://www.shopbop.com/clothing-dresses/br/v=1/13351.htm?f=MADressLength-Knee-Length",
            "category": "Women > Dresses > Knee-Length",
        },
        "Women > Dresses > Knit Dresses": {
            "department": "Women",
            "subcategory": "Dresses",
            "leaf": "Knit Dresses",
            "folder_id": "13351",
            "url": "https://www.shopbop.com/clothing-dresses/br/v=1/13351.htm?f=MADressStyle-Knit",
            "category": "Women > Dresses > Knit Dresses",
        },
        "Women > Dresses > Maxi": {
            "department": "Women",
            "subcategory": "Dresses",
            "leaf": "Maxi",
            "folder_id": "13351",
            "url": "https://www.shopbop.com/clothing-dresses/br/v=1/13351.htm?f=MADressLength-Maxi",
            "category": "Women > Dresses > Maxi",
        },
        "Women > Dresses > Midi": {
            "department": "Women",
            "subcategory": "Dresses",
            "leaf": "Midi",
            "folder_id": "13351",
            "url": "https://www.shopbop.com/clothing-dresses/br/v=1/13351.htm?f=MADressLength-Midi",
            "category": "Women > Dresses > Midi",
        },
        "Women > Dresses > Mini": {
            "department": "Women",
            "subcategory": "Dresses",
            "leaf": "Mini",
            "folder_id": "13351",
            "url": "https://www.shopbop.com/clothing-dresses/br/v=1/13351.htm?f=MADressLength-Mini",
            "category": "Women > Dresses > Mini",
        },
        "Women > Dresses > Night Out": {
            "department": "Women",
            "subcategory": "Dresses",
            "leaf": "Night Out",
            "folder_id": "13351",
            "url": "https://www.shopbop.com/clothing-dresses/br/v=1/13351.htm?f=MADressOccasion-Night+Out",
            "category": "Women > Dresses > Night Out",
        },
        "Women > Dresses > Print Dresses": {
            "department": "Women",
            "subcategory": "Dresses",
            "leaf": "Print Dresses",
            "folder_id": "13351",
            "url": "https://www.shopbop.com/clothing-dresses/br/v=1/13351.htm?f=colors-Print&f=colors-Plaid",
            "category": "Women > Dresses > Print Dresses",
        },
        "Women > Get Inspired": {
            "department": "Women",
            "subcategory": "Get Inspired",
            "leaf": None,
            "folder_id": "13770",
            "url": "https://www.shopbop.com/our-favorites/br/v=1/13770.htm",
            "category": "Women > Get Inspired",
        },
        "Women > Get Inspired > Caroline's Closet": {
            "department": "Women",
            "subcategory": "Get Inspired",
            "leaf": "Caroline's Closet",
            "folder_id": "75192",
            "url": "https://www.shopbop.com/our-favorites-carolines-closet/br/v=1/75192.htm",
            "category": "Women > Get Inspired > Caroline's Closet",
        },
        "Women > Get Inspired > Designer Boutique": {
            "department": "Women",
            "subcategory": "Get Inspired",
            "leaf": "Designer Boutique",
            "folder_id": "13771",
            "url": "https://www.shopbop.com/boutique-designer/br/v=1/13771.htm",
            "category": "Women > Get Inspired > Designer Boutique",
        },
        "Women > Get Inspired > Editors' Picks": {
            "department": "Women",
            "subcategory": "Get Inspired",
            "leaf": "Editors' Picks",
            "folder_id": "13942",
            "url": "https://www.shopbop.com/boutique-editors-picks/br/v=1/13942.htm",
            "category": "Women > Get Inspired > Editors' Picks",
        },
        "Women > Get Inspired > Elevated Staples": {
            "department": "Women",
            "subcategory": "Get Inspired",
            "leaf": "Elevated Staples",
            "folder_id": "67895",
            "url": "https://www.shopbop.com/shop-occasion-everyday-essentials/br/v=1/67895.htm",
            "category": "Women > Get Inspired > Elevated Staples",
        },
        "Women > Get Inspired > Fashion Finds: Under $200": {
            "department": "Women",
            "subcategory": "Get Inspired",
            "leaf": "Fashion Finds: Under $200",
            "folder_id": "28182",
            "url": "https://www.shopbop.com/our-favorites-fashion-finds-under-200/br/v=1/28182.htm",
            "category": "Women > Get Inspired > Fashion Finds: Under $200",
        },
        "Women > Get Inspired > Going-Out Edit": {
            "department": "Women",
            "subcategory": "Get Inspired",
            "leaf": "Going-Out Edit",
            "folder_id": "68031",
            "url": "https://www.shopbop.com/shop-occasion-night-out-edit/br/v=1/68031.htm",
            "category": "Women > Get Inspired > Going-Out Edit",
        },
        "Women > Get Inspired > Modern Workwear": {
            "department": "Women",
            "subcategory": "Get Inspired",
            "leaf": "Modern Workwear",
            "folder_id": "68877",
            "url": "https://www.shopbop.com/shop-occasion-new/br/v=1/68877.htm",
            "category": "Women > Get Inspired > Modern Workwear",
        },
        "Women > Get Inspired > Most Hearted Styles": {
            "department": "Women",
            "subcategory": "Get Inspired",
            "leaf": "Most Hearted Styles",
            "folder_id": "59577",
            "url": "https://www.shopbop.com/our-must-haves-most-hearted-styles/br/v=1/59577.htm",
            "category": "Women > Get Inspired > Most Hearted Styles",
        },
        "Women > Get Inspired > Style for check-me-out checkouts.": {
            "department": "Women",
            "subcategory": "Get Inspired",
            "leaf": "Style for check-me-out checkouts.",
            "folder_id": "80701",
            "url": "https://www.shopbop.com/special-style-whats-next-style-check-me-out-checkouts/br/v=1/80701.htm",
            "category": "Women > Get Inspired > Style for check-me-out checkouts.",
        },
        "Women > Get Inspired > Style for date nights to late nights.": {
            "department": "Women",
            "subcategory": "Get Inspired",
            "leaf": "Style for date nights to late nights.",
            "folder_id": "80702",
            "url": "https://www.shopbop.com/special-style-whats-next-style-date-nights-late-nights/br/v=1/80702.htm",
            "category": "Women > Get Inspired > Style for date nights to late nights.",
        },
        "Women > Get Inspired > Style for subway runways.": {
            "department": "Women",
            "subcategory": "Get Inspired",
            "leaf": "Style for subway runways.",
            "folder_id": "80703",
            "url": "https://www.shopbop.com/special-style-whats-next-style-subway-runways/br/v=1/80703.htm",
            "category": "Women > Get Inspired > Style for subway runways.",
        },
        "Women > Get Inspired > Style for that party you forgot was tomorrow.": {
            "department": "Women",
            "subcategory": "Get Inspired",
            "leaf": "Style for that party you forgot was tomorrow.",
            "folder_id": "80700",
            "url": "https://www.shopbop.com/special-style-whats-next-style-that-party-you-forgot-was/br/v=1/80700.htm",
            "category": "Women > Get Inspired > Style for that party you forgot was tomorrow.",
        },
        "Women > Get Inspired > The Dress Shop": {
            "department": "Women",
            "subcategory": "Get Inspired",
            "leaf": "The Dress Shop",
            "folder_id": "60749",
            "url": "https://www.shopbop.com/shop-occasion-dress/br/v=1/60749.htm",
            "category": "Women > Get Inspired > The Dress Shop",
        },
        "Women > Get Inspired > Top Sellers": {
            "department": "Women",
            "subcategory": "Get Inspired",
            "leaf": "Top Sellers",
            "folder_id": "56675",
            "url": "https://www.shopbop.com/our-must-haves-top-sellers/br/v=1/56675.htm",
            "category": "Women > Get Inspired > Top Sellers",
        },
        "Women > Get Inspired > Vacation Wardrobe": {
            "department": "Women",
            "subcategory": "Get Inspired",
            "leaf": "Vacation Wardrobe",
            "folder_id": "68230",
            "url": "https://www.shopbop.com/shop-occasion-vacation-wardrobe/br/v=1/68230.htm",
            "category": "Women > Get Inspired > Vacation Wardrobe",
        },
        "Women > Get Inspired > Wedding Guest Outfits": {
            "department": "Women",
            "subcategory": "Get Inspired",
            "leaf": "Wedding Guest Outfits",
            "folder_id": "66583",
            "url": "https://www.shopbop.com/shop-occasion-best-dressed-guest/br/v=1/66583.htm",
            "category": "Women > Get Inspired > Wedding Guest Outfits",
        },
        "Women > Get Inspired > Wedding Shop": {
            "department": "Women",
            "subcategory": "Get Inspired",
            "leaf": "Wedding Shop",
            "folder_id": "13838",
            "url": "https://www.shopbop.com/shop-occasion-wedding/br/v=1/13838.htm",
            "category": "Women > Get Inspired > Wedding Shop",
        },
        "Women > Home & Gifts": {
            "department": "Women",
            "subcategory": "Home & Gifts",
            "leaf": None,
            "folder_id": "13885",
            "url": "https://www.shopbop.com/home-gifts/br/v=1/13885.htm",
            "category": "Women > Home & Gifts",
        },
        "Women > Home & Gifts > All Gifts": {
            "department": "Women",
            "subcategory": "Home & Gifts",
            "leaf": "All Gifts",
            "folder_id": "74280",
            "url": "https://www.shopbop.com/home-gifts-gifts/br/v=1/74280.htm",
            "category": "Women > Home & Gifts > All Gifts",
        },
        "Women > Home & Gifts > All Home": {
            "department": "Women",
            "subcategory": "Home & Gifts",
            "leaf": "All Home",
            "folder_id": "74272",
            "url": "https://www.shopbop.com/home-gifts-home/br/v=1/74272.htm",
            "category": "Women > Home & Gifts > All Home",
        },
        "Women > Home & Gifts > Beauty Sets & Gifts": {
            "department": "Women",
            "subcategory": "Home & Gifts",
            "leaf": "Beauty Sets & Gifts",
            "folder_id": "74281",
            "url": "https://www.shopbop.com/home-gifts-gifts-beauty-sets-gifts/br/v=1/74281.htm",
            "category": "Women > Home & Gifts > Beauty Sets & Gifts",
        },
        "Women > Home & Gifts > Bedding & Blankets": {
            "department": "Women",
            "subcategory": "Home & Gifts",
            "leaf": "Bedding & Blankets",
            "folder_id": "74279",
            "url": "https://www.shopbop.com/home-gifts-home-bedding-blankets/br/v=1/74279.htm",
            "category": "Women > Home & Gifts > Bedding & Blankets",
        },
        "Women > Home & Gifts > Books & Stationery": {
            "department": "Women",
            "subcategory": "Home & Gifts",
            "leaf": "Books & Stationery",
            "folder_id": "74278",
            "url": "https://www.shopbop.com/home-gifts-home-books-stationery/br/v=1/74278.htm",
            "category": "Women > Home & Gifts > Books & Stationery",
        },
        "Women > Home & Gifts > Candles": {
            "department": "Women",
            "subcategory": "Home & Gifts",
            "leaf": "Candles",
            "folder_id": "74277",
            "url": "https://www.shopbop.com/home-gifts-home-candles/br/v=1/74277.htm",
            "category": "Women > Home & Gifts > Candles",
        },
        "Women > Home & Gifts > Décor": {
            "department": "Women",
            "subcategory": "Home & Gifts",
            "leaf": "Décor",
            "folder_id": "74276",
            "url": "https://www.shopbop.com/home-gifts-home-dcor/br/v=1/74276.htm",
            "category": "Women > Home & Gifts > Décor",
        },
        "Women > Home & Gifts > Games": {
            "department": "Women",
            "subcategory": "Home & Gifts",
            "leaf": "Games",
            "folder_id": "74275",
            "url": "https://www.shopbop.com/home-gifts-home-games/br/v=1/74275.htm",
            "category": "Women > Home & Gifts > Games",
        },
        "Women > Home & Gifts > Gifts Under $100": {
            "department": "Women",
            "subcategory": "Home & Gifts",
            "leaf": "Gifts Under $100",
            "folder_id": "74282",
            "url": "https://www.shopbop.com/home-gifts-gifts-gifts-under-100/br/v=1/74282.htm",
            "category": "Women > Home & Gifts > Gifts Under $100",
        },
        "Women > Home & Gifts > Gifts Under $50": {
            "department": "Women",
            "subcategory": "Home & Gifts",
            "leaf": "Gifts Under $50",
            "folder_id": "74286",
            "url": "https://www.shopbop.com/home-gifts-gifts-gifts-under-50/br/v=1/74286.htm",
            "category": "Women > Home & Gifts > Gifts Under $50",
        },
        "Women > Home & Gifts > Gifts for Her": {
            "department": "Women",
            "subcategory": "Home & Gifts",
            "leaf": "Gifts for Her",
            "folder_id": "74285",
            "url": "https://www.shopbop.com/home-gifts-gifts-gifts-her/br/v=1/74285.htm",
            "category": "Women > Home & Gifts > Gifts for Her",
        },
        "Women > Home & Gifts > Gifts for Him": {
            "department": "Women",
            "subcategory": "Home & Gifts",
            "leaf": "Gifts for Him",
            "folder_id": "74284",
            "url": "https://www.shopbop.com/home-gifts-gifts-gifts-him/br/v=1/74284.htm",
            "category": "Women > Home & Gifts > Gifts for Him",
        },
        "Women > Home & Gifts > Gifts for Home": {
            "department": "Women",
            "subcategory": "Home & Gifts",
            "leaf": "Gifts for Home",
            "folder_id": "74283",
            "url": "https://www.shopbop.com/home-gifts-gifts-gifts-home/br/v=1/74283.htm",
            "category": "Women > Home & Gifts > Gifts for Home",
        },
        "Women > Home & Gifts > Tabletop": {
            "department": "Women",
            "subcategory": "Home & Gifts",
            "leaf": "Tabletop",
            "folder_id": "74274",
            "url": "https://www.shopbop.com/home-gifts-home-tabletop/br/v=1/74274.htm",
            "category": "Women > Home & Gifts > Tabletop",
        },
        "Women > Home & Gifts > Towels": {
            "department": "Women",
            "subcategory": "Home & Gifts",
            "leaf": "Towels",
            "folder_id": "74273",
            "url": "https://www.shopbop.com/home-gifts-home-towels/br/v=1/74273.htm",
            "category": "Women > Home & Gifts > Towels",
        },
        "Women > Jewelry & Accessories": {
            "department": "Women",
            "subcategory": "Jewelry & Accessories",
            "leaf": None,
            "folder_id": "13539",
            "url": "https://www.shopbop.com/jewelry-accessories/br/v=1/13539.htm",
            "category": "Women > Jewelry & Accessories",
        },
        "Women > Jewelry & Accessories > All Jewelry": {
            "department": "Women",
            "subcategory": "Jewelry & Accessories",
            "leaf": "All Jewelry",
            "folder_id": "13540",
            "url": "https://www.shopbop.com/jewelry-accessories/br/v=1/13540.htm",
            "category": "Women > Jewelry & Accessories > All Jewelry",
        },
        "Women > Jewelry & Accessories > Bag & Phone Charms": {
            "department": "Women",
            "subcategory": "Jewelry & Accessories",
            "leaf": "Bag & Phone Charms",
            "folder_id": "75405",
            "url": "https://www.shopbop.com/jewelry-accessories-trend-bag-phone-charms/br/v=1/75405.htm",
            "category": "Women > Jewelry & Accessories > Bag & Phone Charms",
        },
        "Women > Jewelry & Accessories > Belts": {
            "department": "Women",
            "subcategory": "Jewelry & Accessories",
            "leaf": "Belts",
            "folder_id": "13577",
            "url": "https://www.shopbop.com/accessories-belts/br/v=1/13577.htm",
            "category": "Women > Jewelry & Accessories > Belts",
        },
        "Women > Jewelry & Accessories > Bracelets": {
            "department": "Women",
            "subcategory": "Jewelry & Accessories",
            "leaf": "Bracelets",
            "folder_id": "13540",
            "url": "https://www.shopbop.com/jewelry-accessories/br/v=1/13540.htm?f=MAJewelryProductType-Bracelets",
            "category": "Women > Jewelry & Accessories > Bracelets",
        },
        "Women > Jewelry & Accessories > Details You'll Love: Carolina Amato": {
            "department": "Women",
            "subcategory": "Jewelry & Accessories",
            "leaf": "Details You'll Love: Carolina Amato",
            "folder_id": "23102",
            "url": "https://www.shopbop.com/carolina-amato/br/v=1/23102.htm",
            "category": "Women > Jewelry & Accessories > Details You'll Love: Carolina Amato",
        },
        "Women > Jewelry & Accessories > Earrings": {
            "department": "Women",
            "subcategory": "Jewelry & Accessories",
            "leaf": "Earrings",
            "folder_id": "13540",
            "url": "https://www.shopbop.com/jewelry-accessories/br/v=1/13540.htm?f=MAJewelryProductType-Earrings",
            "category": "Women > Jewelry & Accessories > Earrings",
        },
        "Women > Jewelry & Accessories > Fine Jewelry": {
            "department": "Women",
            "subcategory": "Jewelry & Accessories",
            "leaf": "Fine Jewelry",
            "folder_id": "13540",
            "url": "https://www.shopbop.com/jewelry-accessories/br/v=1/13540.htm?f=MAJewelryProductType-Fine+Jewelry",
            "category": "Women > Jewelry & Accessories > Fine Jewelry",
        },
        "Women > Jewelry & Accessories > Gloves": {
            "department": "Women",
            "subcategory": "Jewelry & Accessories",
            "leaf": "Gloves",
            "folder_id": "13576",
            "url": "https://www.shopbop.com/accessories-gloves/br/v=1/13576.htm",
            "category": "Women > Jewelry & Accessories > Gloves",
        },
        "Women > Jewelry & Accessories > Hair Accessories": {
            "department": "Women",
            "subcategory": "Jewelry & Accessories",
            "leaf": "Hair Accessories",
            "folder_id": "13575",
            "url": "https://www.shopbop.com/jewelry-accessories-hair/br/v=1/13575.htm",
            "category": "Women > Jewelry & Accessories > Hair Accessories",
        },
        "Women > Jewelry & Accessories > Hats": {
            "department": "Women",
            "subcategory": "Jewelry & Accessories",
            "leaf": "Hats",
            "folder_id": "13574",
            "url": "https://www.shopbop.com/accessories-hats/br/v=1/13574.htm",
            "category": "Women > Jewelry & Accessories > Hats",
        },
        "Women > Jewelry & Accessories > Lab Grown Jewelry": {
            "department": "Women",
            "subcategory": "Jewelry & Accessories",
            "leaf": "Lab Grown Jewelry",
            "folder_id": "80833",
            "url": "https://www.shopbop.com/jewelry-accessories-lab-grown-jewelry/br/v=1/80833.htm",
            "category": "Women > Jewelry & Accessories > Lab Grown Jewelry",
        },
        "Women > Jewelry & Accessories > Necklaces": {
            "department": "Women",
            "subcategory": "Jewelry & Accessories",
            "leaf": "Necklaces",
            "folder_id": "13540",
            "url": "https://www.shopbop.com/jewelry-accessories/br/v=1/13540.htm?f=MAJewelryProductType-Necklaces",
            "category": "Women > Jewelry & Accessories > Necklaces",
        },
        "Women > Jewelry & Accessories > Rings": {
            "department": "Women",
            "subcategory": "Jewelry & Accessories",
            "leaf": "Rings",
            "folder_id": "13540",
            "url": "https://www.shopbop.com/jewelry-accessories/br/v=1/13540.htm?f=MAJewelryProductType-Rings",
            "category": "Women > Jewelry & Accessories > Rings",
        },
        "Women > Jewelry & Accessories > Scarves & Wraps": {
            "department": "Women",
            "subcategory": "Jewelry & Accessories",
            "leaf": "Scarves & Wraps",
            "folder_id": "13564",
            "url": "https://www.shopbop.com/accessories-scarves-wraps/br/v=1/13564.htm",
            "category": "Women > Jewelry & Accessories > Scarves & Wraps",
        },
        "Women > Jewelry & Accessories > Socks & Tights": {
            "department": "Women",
            "subcategory": "Jewelry & Accessories",
            "leaf": "Socks & Tights",
            "folder_id": "13578",
            "url": "https://www.shopbop.com/accessories-socks-tights/br/v=1/13578.htm",
            "category": "Women > Jewelry & Accessories > Socks & Tights",
        },
        "Women > Jewelry & Accessories > Statement Scarves": {
            "department": "Women",
            "subcategory": "Jewelry & Accessories",
            "leaf": "Statement Scarves",
            "folder_id": "80586",
            "url": "https://www.shopbop.com/jewelry-accessories-trend-statement-scarves/br/v=1/80586.htm",
            "category": "Women > Jewelry & Accessories > Statement Scarves",
        },
        "Women > Jewelry & Accessories > Sunglasses & Eyewear": {
            "department": "Women",
            "subcategory": "Jewelry & Accessories",
            "leaf": "Sunglasses & Eyewear",
            "folder_id": "13558",
            "url": "https://www.shopbop.com/jewelry-accessories-sunglasses-eyewear/br/v=1/13558.htm",
            "category": "Women > Jewelry & Accessories > Sunglasses & Eyewear",
        },
        "Women > Jewelry & Accessories > Tiger’s Eye Jewelry": {
            "department": "Women",
            "subcategory": "Jewelry & Accessories",
            "leaf": "Tiger’s Eye Jewelry",
            "folder_id": "80876",
            "url": "https://www.shopbop.com/jewelry-accessories-tigers-eye-jewelry/br/v=1/80876.htm",
            "category": "Women > Jewelry & Accessories > Tiger’s Eye Jewelry",
        },
        "Women > Jewelry & Accessories > Travel Accessories": {
            "department": "Women",
            "subcategory": "Jewelry & Accessories",
            "leaf": "Travel Accessories",
            "folder_id": "13586",
            "url": "https://www.shopbop.com/accessories-travel/br/v=1/13586.htm",
            "category": "Women > Jewelry & Accessories > Travel Accessories",
        },
        "Women > Jewelry & Accessories > Watches": {
            "department": "Women",
            "subcategory": "Jewelry & Accessories",
            "leaf": "Watches",
            "folder_id": "13540",
            "url": "https://www.shopbop.com/jewelry-accessories/br/v=1/13540.htm?f=MAJewelryProductType-Watches",
            "category": "Women > Jewelry & Accessories > Watches",
        },
        "Women > Jewelry & Accessories > Winter Accessories": {
            "department": "Women",
            "subcategory": "Jewelry & Accessories",
            "leaf": "Winter Accessories",
            "folder_id": "13584",
            "url": "https://www.shopbop.com/accessories-winter/br/v=1/13584.htm",
            "category": "Women > Jewelry & Accessories > Winter Accessories",
        },
        "Women > Sale": {
            "department": "Women",
            "subcategory": "Sale",
            "leaf": None,
            "folder_id": "13594",
            "url": "https://www.shopbop.com/sale/br/v=1/13594.htm",
            "category": "Women > Sale",
        },
        "Women > Sale > 20% Off": {
            "department": "Women",
            "subcategory": "Sale",
            "leaf": "20% Off",
            "folder_id": "14052",
            "url": "https://www.shopbop.com/sale-20-off/br/v=1/14052.htm",
            "category": "Women > Sale > 20% Off",
        },
        "Women > Sale > 30% Off": {
            "department": "Women",
            "subcategory": "Sale",
            "leaf": "30% Off",
            "folder_id": "14053",
            "url": "https://www.shopbop.com/sale-30-percent-off/br/v=1/14053.htm",
            "category": "Women > Sale > 30% Off",
        },
        "Women > Sale > 40% Off": {
            "department": "Women",
            "subcategory": "Sale",
            "leaf": "40% Off",
            "folder_id": "14054",
            "url": "https://www.shopbop.com/sale-40-percent-off/br/v=1/14054.htm",
            "category": "Women > Sale > 40% Off",
        },
        "Women > Sale > 50% Off - Final Sale": {
            "department": "Women",
            "subcategory": "Sale",
            "leaf": "50% Off - Final Sale",
            "folder_id": "14055",
            "url": "https://www.shopbop.com/sale-50-off/br/v=1/14055.htm",
            "category": "Women > Sale > 50% Off - Final Sale",
        },
        "Women > Sale > 60% Off & Over – Final Sale": {
            "department": "Women",
            "subcategory": "Sale",
            "leaf": "60% Off & Over – Final Sale",
            "folder_id": "14056",
            "url": "https://www.shopbop.com/sale-60-off-over-final/br/v=1/14056.htm",
            "category": "Women > Sale > 60% Off & Over – Final Sale",
        },
        "Women > Sale > Bags": {
            "department": "Women",
            "subcategory": "Sale",
            "leaf": "Bags",
            "folder_id": "15355",
            "url": "https://www.shopbop.com/sale-bags/br/v=1/15355.htm",
            "category": "Women > Sale > Bags",
        },
        "Women > Sale > Beauty": {
            "department": "Women",
            "subcategory": "Sale",
            "leaf": "Beauty",
            "folder_id": "70293",
            "url": "https://www.shopbop.com/sale-beauty/br/v=1/70293.htm",
            "category": "Women > Sale > Beauty",
        },
        "Women > Sale > Best of Sale": {
            "department": "Women",
            "subcategory": "Sale",
            "leaf": "Best of Sale",
            "folder_id": "60969",
            "url": "https://www.shopbop.com/sale-best/br/v=1/60969.htm",
            "category": "Women > Sale > Best of Sale",
        },
        "Women > Sale > Clothing": {
            "department": "Women",
            "subcategory": "Sale",
            "leaf": "Clothing",
            "folder_id": "15381",
            "url": "https://www.shopbop.com/sale-clothing/br/v=1/15381.htm",
            "category": "Women > Sale > Clothing",
        },
        "Women > Sale > Designer Boutique": {
            "department": "Women",
            "subcategory": "Sale",
            "leaf": "Designer Boutique",
            "folder_id": "15538",
            "url": "https://www.shopbop.com/sale-designer-boutique/br/v=1/15538.htm",
            "category": "Women > Sale > Designer Boutique",
        },
        "Women > Sale > Jewelry & Accessories": {
            "department": "Women",
            "subcategory": "Sale",
            "leaf": "Jewelry & Accessories",
            "folder_id": "15304",
            "url": "https://www.shopbop.com/sale-jewelry-accessories/br/v=1/15304.htm",
            "category": "Women > Sale > Jewelry & Accessories",
        },
        "Women > Sale > New to Sale": {
            "department": "Women",
            "subcategory": "Sale",
            "leaf": "New to Sale",
            "folder_id": "14233",
            "url": "https://www.shopbop.com/sale-new/br/v=1/14233.htm",
            "category": "Women > Sale > New to Sale",
        },
        "Women > Sale > Sale Picks Under $100": {
            "department": "Women",
            "subcategory": "Sale",
            "leaf": "Sale Picks Under $100",
            "folder_id": "52017",
            "url": "https://www.shopbop.com/sale-picks-under-100/br/v=1/52017.htm",
            "category": "Women > Sale > Sale Picks Under $100",
        },
        "Women > Sale > Sale Picks Under $250": {
            "department": "Women",
            "subcategory": "Sale",
            "leaf": "Sale Picks Under $250",
            "folder_id": "57014",
            "url": "https://www.shopbop.com/sale-picks-under-250/br/v=1/57014.htm",
            "category": "Women > Sale > Sale Picks Under $250",
        },
        "Women > Sale > Shoes": {
            "department": "Women",
            "subcategory": "Sale",
            "leaf": "Shoes",
            "folder_id": "15539",
            "url": "https://www.shopbop.com/sale-shoes/br/v=1/15539.htm",
            "category": "Women > Sale > Shoes",
        },
        "Women > Shoes": {
            "department": "Women",
            "subcategory": "Shoes",
            "leaf": None,
            "folder_id": "13438",
            "url": "https://www.shopbop.com/shoes/br/v=1/13438.htm",
            "category": "Women > Shoes",
        },
        "Women > Shoes > Best Boots": {
            "department": "Women",
            "subcategory": "Shoes",
            "leaf": "Best Boots",
            "folder_id": "80870",
            "url": "https://www.shopbop.com/shoes-best-boots/br/v=1/80870.htm",
            "category": "Women > Shoes > Best Boots",
        },
        "Women > Shoes > Boots": {
            "department": "Women",
            "subcategory": "Shoes",
            "leaf": "Boots",
            "folder_id": "13460",
            "url": "https://www.shopbop.com/shoes-boots/br/v=1/13460.htm",
            "category": "Women > Shoes > Boots",
        },
        "Women > Shoes > Clogs": {
            "department": "Women",
            "subcategory": "Shoes",
            "leaf": "Clogs",
            "folder_id": "67599",
            "url": "https://www.shopbop.com/shoes-trend-cool-clogs/br/v=1/67599.htm",
            "category": "Women > Shoes > Clogs",
        },
        "Women > Shoes > Espadrilles": {
            "department": "Women",
            "subcategory": "Shoes",
            "leaf": "Espadrilles",
            "folder_id": "13487",
            "url": "https://www.shopbop.com/shoes-espadrilles/br/v=1/13487.htm",
            "category": "Women > Shoes > Espadrilles",
        },
        "Women > Shoes > Everyday Styles": {
            "department": "Women",
            "subcategory": "Shoes",
            "leaf": "Everyday Styles",
            "folder_id": "80871",
            "url": "https://www.shopbop.com/shoes-everyday-styles/br/v=1/80871.htm",
            "category": "Women > Shoes > Everyday Styles",
        },
        "Women > Shoes > Flats": {
            "department": "Women",
            "subcategory": "Shoes",
            "leaf": "Flats",
            "folder_id": "13455",
            "url": "https://www.shopbop.com/shoes-flats/br/v=1/13455.htm",
            "category": "Women > Shoes > Flats",
        },
        "Women > Shoes > Low-Profile Sneakers": {
            "department": "Women",
            "subcategory": "Shoes",
            "leaf": "Low-Profile Sneakers",
            "folder_id": "79359",
            "url": "https://www.shopbop.com/shoes-low-profile-sneaker/br/v=1/79359.htm",
            "category": "Women > Shoes > Low-Profile Sneakers",
        },
        "Women > Shoes > Must-Have Mules": {
            "department": "Women",
            "subcategory": "Shoes",
            "leaf": "Must-Have Mules",
            "folder_id": "80872",
            "url": "https://www.shopbop.com/shoes-must-have-mules/br/v=1/80872.htm",
            "category": "Women > Shoes > Must-Have Mules",
        },
        "Women > Shoes > New From: Rag & Bone": {
            "department": "Women",
            "subcategory": "Shoes",
            "leaf": "New From: Rag & Bone",
            "folder_id": "3174",
            "url": "https://www.shopbop.com/rag-bone-shoes/br/v=1/3174.htm",
            "category": "Women > Shoes > New From: Rag & Bone",
        },
        "Women > Shoes > Pumps": {
            "department": "Women",
            "subcategory": "Shoes",
            "leaf": "Pumps",
            "folder_id": "13449",
            "url": "https://www.shopbop.com/shoes-pumps/br/v=1/13449.htm",
            "category": "Women > Shoes > Pumps",
        },
        "Women > Shoes > Rain & Winter Boots": {
            "department": "Women",
            "subcategory": "Shoes",
            "leaf": "Rain & Winter Boots",
            "folder_id": "13490",
            "url": "https://www.shopbop.com/shoes-rain-boots/br/v=1/13490.htm",
            "category": "Women > Shoes > Rain & Winter Boots",
        },
        "Women > Shoes > Sandals": {
            "department": "Women",
            "subcategory": "Shoes",
            "leaf": "Sandals",
            "folder_id": "13441",
            "url": "https://www.shopbop.com/shoes-sandals/br/v=1/13441.htm",
            "category": "Women > Shoes > Sandals",
        },
        "Women > Shoes > Sneakers & Athletic": {
            "department": "Women",
            "subcategory": "Shoes",
            "leaf": "Sneakers & Athletic",
            "folder_id": "13439",
            "url": "https://www.shopbop.com/shoes-sneakers-athletic/br/v=1/13439.htm",
            "category": "Women > Shoes > Sneakers & Athletic",
        },
        "Women > Shoes > Step Into: STAUD": {
            "department": "Women",
            "subcategory": "Shoes",
            "leaf": "Step Into: STAUD",
            "folder_id": "62131",
            "url": "https://www.shopbop.com/staud-shoes/br/v=1/62131.htm",
            "category": "Women > Shoes > Step Into: STAUD",
        },
        "Women > What's New": {
            "department": "Women",
            "subcategory": "What's New",
            "leaf": None,
            "folder_id": "13198",
            "url": "https://www.shopbop.com/whats-new/br/v=1/13198.htm",
            "category": "Women > What's New",
        },
        "Women > What's New > Autumn Arrivals": {
            "department": "Women",
            "subcategory": "What's New",
            "leaf": "Autumn Arrivals",
            "folder_id": "80841",
            "url": "https://www.shopbop.com/whats-new-autumn-arrivals/br/v=1/80841.htm",
            "category": "Women > What's New > Autumn Arrivals",
        },
        "Women > What's New > Back In Stock": {
            "department": "Women",
            "subcategory": "What's New",
            "leaf": "Back In Stock",
            "folder_id": "50578",
            "url": "https://www.shopbop.com/back-stock/br/v=1/50578.htm",
            "category": "Women > What's New > Back In Stock",
        },
        "Women > What's New > Bags": {
            "department": "Women",
            "subcategory": "What's New",
            "leaf": "Bags",
            "folder_id": "13209",
            "url": "https://www.shopbop.com/whats-new-bags/br/v=1/13209.htm",
            "category": "Women > What's New > Bags",
        },
        "Women > What's New > Beauty": {
            "department": "Women",
            "subcategory": "What's New",
            "leaf": "Beauty",
            "folder_id": "69933",
            "url": "https://www.shopbop.com/whats-new-beauty/br/v=1/69933.htm",
            "category": "Women > What's New > Beauty",
        },
        "Women > What's New > Clothing": {
            "department": "Women",
            "subcategory": "What's New",
            "leaf": "Clothing",
            "folder_id": "13243",
            "url": "https://www.shopbop.com/whats-new-clothing/br/v=1/13243.htm",
            "category": "Women > What's New > Clothing",
        },
        "Women > What's New > Designer Boutique": {
            "department": "Women",
            "subcategory": "What's New",
            "leaf": "Designer Boutique",
            "folder_id": "13261",
            "url": "https://www.shopbop.com/whats-new-designer-boutique/br/v=1/13261.htm",
            "category": "Women > What's New > Designer Boutique",
        },
        "Women > What's New > Exclusive: LE BOP": {
            "department": "Women",
            "subcategory": "What's New",
            "leaf": "Exclusive: LE BOP",
            "folder_id": "75747",
            "url": "https://www.shopbop.com/bop/br/v=1/75747.htm",
            "category": "Women > What's New > Exclusive: LE BOP",
        },
        "Women > What's New > Fall Dresses": {
            "department": "Women",
            "subcategory": "What's New",
            "leaf": "Fall Dresses",
            "folder_id": "74320",
            "url": "https://www.shopbop.com/whats-new-winters-best-dresses/br/v=1/74320.htm",
            "category": "Women > What's New > Fall Dresses",
        },
        "Women > What's New > Home": {
            "department": "Women",
            "subcategory": "What's New",
            "leaf": "Home",
            "folder_id": "78316",
            "url": "https://www.shopbop.com/whats-new-home/br/v=1/78316.htm",
            "category": "Women > What's New > Home",
        },
        "Women > What's New > Inclusive Sizes": {
            "department": "Women",
            "subcategory": "What's New",
            "leaf": "Inclusive Sizes",
            "folder_id": "62708",
            "url": "https://www.shopbop.com/extended-sizes/br/v=1/62708.htm",
            "category": "Women > What's New > Inclusive Sizes",
        },
        "Women > What's New > Jewelry & Accessories": {
            "department": "Women",
            "subcategory": "What's New",
            "leaf": "Jewelry & Accessories",
            "folder_id": "13224",
            "url": "https://www.shopbop.com/whats-new-jewelry-accessories/br/v=1/13224.htm",
            "category": "Women > What's New > Jewelry & Accessories",
        },
        "Women > What's New > New & Emerging Designers": {
            "department": "Women",
            "subcategory": "What's New",
            "leaf": "New & Emerging Designers",
            "folder_id": "74331",
            "url": "https://www.shopbop.com/special-new-emerging-designers/br/v=1/74331.htm",
            "category": "Women > What's New > New & Emerging Designers",
        },
        "Women > What's New > New Today": {
            "department": "Women",
            "subcategory": "What's New",
            "leaf": "New Today",
            "folder_id": "50579",
            "url": "https://www.shopbop.com/new-today/br/v=1/50579.htm",
            "category": "Women > What's New > New Today",
        },
        "Women > What's New > Now Trending": {
            "department": "Women",
            "subcategory": "What's New",
            "leaf": "Now Trending",
            "folder_id": "79427",
            "url": "https://www.shopbop.com/whats-new-top-new-styles/br/v=1/79427.htm",
            "category": "Women > What's New > Now Trending",
        },
        "Women > What's New > Shoes": {
            "department": "Women",
            "subcategory": "What's New",
            "leaf": "Shoes",
            "folder_id": "13199",
            "url": "https://www.shopbop.com/whats-new-shoes/br/v=1/13199.htm",
            "category": "Women > What's New > Shoes",
        },
        "Women > What's New > The Essentials Edit": {
            "department": "Women",
            "subcategory": "What's New",
            "leaf": "The Essentials Edit",
            "folder_id": "74319",
            "url": "https://www.shopbop.com/whats-new-essentials-edit/br/v=1/74319.htm",
            "category": "Women > What's New > The Essentials Edit",
        },
    },
    "Men": {
        "Men > Accessories": {
            "department": "Men",
            "subcategory": "Accessories",
            "leaf": None,
            "folder_id": "19187",
            "url": "https://www.shopbop.com/men-accessories/br/v=1/19187.htm",
            "category": "Men > Accessories",
        },
        "Men > Accessories > Bags": {
            "department": "Men",
            "subcategory": "Accessories",
            "leaf": "Bags",
            "folder_id": "19222",
            "url": "https://www.shopbop.com/men-bags/br/v=1/19222.htm",
            "category": "Men > Accessories > Bags",
        },
        "Men > Accessories > Belts": {
            "department": "Men",
            "subcategory": "Accessories",
            "leaf": "Belts",
            "folder_id": "19223",
            "url": "https://www.shopbop.com/men-accessories-belts/br/v=1/19223.htm",
            "category": "Men > Accessories > Belts",
        },
        "Men > Accessories > Hats, Scarves, & Gloves": {
            "department": "Men",
            "subcategory": "Accessories",
            "leaf": "Hats, Scarves, & Gloves",
            "folder_id": "19224",
            "url": "https://www.shopbop.com/men-accessories-hats-scarves-gloves/br/v=1/19224.htm",
            "category": "Men > Accessories > Hats, Scarves, & Gloves",
        },
        "Men > Accessories > Jewelry": {
            "department": "Men",
            "subcategory": "Accessories",
            "leaf": "Jewelry",
            "folder_id": "19225",
            "url": "https://www.shopbop.com/men-accessories-jewelry/br/v=1/19225.htm",
            "category": "Men > Accessories > Jewelry",
        },
        "Men > Accessories > Socks": {
            "department": "Men",
            "subcategory": "Accessories",
            "leaf": "Socks",
            "folder_id": "20262",
            "url": "https://www.shopbop.com/men-accessories-socks/br/v=1/20262.htm",
            "category": "Men > Accessories > Socks",
        },
        "Men > Accessories > Sunglasses": {
            "department": "Men",
            "subcategory": "Accessories",
            "leaf": "Sunglasses",
            "folder_id": "19227",
            "url": "https://www.shopbop.com/men-accessories-sunglasses/br/v=1/19227.htm",
            "category": "Men > Accessories > Sunglasses",
        },
        "Men > Accessories > Ties & Pocket Squares": {
            "department": "Men",
            "subcategory": "Accessories",
            "leaf": "Ties & Pocket Squares",
            "folder_id": "19229",
            "url": "https://www.shopbop.com/men-accessories-ties-pocket-squares/br/v=1/19229.htm",
            "category": "Men > Accessories > Ties & Pocket Squares",
        },
        "Men > Accessories > Travel Accessories": {
            "department": "Men",
            "subcategory": "Accessories",
            "leaf": "Travel Accessories",
            "folder_id": "19230",
            "url": "https://www.shopbop.com/men-accessories-travel/br/v=1/19230.htm",
            "category": "Men > Accessories > Travel Accessories",
        },
        "Men > Accessories > Wallets & Money Clips": {
            "department": "Men",
            "subcategory": "Accessories",
            "leaf": "Wallets & Money Clips",
            "folder_id": "19231",
            "url": "https://www.shopbop.com/men-accessories-wallets-money-clips/br/v=1/19231.htm",
            "category": "Men > Accessories > Wallets & Money Clips",
        },
        "Men > Clothing": {
            "department": "Men",
            "subcategory": "Clothing",
            "leaf": None,
            "folder_id": "19185",
            "url": "https://www.shopbop.com/men-clothing/br/v=1/19185.htm",
            "category": "Men > Clothing",
        },
        "Men > Clothing > 24/7 Staples: Closed": {
            "department": "Men",
            "subcategory": "Clothing",
            "leaf": "24/7 Staples: Closed",
            "folder_id": "28428",
            "url": "https://www.shopbop.com/men-brands-closed/br/v=1/28428.htm",
            "category": "Men > Clothing > 24/7 Staples: Closed",
        },
        "Men > Clothing > Activewear": {
            "department": "Men",
            "subcategory": "Clothing",
            "leaf": "Activewear",
            "folder_id": "67156",
            "url": "https://www.shopbop.com/men-clothing-activewear/br/v=1/67156.htm",
            "category": "Men > Clothing > Activewear",
        },
        "Men > Clothing > FRAME": {
            "department": "Men",
            "subcategory": "Clothing",
            "leaf": "FRAME",
            "folder_id": "39261",
            "url": "https://www.shopbop.com/men-brands-frame/br/v=1/39261.htm",
            "category": "Men > Clothing > FRAME",
        },
        "Men > Clothing > Faherty": {
            "department": "Men",
            "subcategory": "Clothing",
            "leaf": "Faherty",
            "folder_id": "22436",
            "url": "https://www.shopbop.com/men-brands-faherty/br/v=1/22436.htm",
            "category": "Men > Clothing > Faherty",
        },
        "Men > Clothing > Jeans": {
            "department": "Men",
            "subcategory": "Clothing",
            "leaf": "Jeans",
            "folder_id": "19208",
            "url": "https://www.shopbop.com/men-clothing-jeans/br/v=1/19208.htm",
            "category": "Men > Clothing > Jeans",
        },
        "Men > Clothing > NN07": {
            "department": "Men",
            "subcategory": "Clothing",
            "leaf": "NN07",
            "folder_id": "72344",
            "url": "https://www.shopbop.com/nn07/br/v=1/72344.htm",
            "category": "Men > Clothing > NN07",
        },
        "Men > Clothing > Outerwear": {
            "department": "Men",
            "subcategory": "Clothing",
            "leaf": "Outerwear",
            "folder_id": "19209",
            "url": "https://www.shopbop.com/men-clothing-outerwear/br/v=1/19209.htm",
            "category": "Men > Clothing > Outerwear",
        },
        "Men > Clothing > Pants": {
            "department": "Men",
            "subcategory": "Clothing",
            "leaf": "Pants",
            "folder_id": "19210",
            "url": "https://www.shopbop.com/men-clothing-pants/br/v=1/19210.htm",
            "category": "Men > Clothing > Pants",
        },
        "Men > Clothing > Polo Ralph Lauren": {
            "department": "Men",
            "subcategory": "Clothing",
            "leaf": "Polo Ralph Lauren",
            "folder_id": "56308",
            "url": "https://www.shopbop.com/men-brands-polo-ralph-lauren/br/v=1/56308.htm",
            "category": "Men > Clothing > Polo Ralph Lauren",
        },
        "Men > Clothing > Shirts": {
            "department": "Men",
            "subcategory": "Clothing",
            "leaf": "Shirts",
            "folder_id": "19207",
            "url": "https://www.shopbop.com/men-clothing-shirts/br/v=1/19207.htm",
            "category": "Men > Clothing > Shirts",
        },
        "Men > Clothing > Shorts": {
            "department": "Men",
            "subcategory": "Clothing",
            "leaf": "Shorts",
            "folder_id": "19212",
            "url": "https://www.shopbop.com/men-clothing-shorts/br/v=1/19212.htm",
            "category": "Men > Clothing > Shorts",
        },
        "Men > Clothing > Suits & Blazers": {
            "department": "Men",
            "subcategory": "Clothing",
            "leaf": "Suits & Blazers",
            "folder_id": "19213",
            "url": "https://www.shopbop.com/men-clothing-suits-blazers/br/v=1/19213.htm",
            "category": "Men > Clothing > Suits & Blazers",
        },
        "Men > Clothing > Sweaters": {
            "department": "Men",
            "subcategory": "Clothing",
            "leaf": "Sweaters",
            "folder_id": "19214",
            "url": "https://www.shopbop.com/men-clothing-sweaters/br/v=1/19214.htm",
            "category": "Men > Clothing > Sweaters",
        },
        "Men > Clothing > Sweatshirts": {
            "department": "Men",
            "subcategory": "Clothing",
            "leaf": "Sweatshirts",
            "folder_id": "19215",
            "url": "https://www.shopbop.com/men-clothing-sweatshirts/br/v=1/19215.htm",
            "category": "Men > Clothing > Sweatshirts",
        },
        "Men > Clothing > Swimsuits": {
            "department": "Men",
            "subcategory": "Clothing",
            "leaf": "Swimsuits",
            "folder_id": "51561",
            "url": "https://www.shopbop.com/men-clothing-swim/br/v=1/51561.htm",
            "category": "Men > Clothing > Swimsuits",
        },
        "Men > Clothing > T-Shirts & Polos": {
            "department": "Men",
            "subcategory": "Clothing",
            "leaf": "T-Shirts & Polos",
            "folder_id": "19211",
            "url": "https://www.shopbop.com/men-clothing-shirts-polos/br/v=1/19211.htm",
            "category": "Men > Clothing > T-Shirts & Polos",
        },
        "Men > Clothing > Underwear & Sleepwear": {
            "department": "Men",
            "subcategory": "Clothing",
            "leaf": "Underwear & Sleepwear",
            "folder_id": "19216",
            "url": "https://www.shopbop.com/men-clothing-underwear/br/v=1/19216.htm",
            "category": "Men > Clothing > Underwear & Sleepwear",
        },
        "Men > Clothing > Vince": {
            "department": "Men",
            "subcategory": "Clothing",
            "leaf": "Vince",
            "folder_id": "20175",
            "url": "https://www.shopbop.com/men-brands-vince/br/v=1/20175.htm",
            "category": "Men > Clothing > Vince",
        },
        "Men > Designers > Asian & Pacific Islander-Led Brands": {
            "department": "Men",
            "subcategory": "Designers",
            "leaf": "Asian & Pacific Islander-Led Brands",
            "folder_id": "74303",
            "url": "https://www.shopbop.com/men-shops-asian-pacific-islander-led-brands/br/v=1/74303.htm",
            "category": "Men > Designers > Asian & Pacific Islander-Led Brands",
        },
        "Men > Designers > Black-Led Brands": {
            "department": "Men",
            "subcategory": "Designers",
            "leaf": "Black-Led Brands",
            "folder_id": "73736",
            "url": "https://www.shopbop.com/men-shops-black-designers-black-owned-brands/br/v=1/73736.htm",
            "category": "Men > Designers > Black-Led Brands",
        },
        "Men > Designers > Closet Staples: Marine Layer": {
            "department": "Men",
            "subcategory": "Designers",
            "leaf": "Closet Staples: Marine Layer",
            "folder_id": "73582",
            "url": "https://www.shopbop.com/marine-layer/br/v=1/73582.htm",
            "category": "Men > Designers > Closet Staples: Marine Layer",
        },
        "Men > Designers > Fear of God": {
            "department": "Men",
            "subcategory": "Designers",
            "leaf": "Fear of God",
            "folder_id": "80216",
            "url": "https://www.shopbop.com/fear-god/br/v=1/80216.htm",
            "category": "Men > Designers > Fear of God",
        },
        "Men > Designers > Nahmias": {
            "department": "Men",
            "subcategory": "Designers",
            "leaf": "Nahmias",
            "folder_id": "79642",
            "url": "https://www.shopbop.com/nahmias/br/v=1/79642.htm",
            "category": "Men > Designers > Nahmias",
        },
        "Men > Designers > New & Emerging Designers": {
            "department": "Men",
            "subcategory": "Designers",
            "leaf": "New & Emerging Designers",
            "folder_id": "77845",
            "url": "https://www.shopbop.com/men-special-new-emerging-designers/br/v=1/77845.htm",
            "category": "Men > Designers > New & Emerging Designers",
        },
        "Men > Designers > Stone Island": {
            "department": "Men",
            "subcategory": "Designers",
            "leaf": "Stone Island",
            "folder_id": "78059",
            "url": "https://www.shopbop.com/stone-island/br/v=1/78059.htm",
            "category": "Men > Designers > Stone Island",
        },
        "Men > Designers > Vuori": {
            "department": "Men",
            "subcategory": "Designers",
            "leaf": "Vuori",
            "folder_id": "80280",
            "url": "https://www.shopbop.com/vuori/br/v=1/80280.htm",
            "category": "Men > Designers > Vuori",
        },
        "Men > Designers > Willy Chavarria": {
            "department": "Men",
            "subcategory": "Designers",
            "leaf": "Willy Chavarria",
            "folder_id": "79667",
            "url": "https://www.shopbop.com/willy-chavarria/br/v=1/79667.htm",
            "category": "Men > Designers > Willy Chavarria",
        },
        "Men > Our Edits": {
            "department": "Men",
            "subcategory": "Our Edits",
            "leaf": None,
            "folder_id": "19189",
            "url": "https://www.shopbop.com/men-shops/br/v=1/19189.htm",
            "category": "Men > Our Edits",
        },
        "Men > Our Edits > Editors' Picks": {
            "department": "Men",
            "subcategory": "Our Edits",
            "leaf": "Editors' Picks",
            "folder_id": "21587",
            "url": "https://www.shopbop.com/men-shops-editors-picks/br/v=1/21587.htm",
            "category": "Men > Our Edits > Editors' Picks",
        },
        "Men > Our Edits > Everyday Basics": {
            "department": "Men",
            "subcategory": "Our Edits",
            "leaf": "Everyday Basics",
            "folder_id": "21588",
            "url": "https://www.shopbop.com/men-shops-basics/br/v=1/21588.htm",
            "category": "Men > Our Edits > Everyday Basics",
        },
        "Men > Our Edits > Linen": {
            "department": "Men",
            "subcategory": "Our Edits",
            "leaf": "Linen",
            "folder_id": "79601",
            "url": "https://www.shopbop.com/men-special-linen/br/v=1/79601.htm",
            "category": "Men > Our Edits > Linen",
        },
        "Men > Our Edits > Polo Collars": {
            "department": "Men",
            "subcategory": "Our Edits",
            "leaf": "Polo Collars",
            "folder_id": "19211",
            "url": "https://www.shopbop.com/men-clothing-shirts-polos/br/v=1/19211.htm?f=MATShirtNeckline-Polo",
            "category": "Men > Our Edits > Polo Collars",
        },
        "Men > Our Edits > Stripes": {
            "department": "Men",
            "subcategory": "Our Edits",
            "leaf": "Stripes",
            "folder_id": "79599",
            "url": "https://www.shopbop.com/men-special-stripes/br/v=1/79599.htm",
            "category": "Men > Our Edits > Stripes",
        },
        "Men > Our Edits > The Golf Shop": {
            "department": "Men",
            "subcategory": "Our Edits",
            "leaf": "The Golf Shop",
            "folder_id": "73925",
            "url": "https://www.shopbop.com/men-shops-golf-shop/br/v=1/73925.htm",
            "category": "Men > Our Edits > The Golf Shop",
        },
        "Men > Our Edits > The Tennis Shop": {
            "department": "Men",
            "subcategory": "Our Edits",
            "leaf": "The Tennis Shop",
            "folder_id": "76299",
            "url": "https://www.shopbop.com/men-shops-tennis-shop/br/v=1/76299.htm",
            "category": "Men > Our Edits > The Tennis Shop",
        },
        "Men > Our Edits > Top Sellers": {
            "department": "Men",
            "subcategory": "Our Edits",
            "leaf": "Top Sellers",
            "folder_id": "22686",
            "url": "https://www.shopbop.com/men-shops-top-sellers/br/v=1/22686.htm",
            "category": "Men > Our Edits > Top Sellers",
        },
        "Men > Our Edits > Vacation Shop": {
            "department": "Men",
            "subcategory": "Our Edits",
            "leaf": "Vacation Shop",
            "folder_id": "61955",
            "url": "https://www.shopbop.com/men-shops-vacation-style/br/v=1/61955.htm",
            "category": "Men > Our Edits > Vacation Shop",
        },
        "Men > Sale": {
            "department": "Men",
            "subcategory": "Sale",
            "leaf": None,
            "folder_id": "19188",
            "url": "https://www.shopbop.com/sale/br/v=1/19188.htm",
            "category": "Men > Sale",
        },
        "Men > Sale > 20% Off": {
            "department": "Men",
            "subcategory": "Sale",
            "leaf": "20% Off",
            "folder_id": "19201",
            "url": "https://www.shopbop.com/sale-20-off/br/v=1/19201.htm",
            "category": "Men > Sale > 20% Off",
        },
        "Men > Sale > 30% Off": {
            "department": "Men",
            "subcategory": "Sale",
            "leaf": "30% Off",
            "folder_id": "19202",
            "url": "https://www.shopbop.com/sale-30-off/br/v=1/19202.htm",
            "category": "Men > Sale > 30% Off",
        },
        "Men > Sale > 40% Off": {
            "department": "Men",
            "subcategory": "Sale",
            "leaf": "40% Off",
            "folder_id": "19203",
            "url": "https://www.shopbop.com/sale-40-off/br/v=1/19203.htm",
            "category": "Men > Sale > 40% Off",
        },
        "Men > Sale > 50% Off - Final Sale": {
            "department": "Men",
            "subcategory": "Sale",
            "leaf": "50% Off - Final Sale",
            "folder_id": "19204",
            "url": "https://www.shopbop.com/sale-50-off-final/br/v=1/19204.htm",
            "category": "Men > Sale > 50% Off - Final Sale",
        },
        "Men > Sale > 60% Off & Over – Final Sale": {
            "department": "Men",
            "subcategory": "Sale",
            "leaf": "60% Off & Over – Final Sale",
            "folder_id": "19205",
            "url": "https://www.shopbop.com/sale-60-off-over-final/br/v=1/19205.htm",
            "category": "Men > Sale > 60% Off & Over – Final Sale",
        },
        "Men > Sale > Accessories": {
            "department": "Men",
            "subcategory": "Sale",
            "leaf": "Accessories",
            "folder_id": "19408",
            "url": "https://www.shopbop.com/sale-accessories/br/v=1/19408.htm",
            "category": "Men > Sale > Accessories",
        },
        "Men > Sale > Clothing": {
            "department": "Men",
            "subcategory": "Sale",
            "leaf": "Clothing",
            "folder_id": "19407",
            "url": "https://www.shopbop.com/sale-clothing/br/v=1/19407.htm",
            "category": "Men > Sale > Clothing",
        },
        "Men > Sale > New to Sale": {
            "department": "Men",
            "subcategory": "Sale",
            "leaf": "New to Sale",
            "folder_id": "19406",
            "url": "https://www.shopbop.com/sale-new/br/v=1/19406.htm",
            "category": "Men > Sale > New to Sale",
        },
        "Men > Sale > Shoes": {
            "department": "Men",
            "subcategory": "Sale",
            "leaf": "Shoes",
            "folder_id": "19329",
            "url": "https://www.shopbop.com/sale-shoes/br/v=1/19329.htm",
            "category": "Men > Sale > Shoes",
        },
        "Men > Shoes": {
            "department": "Men",
            "subcategory": "Shoes",
            "leaf": None,
            "folder_id": "19186",
            "url": "https://www.shopbop.com/men-shoes/br/v=1/19186.htm",
            "category": "Men > Shoes",
        },
        "Men > Shoes > Boots": {
            "department": "Men",
            "subcategory": "Shoes",
            "leaf": "Boots",
            "folder_id": "19217",
            "url": "https://www.shopbop.com/men-shoes-boots/br/v=1/19217.htm",
            "category": "Men > Shoes > Boots",
        },
        "Men > Shoes > Lace-Ups": {
            "department": "Men",
            "subcategory": "Shoes",
            "leaf": "Lace-Ups",
            "folder_id": "19218",
            "url": "https://www.shopbop.com/men-shoes-lace-ups/br/v=1/19218.htm",
            "category": "Men > Shoes > Lace-Ups",
        },
        "Men > Shoes > Loafers & Slip Ons": {
            "department": "Men",
            "subcategory": "Shoes",
            "leaf": "Loafers & Slip Ons",
            "folder_id": "19219",
            "url": "https://www.shopbop.com/men-shoes-loafers-slip-ons/br/v=1/19219.htm",
            "category": "Men > Shoes > Loafers & Slip Ons",
        },
        "Men > Shoes > Sandals": {
            "department": "Men",
            "subcategory": "Shoes",
            "leaf": "Sandals",
            "folder_id": "19220",
            "url": "https://www.shopbop.com/men-shoes-sandals/br/v=1/19220.htm",
            "category": "Men > Shoes > Sandals",
        },
        "Men > Shoes > Slippers": {
            "department": "Men",
            "subcategory": "Shoes",
            "leaf": "Slippers",
            "folder_id": "71609",
            "url": "https://www.shopbop.com/men-shoes-slippers/br/v=1/71609.htm",
            "category": "Men > Shoes > Slippers",
        },
        "Men > Shoes > Sneakers": {
            "department": "Men",
            "subcategory": "Shoes",
            "leaf": "Sneakers",
            "folder_id": "19221",
            "url": "https://www.shopbop.com/men-shoes-sneakers/br/v=1/19221.htm",
            "category": "Men > Shoes > Sneakers",
        },
        "Men > What's New": {
            "department": "Men",
            "subcategory": "What's New",
            "leaf": None,
            "folder_id": "19184",
            "url": "https://www.shopbop.com/men-whats-new/br/v=1/19184.htm",
            "category": "Men > What's New",
        },
        "Men > What's New > Accessories": {
            "department": "Men",
            "subcategory": "What's New",
            "leaf": "Accessories",
            "folder_id": "19398",
            "url": "https://www.shopbop.com/men-accessories/br/v=1/19398.htm",
            "category": "Men > What's New > Accessories",
        },
        "Men > What's New > Clothing": {
            "department": "Men",
            "subcategory": "What's New",
            "leaf": "Clothing",
            "folder_id": "19396",
            "url": "https://www.shopbop.com/men-clothing/br/v=1/19396.htm",
            "category": "Men > What's New > Clothing",
        },
        "Men > What's New > Shoes": {
            "department": "Men",
            "subcategory": "What's New",
            "leaf": "Shoes",
            "folder_id": "19397",
            "url": "https://www.shopbop.com/men-shoes/br/v=1/19397.htm",
            "category": "Men > What's New > Shoes",
        },
        "Men > What's New > Style for What's Next": {
            "department": "Men",
            "subcategory": "What's New",
            "leaf": "Style for What's Next",
            "folder_id": "80808",
            "url": "https://www.shopbop.com/men-special-fall-brand-campaign/br/v=1/80808.htm",
            "category": "Men > What's New > Style for What's Next",
        },
    },
    "Beauty": {
        "Beauty > Beauty": {
            "department": "Beauty",
            "subcategory": "Beauty",
            "leaf": None,
            "folder_id": "69175",
            "url": "https://www.shopbop.com/beauty/br/v=1/69175.htm",
            "category": "Beauty > Beauty",
        },
        "Beauty > Beauty > Bath & Body": {
            "department": "Beauty",
            "subcategory": "Beauty",
            "leaf": "Bath & Body",
            "folder_id": "69284",
            "url": "https://www.shopbop.com/beauty-bath-body/br/v=1/69284.htm",
            "category": "Beauty > Beauty > Bath & Body",
        },
        "Beauty > Beauty > Black-Led Brands": {
            "department": "Beauty",
            "subcategory": "Beauty",
            "leaf": "Black-Led Brands",
            "folder_id": "69292",
            "url": "https://www.shopbop.com/beauty-black-owned-brands/br/v=1/69292.htm",
            "category": "Beauty > Beauty > Black-Led Brands",
        },
        "Beauty > Beauty > Clean Beauty at Shopbop": {
            "department": "Beauty",
            "subcategory": "Beauty",
            "leaf": "Clean Beauty at Shopbop",
            "folder_id": "69291",
            "url": "https://www.shopbop.com/beauty-clean-beauty-at-shopbop/br/v=1/69291.htm",
            "category": "Beauty > Beauty > Clean Beauty at Shopbop",
        },
        "Beauty > Beauty > Fragrance & Candles": {
            "department": "Beauty",
            "subcategory": "Beauty",
            "leaf": "Fragrance & Candles",
            "folder_id": "71676",
            "url": "https://www.shopbop.com/beauty-fragrance-candles/br/v=1/71676.htm",
            "category": "Beauty > Beauty > Fragrance & Candles",
        },
        "Beauty > Beauty > Haircare": {
            "department": "Beauty",
            "subcategory": "Beauty",
            "leaf": "Haircare",
            "folder_id": "69286",
            "url": "https://www.shopbop.com/beauty-haircare/br/v=1/69286.htm",
            "category": "Beauty > Beauty > Haircare",
        },
        "Beauty > Beauty > Makeup": {
            "department": "Beauty",
            "subcategory": "Beauty",
            "leaf": "Makeup",
            "folder_id": "69288",
            "url": "https://www.shopbop.com/beauty-makeup/br/v=1/69288.htm",
            "category": "Beauty > Beauty > Makeup",
        },
        "Beauty > Beauty > Skin Saviors: goop beauty": {
            "department": "Beauty",
            "subcategory": "Beauty",
            "leaf": "Skin Saviors: goop beauty",
            "folder_id": "72376",
            "url": "https://www.shopbop.com/goop/br/v=1/72376.htm",
            "category": "Beauty > Beauty > Skin Saviors: goop beauty",
        },
        "Beauty > Beauty > Skincare": {
            "department": "Beauty",
            "subcategory": "Beauty",
            "leaf": "Skincare",
            "folder_id": "69289",
            "url": "https://www.shopbop.com/beauty-skincare/br/v=1/69289.htm",
            "category": "Beauty > Beauty > Skincare",
        },
        "Beauty > Beauty > Staffer Beauty Picks": {
            "department": "Beauty",
            "subcategory": "Beauty",
            "leaf": "Staffer Beauty Picks",
            "folder_id": "71645",
            "url": "https://www.shopbop.com/beauty-staffer-beauty-picks/br/v=1/71645.htm",
            "category": "Beauty > Beauty > Staffer Beauty Picks",
        },
        "Beauty > Beauty > Suncare": {
            "department": "Beauty",
            "subcategory": "Beauty",
            "leaf": "Suncare",
            "folder_id": "71917",
            "url": "https://www.shopbop.com/beauty-suncare/br/v=1/71917.htm",
            "category": "Beauty > Beauty > Suncare",
        },
        "Beauty > Beauty > Tools & Brushes": {
            "department": "Beauty",
            "subcategory": "Beauty",
            "leaf": "Tools & Brushes",
            "folder_id": "69290",
            "url": "https://www.shopbop.com/beauty-tools-brushes/br/v=1/69290.htm",
            "category": "Beauty > Beauty > Tools & Brushes",
        },
        "Beauty > Beauty > Top Sellers: Beauty": {
            "department": "Beauty",
            "subcategory": "Beauty",
            "leaf": "Top Sellers: Beauty",
            "folder_id": "70162",
            "url": "https://www.shopbop.com/our-must-haves-top-sellers-beauty/br/v=1/70162.htm",
            "category": "Beauty > Beauty > Top Sellers: Beauty",
        },
    },
}
