from __future__ import annotations

import re


STAPLES_CATEGORY_INVENTORY = {'Office Supplies': {'url': 'https://www.staples.com/Office-Supplies/cat_SC1',
                     'subcategories': {'Binders': 'https://www.staples.com/Binders/cat_CL167205',
                                       'Desk Organizers & Accessories': 'https://www.staples.com/Desk-Organizers-Accessories/cat_CG22',
                                       'Folders & Filing': 'https://www.staples.com/Folders-Filing/cat_CG3539',
                                       'Office Basics': 'https://www.staples.com/Office-Basics/cat_CG1036',
                                       'Tape, Fasteners & Adhesives': 'https://www.staples.com/Tape-Fasteners-Adhesives/cat_CG3745',
                                       'Storage & Organization': 'https://www.staples.com/Storage-Organization/cat_CG3633'}},
 'Printer Ink Cartridges & Toner Finder': {'url': 'https://www.staples.com/printer-ink-cartridges-toner-finder/cat_SC43',
                                           'subcategories': {'HP': 'https://www.staples.com/hp/cat_CG812',
                                                             'Epson Ink & Toner': 'https://www.staples.com/Epson-ink-cartridges-toner-cartridges/cat_CG782',
                                                             'Canon Ink & Toner': 'https://www.staples.com/Canon-ink-cartridges-toner-cartridges/cat_CG703',
                                                             'Brother Ink & Toner': 'https://www.staples.com/Brother-ink-cartridges-toner-cartridges/cat_CG628',
                                                             'Lexmark Ink & Toner': 'https://www.staples.com/Lexmark-ink-cartridges-toner-cartridges/cat_CG554',
                                                             'Samsung Ink & Toner': 'https://www.staples.com/Samsung-ink-cartridges-toner-cartridges/cat_CG682',
                                                             'Dell Ink & Toner': 'https://www.staples.com/Dell-ink-cartridges-toner-cartridges/cat_CG883',
                                                             'Toshiba Ink & Toner': 'https://www.staples.com/Toshiba-ink-cartridges-toner-cartridges/cat_CG711',
                                                             'Xerox Toner & Ink': 'https://www.staples.com/Xerox-ink-cartridges-toner-cartridges/cat_CG620',
                                                             'Sharp Ink & Toner': 'https://www.staples.com/Sharp-ink-cartridges-toner-cartridges/cat_CG817',
                                                             'OKI': 'https://www.staples.com/oki/cat_CG778',
                                                             'Ricoh Ink & Toner': 'https://www.staples.com/Ricoh/cat_CG704'}},
 'Shipping, Packing & Mailing Supplies': {'url': 'https://www.staples.com/Shipping-Packing-Mailing-Supplies/cat_SC5585',
                                          'subcategories': {'Packing Tape': 'https://www.staples.com/Packing-Tape/cat_CL140631',
                                                            'Packing Tape Dispensers': 'https://www.staples.com/Packing-Tape-Dispensers/cat_CL350620',
                                                            'Shipping Boxes': 'https://www.staples.com/Shipping-Boxes/cat_CL213835',
                                                            'Corrugated Boxes & Pads': 'https://www.staples.com/Corrugated-Boxes-Pads/cat_DP350125',
                                                            'Mailers': 'https://www.staples.com/Mailers/cat_CL142648',
                                                            'Cushioning & Void Fill': 'https://www.staples.com/Cushioning-Void-Fill/cat_DP350126',
                                                            'Postal Scales & Meters': 'https://www.staples.com/Postal-Scales-Meters/cat_CL141867',
                                                            'Literature & Mail Sorters': 'https://www.staples.com/Literature-Mail-Sorters/cat_CL141866',
                                                            'Poly Bags': 'https://www.staples.com/Poly-Bags/cat_CL350297',
                                                            'Strapping & Strapping Equipment': 'https://www.staples.com/Strapping-Strapping-Equipment/cat_DP350130',
                                                            'Paper Folding Machines & Joggers': 'https://www.staples.com/Paper-Folding-Machines-Joggers/cat_CL140639'}},
 'Paper': {'url': 'https://www.staples.com/Paper/cat_SC1676',
           'subcategories': {'Copy & Printer Paper': 'https://www.staples.com/Copy-Printer-Paper/cat_CL140691',
                             'Notebooks': 'https://www.staples.com/Notebooks/cat_CL165557',
                             'Notepads': 'https://www.staples.com/Notepads/cat_CL220835',
                             'Journals & Diaries': 'https://www.staples.com/Journals-Diaries/cat_CL166390',
                             'Fine Business & Resume Papers': 'https://www.staples.com/Fine-Business-Resume-Papers/cat_CL221518',
                             'Card Stock': 'https://www.staples.com/Card-Stock/cat_CL214438',
                             'Stationery & Invitations': 'https://www.staples.com/Stationery-Invitations/cat_CG350061',
                             'Forms & Recordkeeping': 'https://www.staples.com/Forms-Recordkeeping/cat_CG3717',
                             'Index Cards': 'https://www.staples.com/Index-Cards/cat_CL214476',
                             'Post-it® & Sticky Notes': 'https://www.staples.com/Post-it-Sticky-Notes/cat_CG3861'}},
 'Cleaning Supplies': {'url': 'https://www.staples.com/cleaning-supplies/cat_SC1683',
                       'subcategories': {'Janitorial Paper Dispensers': 'https://www.staples.com/Janitorial-Paper-Dispensers/cat_CG3930',
                                         'Cleaning Chemicals & Wipes': 'https://www.staples.com/Cleaning-Chemicals-Disinfectants/cat_CG3668',
                                         'Hand Sanitizer': 'https://www.staples.com/Hand-Sanitizer/cat_CL220928',
                                         'Hand Soaps & Sanitizers': 'https://www.staples.com/Hand-Soaps-Sanitizers/cat_CG3931',
                                         'Natural Cleaning Supplies': 'https://www.staples.com/natural-cleaning-supplies/cat_CG350171',
                                         'Waste & Recycling': 'https://www.staples.com/Waste-Recycling-Products/cat_CG2827',
                                         'Laundry Detergent': 'https://www.staples.com/Laundry-Detergent/cat_CL168322',
                                         'Cleaning Tools': 'https://www.staples.com/Cleaning-Tools/cat_CG3928'}},
 'Furniture': {'url': 'https://www.staples.com/Furniture-Chairs-Cabinets/cat_SC2',
               'subcategories': {'Chairs & Seating': 'https://www.staples.com/Chairs-Seating/cat_CG32',
                                 'File Cabinets': 'https://www.staples.com/File-Cabinets/cat_CL70401',
                                 'Bookcases & Bookshelves': 'https://www.staples.com/Bookcases-Bookshelves/cat_CL166206',
                                 'Kids Seating': 'https://www.staples.com/kids-seating/cat_DP10543',
                                 'Desks': 'https://www.staples.com/desks/cat_CG33',
                                 'Home & Office Tables': 'https://www.staples.com/home-office-tables/cat_CG39',
                                 'Boards & Easels': 'https://www.staples.com/Boards-Easels-Dry-Erase/cat_CG101'}},
 'Facilities': {'url': 'https://www.staples.com/Facilities/cat_SC350045',
                'subcategories': {'Commercial Lighting, Ballasts & Bulbs': 'https://www.staples.com/Commercial-Lighting-Ballasts-Bulbs/cat_DP10986',
                                  'Air Quality': 'https://www.staples.com/Air-Quality/cat_DP10983',
                                  'Hardware': 'https://www.staples.com/Hardware/cat_CG350121',
                                  'Grounds Maintenance': 'https://www.staples.com/Grounds-Maintenance/cat_CG350176',
                                  'Hand & Power Tools': 'https://www.staples.com/Hand-Power-Tools/cat_CG350126',
                                  'Paint Supplies': 'https://www.staples.com/Paint-Supplies/cat_CG350152',
                                  'Plumbing': 'https://www.staples.com/Plumbing/cat_CG350111',
                                  'Power Management': 'https://www.staples.com/power-management/cat_CG1375',
                                  'Sealants & Caulking': 'https://www.staples.com/Sealants-Caulking/cat_CL167177'}},
 'Computers & Accessories': {'url': 'https://www.staples.com/computers-accessories/cat_SC3',
                             'subcategories': {'Computer Monitors': 'https://www.staples.com/Computer-Monitors/cat_CL142219',
                                               'Webcams': 'https://www.staples.com/Webcams/cat_CL140467',
                                               'Desktop Computers': 'https://www.staples.com/Desktop-Computers/cat_CL167288'}},
 'Coffee, Water & Snacks': {'url': 'https://www.staples.com/Coffee-Water-Snacks/cat_SC1684',
                            'subcategories': {'Coffee, Coffee Makers & Supplies': 'https://www.staples.com/coffee-coffee-makers-supplies/cat_CG1038',
                                              'Water & Beverages': 'https://www.staples.com/water-beverages/cat_CG1251',
                                              'Snacks & Food': 'https://www.staples.com/Snacks-Meals/cat_CG3609',
                                              'Coffee Makers & Espresso Machines': 'https://www.staples.com/Coffee-Makers-Espresso-Machines/cat_CL140860',
                                              'Plates, Cups & Cutlery': 'https://www.staples.com/Disposable-Tableware/cat_CG3813',
                                              'Candy, Gum & Mints': 'https://www.staples.com/Candy-Gum-Mints/cat_CG1253'}},
 'Shredders, Projectors & Office Machines': {'url': 'https://www.staples.com/shredders-projectors-office-machines/cat_SC1681',
                                             'subcategories': {'Shredders': 'https://www.staples.com/Shredders/cat_CL141980',
                                                               'Projectors & Accessories': 'https://www.staples.com/Projectors-Accessories/cat_CG3474',
                                                               'Calculators': 'https://www.staples.com/Calculators/cat_CG3981',
                                                               'Label Makers & Tapes': 'https://www.staples.com/Label-Makers-Tapes/cat_CG3619',
                                                               'Phones & Accessories': 'https://www.staples.com/Telephones-Accessories/cat_CG14',
                                                               'Copiers': 'https://www.staples.com/Copiers/cat_CL90200',
                                                               'Fax Machines': 'https://www.staples.com/Fax-Machines/cat_CL165742',
                                                               'Headsets': 'https://www.staples.com/Headsets/cat_CL140478',
                                                               'Typewriters & Typewriter Supplies': 'https://www.staples.com/Typewriters-Typewriter-Supplies/cat_CL90800',
                                                               'Barcode Scanners & Readers': 'https://www.staples.com/Barcode-Scanners-Readers/cat_CL141846'}},
 'Education': {'url': 'https://www.staples.com/education/cat_SC1686',
               'subcategories': {'Classroom Decorations': 'https://www.staples.com/Classroom-Decorations/cat_DP5229',
                                 'Games, Puzzles & Toys': 'https://www.staples.com/Games-Puzzles-Toys/cat_CG3880',
                                 'Musical Instruments': 'https://www.staples.com/Musical-Instruments/cat_CL207326',
                                 'Classroom Books & Digital Media': 'https://www.staples.com/Classroom-Books-Digital-Media/cat_DP5205',
                                 'Physical Education & Outdoor Play': 'https://www.staples.com/Physical-Education-Outdoor-Play/cat_CG3201',
                                 'Rewards & Incentives': 'https://www.staples.com/Rewards-Incentives/cat_CG3893',
                                 'Teacher Resources': 'https://www.staples.com/Teacher-Resources/cat_DP5228',
                                 'Lesson Plans & Grade Books': 'https://www.staples.com/Lesson-Plans-Grade-Books/cat_CL207302',
                                 'Classroom Posters & Charts': 'https://www.staples.com/Classroom-Posters-Charts/cat_CL166104'}},
 'Printers & Scanners': {'url': 'https://www.staples.com/printers-scanners/cat_SC5435',
                         'subcategories': {'Printers': 'https://www.staples.com/Printers/cat_CL167883',
                                           'Scanners': 'https://www.staples.com/Scanners/cat_CL158948',
                                           'Printer Accessories & Replacement Parts': 'https://www.staples.com/Printer-Accessories-Replacement-Parts/cat_CL140828',
                                           '3D Printers': 'https://www.staples.com/3D-Printers/cat_CL211598'}},
 'Networking & WiFi': {'url': 'https://www.staples.com/networking-wifi/cat_SC5487',
                       'subcategories': {'Adapters & Access Points': 'https://www.staples.com/Adapters-Access-Points/cat_CG3708',
                                         'Wireless Access Points': 'https://www.staples.com/Wireless-Access-Points/cat_CL215781',
                                         'Modems': 'https://www.staples.com/Modems/cat_CL140458',
                                         'NAS / Cloud Storage': 'https://www.staples.com/nas-cloud-storage/cat_CL164718',
                                         'Mesh WiFi Systems': 'https://www.staples.com/Mesh-WiFi-Systems/cat_CL220815'}},
 'Bags, Backpacks & Luggage': {'url': 'https://www.staples.com/Bags-Backpacks-Luggage/cat_SC5884',
                               'subcategories': {'Lunch Bags & Boxes': 'https://www.staples.com/Lunch-Bags-Boxes/cat_CL165124',
                                                 'Briefcases': 'https://www.staples.com/Briefcases/cat_CL216485',
                                                 'Laptop Bags': 'https://www.staples.com/Laptop-Bags/cat_CL140978',
                                                 'Backpacks': 'https://www.staples.com/Backpacks/cat_CL142745'}},
 'Computer Software': {'url': 'https://www.staples.com/Computer-Software/cat_SC1941',
                       'subcategories': {'Office & Business Software': 'https://www.staples.com/Office-Business-Software/cat_CG3692',
                                         'Windows Operating Systems': 'https://www.staples.com/Windows-Operating-Systems/cat_CL167740',
                                         'Antivirus & Internet Security Software': 'https://www.staples.com/Antivirus-Internet-Security-Software/cat_CG3694',
                                         'Accounting & Finance Software': 'https://www.staples.com/Accounting-Finance-Software/cat_CG3789',
                                         'Tax Software': 'https://www.staples.com/Tax-Software/cat_CL166056',
                                         'Photo Editing & Graphic Design Software': 'https://www.staples.com/Photo-Editing-Graphic-Design-Software/cat_CL167778',
                                         'Hobbies & Personal Interest Software': 'https://www.staples.com/Hobbies-Personal-Interest-Software/cat_CL167741',
                                         'Education & Language Learning Software': 'https://www.staples.com/Education-Language-Learning-Software/cat_CL167771',
                                         'PC Games': 'https://www.staples.com/PC-Games/cat_CL165725'}},
 'Healthcare Supplies': {'url': 'https://www.staples.com/Healthcare-Supplies/cat_SC1929',
                         'subcategories': {'Dental Supplies': 'https://www.staples.com/Dental/cat_CG3399'}},
 'Cell Phone Accessories': {'url': 'https://www.staples.com/Cell-Phones-Accessories/cat_SC5308',
                            'subcategories': {'Chargers & Charging Cables': 'https://www.staples.com/Chargers-Charging-Cables/cat_CL162051',
                                              'Cell Phones': 'https://www.staples.com/Cell-Phones/cat_CL166921',
                                              'Cell Phone Cases': 'https://www.staples.com/Cell-Phone-Cases/cat_CL206053',
                                              'Cell Phone Screen Protectors': 'https://www.staples.com/Cell-Phone-Screen-Protectors/cat_CL216706',
                                              'Cell Phone Docks & Mounts': 'https://www.staples.com/Cell-Phone-Mounts-Holders/cat_CL206054'}},
 'Tablets & iPads': {'url': 'https://www.staples.com/tablets-ipads/cat_SC5326',
                     'subcategories': {'Tablets & iPads': 'https://www.staples.com/tablets-ipads/cat_CL204449',
                                       'E-Readers': 'https://www.staples.com/E-Readers/cat_CL164364',
                                       'Tablet & iPad Cases, Covers & Keyboards': 'https://www.staples.com/Tablet-iPad-Cases-Covers-Keyboards/cat_CL166405',
                                       'Tablet Screen Protectors': 'https://www.staples.com/Tablet-Screen-Protectors/cat_CL166407',
                                       'Tablet Stands & Mounts': 'https://www.staples.com/Tablet-Stands-Mounts/cat_CL166415',
                                       'Stylus & Smart Pens': 'https://www.staples.com/Stylus-Smart-Pens/cat_CL166408'}},
 'Safety Supplies': {'url': 'https://www.staples.com/Safety-Supplies/cat_SC1718',
                     'subcategories': {'Fall Protection': 'https://www.staples.com/Fall-Protection/cat_DP5079',
                                       'Fire Protection': 'https://www.staples.com/Fire-Protection/cat_DP5201',
                                       'Traffic Safety': 'https://www.staples.com/Traffic-Safety/cat_DP5085',
                                       'Personal Protective Equipment (PPE)': 'https://www.staples.com/Personal-Protective-Equipment-PPE/cat_CG1398',
                                       'Safety Storage': 'https://www.staples.com/Safety-Storage/cat_CG1364',
                                       'Disposable Gloves': 'https://www.staples.com/Disposable-Gloves/cat_CL167009'}},
 'Smart Home & Security': {'url': 'https://www.staples.com/Smart-Home-Security/cat_SC5529',
                           'subcategories': {'Smart Speakers & Displays': 'https://www.staples.com/Smart-Speakers-Displays/cat_CL216608',
                                             'Smart Locks': 'https://www.staples.com/Smart-Locks/cat_CL216607',
                                             'Smart Bulbs': 'https://www.staples.com/Smart-Bulbs/cat_CL353947',
                                             'Security Cameras & Systems': 'https://www.staples.com/Security-Cameras-Systems/cat_CL160405',
                                             'Smart Plugs & Outlets': 'https://www.staples.com/Smart-Plugs-Outlets/cat_CL211550',
                                             'Smart Thermostats': 'https://www.staples.com/Smart-Thermostats/cat_CL211415',
                                             'Security System Accessories': 'https://www.staples.com/Security-System-Accessories/cat_CL163142',
                                             'Smart Doorbells': 'https://www.staples.com/Smart-Doorbells/cat_CL353945',
                                             'Smart Light Switches & Dimmers': 'https://www.staples.com/Smart-Light-Switches-Dimmers/cat_CL353946',
                                             'Smart Sensors': 'https://www.staples.com/Smart-Sensors/cat_CL211416'}},
 'Arts & Crafts': {'url': 'https://www.staples.com/Arts-Crafts/cat_SC5787',
                   'subcategories': {'Crafting': 'https://www.staples.com/Crafting/cat_DP10798',
                                     'Scrapbooking': 'https://www.staples.com/Scrapbooking/cat_DP9640',
                                     'Coloring Books': 'https://www.staples.com/Coloring-Books/cat_CL219108',
                                     'Paint': 'https://www.staples.com/Paint/cat_CL140420',
                                     'Drawing Tools & Supplies': 'https://www.staples.com/Drawing-Tools-Supplies/cat_CL110202'}},
 'Workwear': {'url': 'https://www.staples.com/Workwear/cat_SC5803',
              'subcategories': {'Workwear & Rainwear': 'https://www.staples.com/Workwear-Rainwear/cat_DP9817',
                                'Restaurant Apparel': 'https://www.staples.com/Restaurant-Apparel/cat_DP9818',
                                'Healthcare Apparel': 'https://www.staples.com/Staff-Apparel/cat_DP5426',
                                'Lab Apparel': 'https://www.staples.com/Lab-Science/cat_DP9819'}},
 'Gaming': {'url': 'https://www.staples.com/Gaming/cat_SC5841',
            'subcategories': {'Xbox One Video Games': 'https://www.staples.com/xbox-one-video-games/cat_CL350107',
                              'Xbox One Accessories': 'https://www.staples.com/xbox-one-accessories/cat_CL216222',
                              'PS4 Video Games': 'https://www.staples.com/PS4-Video-Games/cat_CL350097',
                              'Nintendo Switch Games': 'https://www.staples.com/nintendo-switch/cat_CL350266'}},
 'Security, Banking & Cash': {'url': 'https://www.staples.com/Security-Banking-Cash/cat_SC5881',
                              'subcategories': {'Cash Handling': 'https://www.staples.com/Cash-Handling/cat_CG3379',
                                                'Tickets & Tags': 'https://www.staples.com/Pricing-Tickets-Tags/cat_CL206119',
                                                'Safes & Secure Storage': 'https://www.staples.com/Safes-Secure-Storage/cat_CL158854',
                                                'Call Bells': 'https://www.staples.com/Call-Bells/cat_CL142096'}},
 'Audio': {'url': 'https://www.staples.com/audio/cat_SC5829',
           'subcategories': {'Portable Speakers & Radios': 'https://www.staples.com/Portable-Speakers-Radios/cat_CL167926'}},
 'Tech Services': {'url': 'https://www.staples.com/Tech-Services/cat_SC5863', 'subcategories': {}},
 'Laboratory & Scientific Supplies': {'url': 'https://www.staples.com/Laboratory-Scientific-Supplies/cat_SC350020',
                                      'subcategories': {'Hazardous Material Lab Storage': 'https://www.staples.com/hazardous-material-lab-storage/cat_CL215399'}},
 'Tools, Parts & Supplies': {'url': 'https://www.staples.com/Tools-Parts-Supplies/cat_SC5886',
                             'subcategories': {'Chemicals, Lubricants & Paints': 'https://www.staples.com/Lubricants-Penetrants/cat_CG1373',
                                               'Measuring & Leveling Tools': 'https://www.staples.com/Measuring-Leveling-Tools/cat_CG3969',
                                               'Tool & Garage Organization': 'https://www.staples.com/Tool-Garage-Organization/cat_CG3977',
                                               'Chalk Reels & Marking Tools': 'https://www.staples.com/Chalk-Reels-Marking-Tools/cat_CG3966'}},
 'Restaurant & Foodservice Supplies': {'url': 'https://www.staples.com/restaurant-foodservice-supplies/cat_SC5542',
                                       'subcategories': {'Smallwares': 'https://www.staples.com/Bar-Supplies-Equipment/cat_CG3140',
                                                         'Restaurant Apparel': 'https://www.staples.com/Restaurant-Apparel/cat_CG3136',
                                                         'Restaurant Storage & Transport': 'https://www.staples.com/Restaurant-Storage-Transport/cat_CG3549',
                                                         'Restaurant Janitorial': 'https://www.staples.com/Restaurant-Janitorial/cat_CG3550',
                                                         'Restaurant Furniture': 'https://www.staples.com/Restaurant-Furniture/cat_CG3548',
                                                         'Tabletop': 'https://www.staples.com/Tabletop/cat_CG3547'}},
 'Retail Store Supplies': {'url': 'https://www.staples.com/Retail-Store-Supplies/cat_SC5421',
                           'subcategories': {'Store Fixtures & Retail Displays': 'https://www.staples.com/Store-Fixtures-Retail-Displays/cat_CG2898',
                                             'Store Security & Operations': 'https://www.staples.com/Store-Retail-Security-Operations/cat_CG2902',
                                             'Backroom Retail Supplies': 'https://www.staples.com/Backroom-Retail-Supplies/cat_CG2897',
                                             'Retail Packaging': 'https://www.staples.com/Bags-Packaging/cat_CG2901',
                                             'Retail Signage': 'https://www.staples.com/Retail-Signage/cat_CG3112',
                                             'Point of Sale (POS) Equipment': 'https://www.staples.com/Point-of-Sale-Equipment/cat_CG2899',
                                             'Time Clocks & Cards': 'https://www.staples.com/Time-Clocks-Cards/cat_DP3901',
                                             'Pricing & Tagging': 'https://www.staples.com/pricing-tagging/cat_CG2900'}},
 'Office Decor, Homewares & Appliances': {'url': 'https://www.staples.com/Office-Decor-Homewares-Appliances/cat_SC5791',
                                          'subcategories': {'Decor': 'https://www.staples.com/Decor/cat_CG853',
                                                            'Appliances': 'https://www.staples.com/Kitchen-Appliances/cat_CG3156',
                                                            'Picture Frames & Photo Albums': 'https://www.staples.com/Picture-Frames-Photo-Albums/cat_CL161523',
                                                            'Desk Lamps': 'https://www.staples.com/Desk-Lamps/cat_CL167867',
                                                            'Floor Lamps': 'https://www.staples.com/Floor-Lamps/cat_CL216710',
                                                            'Clocks & Timers': 'https://www.staples.com/Clocks/cat_CL161533',
                                                            'Dining & Entertainment': 'https://www.staples.com/Dining-Entertainment/cat_CG3409',
                                                            'Kitchen Storage & Organization': 'https://www.staples.com/Kitchen-Storage-Organization/cat_CL142181'}},
 'TV & Streaming Media': {'url': 'https://www.staples.com/TV-Streaming-Media/cat_SC5917',
                          'subcategories': {'Streaming Media Players': 'https://www.staples.com/Streaming-Media-Players/cat_CG3572',
                                            'TVs': 'https://www.staples.com/TVs/cat_CL164870',
                                            'Home Theater Audio': 'https://www.staples.com/Home-Audio/cat_DP5070',
                                            'TV Accessories': 'https://www.staples.com/TV-Accessories/cat_CL168253',
                                            'TV Wall Mounts & Stands': 'https://www.staples.com/TV-Wall-Mounts/cat_CL142753'}},
 'Gift Shop': {'url': 'https://www.staples.com/Gift-Shop/cat_SC1699',
               'subcategories': {'Home, Personal & Travel': 'https://www.staples.com/Home-Personal-Travel/cat_CG3762',
                                 'Gift Cards': 'https://www.staples.com/gift-cards/cat_SC5857',
                                 'Game Room & Toys': 'https://www.staples.com/Gifts-Games-Accessories/cat_CG2853',
                                 'Gift Sets, Photo & Custom Gifts': 'https://www.staples.com/Gift-Sets-Photo-Custom-Gifts/cat_CG3760',
                                 'Professional Gifts': 'https://www.staples.com/Executive-Gifts/cat_CG3761',
                                 'Party Supplies & Decor': 'https://www.staples.com/party-supplies-decor/cat_CG3363'}},
 'School Supplies': {'url': 'https://www.staples.com/School-Supplies/cat_SC350235',
                     'subcategories': {'Preschool Supplies': 'https://www.staples.com/preschool-supplies/cat_CG350600',
                                       'Elementary School Supplies': 'https://www.staples.com/elementary-school-supplies/cat_CG350606',
                                       'Middle School Supplies': 'https://www.staples.com/middle-school-supplies/cat_CG350612',
                                       'High School Supplies': 'https://www.staples.com/high-school-supplies/cat_CG350614',
                                       'College Supplies': 'https://www.staples.com/college-supplies/cat_CG350616',
                                       'School Tech': 'https://www.staples.com/school-tech/cat_CG350603',
                                       'School Art Supplies': 'https://www.staples.com/school-art-supplies/cat_CG350597',
                                       'School Bags & Lunch Boxes': 'https://www.staples.com/school-bags-lunch-boxes/cat_CG350602',
                                       'Learning at Home': 'https://www.staples.com/learning-at-home/cat_CG350598',
                                       'Classroom Essentials': 'https://www.staples.com/classroom-essentials/cat_CG350601',
                                       'Shop by Subject': 'https://www.staples.com/shop-by-subject/cat_CG350599'}}}


def _slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")


def _flatten_categories() -> list[dict[str, str]]:
    categories: list[dict[str, str]] = []
    seen_urls: set[str] = set()
    used_names: set[str] = set()
    for root, group in STAPLES_CATEGORY_INVENTORY.items():
        entries = [(root, group["url"]), *group["subcategories"].items()]
        for label, url in entries:
            if url in seen_urls:
                continue
            seen_urls.add(url)
            base = _slug(label)
            name = base
            if name in used_names:
                name = f"{_slug(root)}-{base}"
            suffix = 2
            while name in used_names:
                name = f"{_slug(root)}-{base}-{suffix}"
                suffix += 1
            used_names.add(name)
            categories.append({"category": name, "department": root, "subcategory": label, "url": url})
    return categories


STAPLES_CATEGORIES = _flatten_categories()
